/**
 * @generated by @flusk/cli
 * Docker Compose generator (standalone)
 */

import { resolve } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { generateDockerComposeTemplate } from '../templates/infrastructure/docker-compose.template.js';
import type { DockerComposeOptions } from '../templates/infrastructure/docker-compose.template.js';

export interface GeneratorResult {
  path: string;
  content: string;
}

export async function generateDockerCompose(
  options: DockerComposeOptions
): Promise<GeneratorResult> {
  const content = generateDockerComposeTemplate(options);
  const outputPath = resolve(process.cwd(), 'docker-compose.yml');
  await writeFile(outputPath, content, 'utf-8');
  return { path: 'docker-compose.yml', content };
}
