/**
 * @generated by @flusk/cli
 * Dockerfile generator
 */

import { resolve } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { generateDockerfileTemplate } from '../templates/infrastructure/dockerfile.template.js';
import type { DockerfileOptions } from '../templates/infrastructure/dockerfile.template.js';

export interface GeneratorResult {
  path: string;
  content: string;
}

export async function generateDockerfile(
  options: DockerfileOptions = {}
): Promise<GeneratorResult> {
  const content = generateDockerfileTemplate(options);
  const outputPath = resolve(process.cwd(), 'Dockerfile');
  await writeFile(outputPath, content, 'utf-8');
  return { path: 'Dockerfile', content };
}
