/**
 * @generated by @flusk/cli
 * Fastify plugin generator - creates fp-wrapped plugins
 */

import { resolve } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import { toPascalCase, toCamelCase } from './utils.js';

export interface FastifyPluginGenOptions {
  name: string;
  package?: string;
  withConfig?: boolean;
  withDecorator?: boolean;
}

export interface GenResult {
  files: { path: string; action: 'created' }[];
}

export function generateFastifyPluginContent(opts: FastifyPluginGenOptions): string {
  const pascal = toPascalCase(opts.name);
  const camel = toCamelCase(opts.name);
  const configBlock = opts.withConfig ? generateConfigBlock(pascal) : '';
  const decoratorLine = opts.withDecorator
    ? `\n  app.decorate('${camel}', {});\n`
    : '';

  return `/**
 * @generated by @flusk/cli
 */
import fp from 'fastify-plugin';
import type { FastifyInstance } from 'fastify';
import { getLogger } from '@flusk/logger';

const logger = getLogger().child({ module: '${opts.name}-plugin' });

export interface ${pascal}PluginOptions {
  // TODO: add plugin options
}
${configBlock}
async function ${camel}Plugin(
  app: FastifyInstance,
  opts: ${pascal}PluginOptions,
): Promise<void> {
  logger.info({ opts }, '${opts.name} plugin registered');
  // TODO: plugin logic${decoratorLine}
}

export const ${camel}PluginFp = fp(${camel}Plugin, {
  name: '${opts.name}-plugin',
});
`;
}

function generateConfigBlock(pascal: string): string {
  return `
export const ${pascal}EnvSchema = {
  type: 'object' as const,
  properties: {
    // TODO: add env vars
  },
};
`;
}

export function generateFastifyPluginTestContent(name: string): string {
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';

describe('${name} plugin', () => {
  it('should export plugin function', async () => {
    const mod = await import('../${name}.plugin.js');
    expect(mod.${camel}PluginFp).toBeDefined();
  });
});
`;
}

export async function generateFastifyPlugin(opts: FastifyPluginGenOptions): Promise<GenResult> {
  const root = process.cwd();
  const pkg = opts.package ?? 'otel';
  const dir = resolve(root, `packages/${pkg}/src/plugins`);
  const testDir = resolve(dir, '__tests__');
  await mkdir(testDir, { recursive: true });

  const result: GenResult = { files: [] };
  const filePath = `packages/${pkg}/src/plugins/${opts.name}.plugin.ts`;
  await writeFile(resolve(root, filePath), generateFastifyPluginContent(opts), 'utf-8');
  result.files.push({ path: filePath, action: 'created' });

  const testPath = `packages/${pkg}/src/plugins/__tests__/${opts.name}.plugin.test.ts`;
  await writeFile(resolve(root, testPath), generateFastifyPluginTestContent(opts.name), 'utf-8');
  result.files.push({ path: testPath, action: 'created' });

  return result;
}
