/**
 * Unit tests for fastify-plugin generator
 */

import { test, describe } from 'node:test';
import assert from 'node:assert';
import { generateFastifyPluginContent, generateFastifyPluginTestContent } from './fastify-plugin.generator.js';

describe('Fastify Plugin Generator', () => {
  test('generates plugin with fp wrapper', () => {
    const content = generateFastifyPluginContent({ name: 'flame-profile' });
    assert.ok(content.includes("import fp from 'fastify-plugin'"));
    assert.ok(content.includes('FlameProfilePluginOptions'));
    assert.ok(content.includes('flameProfilePluginFp'));
    assert.ok(content.includes("name: 'flame-profile-plugin'"));
  });

  test('includes @generated header', () => {
    const content = generateFastifyPluginContent({ name: 'test' });
    assert.ok(content.includes('@generated by @flusk/cli'));
  });

  test('adds config block with --with-config', () => {
    const content = generateFastifyPluginContent({ name: 'test', withConfig: true });
    assert.ok(content.includes('EnvSchema'));
  });

  test('adds decorator with --with-decorator', () => {
    const content = generateFastifyPluginContent({ name: 'test', withDecorator: true });
    assert.ok(content.includes("app.decorate('test'"));
  });

  test('generates test file', () => {
    const content = generateFastifyPluginTestContent('flame-profile');
    assert.ok(content.includes('flameProfilePluginFp'));
  });
});
