/**
 * Infrastructure generator - creates docker-compose.yml, .gitignore, .env.example, watt.json
 */

import { resolve } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { generateDockerComposeTemplate } from '../templates/infrastructure/docker-compose.template.js';
import { generateGitignoreTemplate } from '../templates/infrastructure/gitignore.template.js';
import { generateEnvTemplate } from '../templates/infrastructure/env.template.js';
import { generateWattTemplate } from '../templates/infrastructure/watt.template.js';

export interface GeneratorResult {
  path: string;
  content: string;
}

export interface InfrastructureOptions {
  projectName: string;
  targetDir?: string;
  skipDockerCompose?: boolean;
  skipGitignore?: boolean;
  skipEnv?: boolean;
  skipWatt?: boolean;
}

/**
 * Generate all infrastructure files
 */
export async function generateInfrastructure(
  options: InfrastructureOptions
): Promise<GeneratorResult[]> {
  const results: GeneratorResult[] = [];
  const { projectName, targetDir = process.cwd() } = options;

  // Ensure target directory exists
  if (!existsSync(targetDir)) {
    await mkdir(targetDir, { recursive: true });
  }

  // Generate docker-compose.yml
  if (!options.skipDockerCompose) {
    const dockerComposeResult = await generateDockerCompose(projectName, targetDir);
    results.push(dockerComposeResult);
  }

  // Generate .gitignore
  if (!options.skipGitignore) {
    const gitignoreResult = await generateGitignore(targetDir);
    results.push(gitignoreResult);
  }

  // Generate .env.example
  if (!options.skipEnv) {
    const envResult = await generateEnvExample(projectName, targetDir);
    results.push(envResult);
  }

  // Generate watt.json
  if (!options.skipWatt) {
    const wattResult = await generateWattConfig(projectName, targetDir);
    results.push(wattResult);
  }

  return results;
}

/**
 * Generate docker-compose.yml
 */
async function generateDockerCompose(
  projectName: string,
  targetDir: string
): Promise<GeneratorResult> {
  const outputPath = resolve(targetDir, 'docker-compose.yml');
  const content = generateDockerComposeTemplate({ projectName });

  await writeFile(outputPath, content, 'utf-8');

  return {
    path: 'docker-compose.yml',
    content
  };
}

/**
 * Generate .gitignore
 */
async function generateGitignore(targetDir: string): Promise<GeneratorResult> {
  const outputPath = resolve(targetDir, '.gitignore');
  const content = generateGitignoreTemplate();

  await writeFile(outputPath, content, 'utf-8');

  return {
    path: '.gitignore',
    content
  };
}

/**
 * Generate .env.example
 */
async function generateEnvExample(
  projectName: string,
  targetDir: string
): Promise<GeneratorResult> {
  const outputPath = resolve(targetDir, '.env.example');
  const content = generateEnvTemplate({ projectName });

  await writeFile(outputPath, content, 'utf-8');

  return {
    path: '.env.example',
    content
  };
}

/**
 * Generate watt.json
 */
async function generateWattConfig(
  projectName: string,
  targetDir: string
): Promise<GeneratorResult> {
  const outputPath = resolve(targetDir, 'watt.json');
  const content = generateWattTemplate({ projectName });

  await writeFile(outputPath, content, 'utf-8');

  return {
    path: 'watt.json',
    content
  };
}

/**
 * Generate database initialization script
 */
export async function generateInitDbScript(targetDir: string): Promise<GeneratorResult> {
  const scriptsDir = resolve(targetDir, 'scripts');
  const outputPath = resolve(scriptsDir, 'init-db.sql');

  if (!existsSync(scriptsDir)) {
    await mkdir(scriptsDir, { recursive: true });
  }

  const content = `-- @generated by @flusk/cli
-- PostgreSQL initialization script

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Set timezone
SET timezone = 'UTC';

-- Create updated_at function (reusable for all tables)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Log initialization
DO $$
BEGIN
  RAISE NOTICE 'Flusk database initialized successfully';
END $$;
`;

  await writeFile(outputPath, content, 'utf-8');

  return {
    path: 'scripts/init-db.sql',
    content
  };
}
