/**
 * @generated by @flusk/cli
 * OTel hook generator - creates SpanProcessor implementations
 */

import { resolve } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import { toPascalCase } from './utils.js';

export interface OtelHookGenOptions {
  name: string;
  spanFilter?: string;
}

export interface GenResult {
  files: { path: string; action: 'created' }[];
}

export function generateOtelHookContent(opts: OtelHookGenOptions): string {
  const pascal = toPascalCase(opts.name);
  const filterBlock = opts.spanFilter
    ? generateFilterBlock(opts.spanFilter)
    : '';

  return `/**
 * @generated by @flusk/cli
 */
import type {
  ReadableSpan,
  Span,
  SpanProcessor,
} from '@opentelemetry/sdk-trace-base';
${filterBlock}
export class ${pascal}Hook implements SpanProcessor {
  onStart(span: Span): void {
    // TODO: handle span start
  }

  onEnd(span: ReadableSpan): void {
    // TODO: handle span end
  }

  async shutdown(): Promise<void> {
    // cleanup
  }

  async forceFlush(): Promise<void> {
    // no-op
  }
}
`;
}

function generateFilterBlock(filter: string): string {
  const prefixes = filter.split(',').map((p) => `'${p.trim()}'`);
  return `
const SPAN_PREFIXES = [${prefixes.join(', ')}];

function matchesFilter(span: Span): boolean {
  const name = (span as unknown as { name: string }).name ?? '';
  return SPAN_PREFIXES.some((p) => name.toLowerCase().includes(p));
}
`;
}

export function generateOtelHookTestContent(name: string): string {
  const pascal = toPascalCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';
import { ${pascal}Hook } from '../${name}.hook.js';

describe('${pascal}Hook', () => {
  it('should implement SpanProcessor interface', () => {
    const hook = new ${pascal}Hook();
    expect(hook.onStart).toBeDefined();
    expect(hook.onEnd).toBeDefined();
    expect(hook.shutdown).toBeDefined();
    expect(hook.forceFlush).toBeDefined();
  });
});
`;
}

export async function generateOtelHook(opts: OtelHookGenOptions): Promise<GenResult> {
  const root = process.cwd();
  const dir = resolve(root, 'packages/otel/src/hooks');
  const testDir = resolve(dir, '__tests__');
  await mkdir(testDir, { recursive: true });

  const result: GenResult = { files: [] };
  const filePath = `packages/otel/src/hooks/${opts.name}.hook.ts`;
  await writeFile(resolve(root, filePath), generateOtelHookContent(opts), 'utf-8');
  result.files.push({ path: filePath, action: 'created' });

  const testPath = `packages/otel/src/hooks/__tests__/${opts.name}.hook.test.ts`;
  await writeFile(resolve(root, testPath), generateOtelHookTestContent(opts.name), 'utf-8');
  result.files.push({ path: testPath, action: 'created' });

  return result;
}
