/**
 * @generated by @flusk/cli
 * Plugin generator - creates Fastify plugins with encapsulation
 */

import { resolve } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { generatePluginTemplate, generatePluginTestTemplate } from '../templates/plugin/plugin.template.js';

export interface GeneratorResult {
  path: string;
  content: string;
}

export async function generatePlugin(pluginName: string): Promise<GeneratorResult[]> {
  const results: GeneratorResult[] = [];
  const pluginsDir = resolve(process.cwd(), 'packages/execution/src/plugins');
  const testsDir = resolve(process.cwd(), 'packages/execution/src/plugins/__tests__');

  // Ensure directories exist
  if (!existsSync(pluginsDir)) {
    await mkdir(pluginsDir, { recursive: true });
  }
  if (!existsSync(testsDir)) {
    await mkdir(testsDir, { recursive: true });
  }

  // Generate plugin file
  const pluginContent = generatePluginTemplate(pluginName);
  const pluginPath = resolve(pluginsDir, `${pluginName}.plugin.ts`);
  await writeFile(pluginPath, pluginContent, 'utf-8');

  results.push({
    path: `execution/plugins/${pluginName}.plugin.ts`,
    content: pluginContent
  });

  // Generate test file
  const testContent = generatePluginTestTemplate(pluginName);
  const testPath = resolve(testsDir, `${pluginName}.plugin.test.ts`);
  await writeFile(testPath, testContent, 'utf-8');

  results.push({
    path: `execution/plugins/__tests__/${pluginName}.plugin.test.ts`,
    content: testContent
  });

  return results;
}
