/**
 * @generated by @flusk/cli — client recipe
 * Pattern Repository — CRUD for detected repetitive prompt patterns.
 * All functions accept a Pool instance as first parameter.
 */

// --- BEGIN GENERATED ---
export { create } from './create.js';
export { findById } from './find-by-id.js';
export { findMany } from './find-many.js';
export { findByOrganization } from './find-by-organization.js';
export { findByPromptHash } from './find-by-prompt-hash.js';
export { updateOccurrence } from './update-occurrence.js';
export type { PatternFilters } from './types.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
