/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { ConversationEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Insert a new Conversation record into SQLite
 */
export function create(
  db: DatabaseSync,
  data: Omit<ConversationEntity, 'id' | 'createdAt' | 'updatedAt'>,
): ConversationEntity {
  const stmt = db.prepare(`
    INSERT INTO conversations (
      external_id, model, provider, turn_count, total_input_tokens,
      total_output_tokens, total_cost, first_call_at, last_call_at, metadata,
      status
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    RETURNING *
  `);

  const row = stmt.get(
    data.externalId ?? null,
    data.model,
    data.provider,
    data.turnCount,
    data.totalInputTokens,
    data.totalOutputTokens,
    data.totalCost,
    data.firstCallAt,
    data.lastCallAt,
    data.metadata != null ? JSON.stringify(data.metadata) : null,
    data.status,
  ) as Record<string, unknown>;

  return rowToEntity(row);
}
// --- END GENERATED ---
