/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';

/**
 * Delete Conversation by id
 */
export function deleteById(
  db: DatabaseSync,
  id: string,
): boolean {
  const stmt = db.prepare('DELETE FROM conversations WHERE id = ?');
  return stmt.run(id).changes > 0;
}
// --- END GENERATED ---
