/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { ConversationEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Find Conversation records within a time range
 */
export function findByTimeRange(
  db: DatabaseSync,
  from: string,
  to: string,
): ConversationEntity[] {
  const stmt = db.prepare(
    'SELECT * FROM conversations WHERE created_at >= ? AND created_at <= ? ORDER BY created_at DESC',
  );
  const rows = stmt.all(from, to) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}
// --- END GENERATED ---
