/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { ConversationEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Find active conversations older than a threshold
 */
export function findAbandoned(
  db: DatabaseSync, before: string,
): ConversationEntity[] {
  const stmt = db.prepare(
    "SELECT * FROM conversations WHERE status = 'active' AND last_call_at < ?",
  );
  const rows = stmt.all(before) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}
// --- END GENERATED ---
