/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { ConversationEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Find conversation by external ID
 */
export function findByExternalId(
  db: DatabaseSync,
  externalId: string,
): ConversationEntity | null {
  const stmt = db.prepare(
    'SELECT * FROM conversations WHERE external_id = ?',
  );
  const row = stmt.get(externalId) as Record<string, unknown> | undefined;
  return row ? rowToEntity(row) : null;
}
// --- END GENERATED ---
