/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { ConversationEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * List Conversations with pagination
 */
export function list(
  db: DatabaseSync,
  limit = 50,
  offset = 0,
): ConversationEntity[] {
  const stmt = db.prepare(
    'SELECT * FROM conversations ORDER BY created_at DESC LIMIT ? OFFSET ?',
  );
  const rows = stmt.all(limit, offset) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}
// --- END GENERATED ---
