/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { ConversationEntity } from '@flusk/entities';
import { toISOString } from '../../../shared/map-row.js';

/** Convert SQLite row to ConversationEntity */
export function rowToEntity(row: Record<string, unknown>): ConversationEntity {
  return {
    id: row.id as string,
    createdAt: toISOString(row.created_at),
    updatedAt: toISOString(row.updated_at),
    externalId: (row.external_id as string) ?? undefined,
    model: row.model as string,
    provider: row.provider as string,
    turnCount: row.turn_count as number,
    totalInputTokens: row.total_input_tokens as number,
    totalOutputTokens: row.total_output_tokens as number,
    totalCost: row.total_cost as number,
    firstCallAt: toISOString(row.first_call_at),
    lastCallAt: toISOString(row.last_call_at),
    metadata: row.metadata != null ? JSON.parse(row.metadata as string) : undefined,
    status: row.status as 'active' | 'completed' | 'abandoned',
  };
}
// --- END GENERATED ---
