/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';

export interface TopByCostRow {
  _: string;
}

/**
 * Top conversations by total cost
 */
export function topByCost(db: DatabaseSync): TopByCostRow[] {
  const stmt = db.prepare(
    'SELECT * FROM conversations ORDER BY total_cost DESC LIMIT 10',
  );
  return stmt.all() as unknown as TopByCostRow[];
}
// --- END GENERATED ---
