/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/text/hash.fn.yaml
 */

/**
 * Create a deterministic hash of a string using Node crypto
 */
export function hash(input: string, algorithm: string): string {
  return (() => {
  const { createHash } = require('node:crypto');
  return createHash(algorithm ?? 'sha256').update(input).digest('hex');
})();
}
