/**
 * @generated by @flusk/cli — cli-command recipe
 * CLI command: flusk alerts-list
 */
import { Command } from 'commander';
import chalk from 'chalk';
import { getDb } from '@flusk/resources';

export const alertsListCommand = new Command('alerts-list')
  .description('List configured alert channels')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const db = getDb();
    const { AlertChannelRepository } = await import('@flusk/resources');
    const channels = AlertChannelRepository.listAlertChannels(db);

    if (channels.length === 0) {
      console.log(chalk.yellow('No alert channels configured. Use alerts-setup to add one.'));
      return;
    }

    if (opts.json) {
      console.log(JSON.stringify(channels, null, 2));
      return;
    }

    console.log(chalk.blue(`\n📋 ${channels.length} alert channel(s):\n`));
    for (const ch of channels) {
      const status = ch.enabled ? chalk.green('●') : chalk.red('○');
      console.log(`  ${status} ${ch.name} (${ch.channelType}) — severity ≥ ${ch.severityFilter}`);
    }
    console.log();
  });
