/**
 * @generated by @flusk/cli — cli-command recipe
 * CLI command: flusk alerts-ack
 */
import { Command } from 'commander';
import chalk from 'chalk';
import { getDb } from '@flusk/resources';

export const alertsAckCommand = new Command('alerts-ack')
  .description('Acknowledge an alert event')
  .requiredOption('--id <id>', 'Alert event ID to acknowledge')
  .action(async (opts) => {
    const db = getDb();
    const { AlertEventRepository } = await import('@flusk/resources');

    const event = AlertEventRepository.findAlertEventById(db, opts.id as string);
    if (!event) {
      console.error(chalk.red(`Alert event "${opts.id}" not found`));
      process.exit(1);
    }

    AlertEventRepository.updateAlertEvent(db, event.id, {
      acknowledgedAt: new Date().toISOString(),
    });

    console.log(chalk.green(`✅ Alert "${event.title}" acknowledged`));
  });
