"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.analyzeCommand = void 0;
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk analyze <script>
 * Spawns user script with OTel instrumentation, captures LLM calls.
 * Local mode (default): direct SQLite export, no HTTP server.
 * Server mode: ephemeral OTLP receiver over HTTP.
 */
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var node_child_process_1 = require("node:child_process");
var node_path_1 = require("node:path");
var node_url_1 = require("node:url");
var promises_1 = require("node:fs/promises");
var node_fs_1 = require("node:fs");
var node_crypto_1 = require("node:crypto");
var resources_1 = require("@flusk/resources");
var analyze_receiver_js_1 = require("./analyze-receiver.js");
var analyze_report_js_1 = require("./analyze-report.js");
var forge_1 = require("@flusk/forge");
var logger_1 = require("@flusk/logger");
var analyze_budget_js_1 = require("./analyze-budget.js");
var log = (0, logger_1.createLogger)({ name: 'analyze' });
exports.analyzeCommand = new commander_1.Command('analyze')
    .description('Analyze LLM costs of a script in real-time')
    .argument('<script>', 'Script to analyze')
    .option('-d, --duration <seconds>', 'Duration in seconds (0 = until exit)', '60')
    .option('-o, --output <file>', 'Write report to file')
    .option('-f, --format <format>', 'Report format (markdown|json)', 'markdown')
    .option('-a, --agent <name>', 'Label for multi-agent tracking')
    .option('-m, --mode <mode>', 'Export mode (local|server)', 'local')
    .option('--redact', 'Redact prompt/completion text from storage (security)')
    .action(function (script, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var duration, config, mode, agentLabel, storage, session, redact, authToken, receiver, _a, scriptPath, child, exitCode, calls, totalCost, models, totalCalls, report;
    var _b;
    return __generator(this, function (_c) {
        switch (_c.label) {
            case 0:
                duration = parseInt(opts.duration, 10);
                return [4 /*yield*/, (0, forge_1.loadConfig)()];
            case 1:
                config = _c.sent();
                mode = opts.mode;
                agentLabel = opts.agent || config.agent || process.env.FLUSK_AGENT;
                storage = (0, resources_1.createSqliteStorage)((_b = config.storage) === null || _b === void 0 ? void 0 : _b.path);
                session = storage.analyzeSessions.create({
                    script: script,
                    durationMs: duration * 1000, totalCalls: 0,
                    totalCost: 0, modelsUsed: [], startedAt: new Date().toISOString(),
                });
                redact = !!opts.redact;
                authToken = (0, node_crypto_1.randomBytes)(16).toString('hex');
                if (!(mode === 'server')) return [3 /*break*/, 3];
                return [4 /*yield*/, (0, analyze_receiver_js_1.startReceiver)(storage, session.id, redact, authToken)];
            case 2:
                _a = _c.sent();
                return [3 /*break*/, 4];
            case 3:
                _a = null;
                _c.label = 4;
            case 4:
                receiver = _a;
                scriptPath = (0, node_path_1.resolve)((0, node_path_1.normalize)(script));
                if (!(0, node_fs_1.existsSync)(scriptPath)) {
                    console.error(chalk_1.default.red("\u274C Script not found: ".concat(scriptPath)));
                    console.error(chalk_1.default.dim('Please provide a valid path to the script to analyze.'));
                    process.exit(1);
                }
                console.log(chalk_1.default.cyan("\uD83D\uDD0D Analyzing ".concat(script, "...")));
                if (receiver)
                    console.log(chalk_1.default.dim("   OTLP receiver on port ".concat(receiver.port)));
                else
                    console.log(chalk_1.default.dim('   Local mode — direct SQLite export'));
                if (duration > 0)
                    console.log(chalk_1.default.dim("   Duration: ".concat(duration, "s")));
                if (redact)
                    console.log(chalk_1.default.dim('   Redact mode — prompts/completions will not be stored'));
                child = spawnChild(script, mode, receiver === null || receiver === void 0 ? void 0 : receiver.port, agentLabel, session.id, redact, receiver ? authToken : undefined);
                return [4 /*yield*/, waitForCompletion(child, duration)];
            case 5:
                exitCode = _c.sent();
                if (!receiver) return [3 /*break*/, 7];
                return [4 /*yield*/, receiver.close()];
            case 6:
                _c.sent();
                _c.label = 7;
            case 7:
                calls = storage.llmCalls.listBySessionId(session.id, 10000, 0);
                totalCost = storage.llmCalls.sumCostBySessionId(session.id);
                models = storage.llmCalls.countByModelBySessionId(session.id).map(function (m) { return m.model; });
                totalCalls = calls.length;
                storage.analyzeSessions.update(session.id, {
                    completedAt: new Date().toISOString(),
                    totalCalls: totalCalls,
                    totalCost: totalCost,
                    modelsUsed: models,
                });
                report = (0, analyze_report_js_1.generateReport)({ session: __assign(__assign({}, session), { totalCalls: totalCalls, totalCost: totalCost, modelsUsed: models }), calls: calls }, { format: opts.format, color: !opts.output });
                if (!opts.output) return [3 /*break*/, 9];
                return [4 /*yield*/, (0, promises_1.writeFile)((0, node_path_1.resolve)(opts.output), report, 'utf-8')];
            case 8:
                _c.sent();
                console.log(chalk_1.default.green("\n\u2705 Report written to ".concat(opts.output)));
                return [3 /*break*/, 10];
            case 9:
                console.log('\n' + report);
                _c.label = 10;
            case 10:
                (0, analyze_budget_js_1.runBudgetCheck)(config, storage, calls);
                log.info({ exitCode: exitCode, calls: totalCalls }, 'Analysis complete');
                return [2 /*return*/];
        }
    });
}); });
function getOtelRegisterUrl() {
    // Find the otel register.ts by walking up to find the monorepo root
    // (identified by packages/otel/src/register.ts existing).
    // This works from both src/ and dist/ layouts.
    var startDir = (function () {
        try {
            return (0, node_url_1.fileURLToPath)(new URL('.', import.meta.url));
        }
        catch (_a) {
            return process.cwd();
        }
    })();
    var dir = startDir;
    for (var i = 0; i < 10; i++) {
        var candidate = (0, node_path_1.resolve)(dir, 'packages', 'otel', 'src', 'register.ts');
        if ((0, node_fs_1.existsSync)(candidate))
            return candidate;
        var parent_1 = (0, node_path_1.resolve)(dir, '..');
        if (parent_1 === dir)
            break;
        dir = parent_1;
    }
    // Final fallback: assume cwd is monorepo root
    return (0, node_path_1.resolve)(process.cwd(), 'packages', 'otel', 'src', 'register.ts');
}
function spawnChild(script, mode, port, agent, sessionId, redact, authToken) {
    var _a, _b, _c, _d;
    // Resolve the otel register path relative to this file
    var otelRegister = getOtelRegisterUrl().replace('file://', '');
    var env = __assign(__assign(__assign(__assign(__assign(__assign(__assign({}, process.env), { FLUSK_MODE: mode, FLUSK_SQLITE_PATH: (0, node_path_1.resolve)((_a = process.env.HOME) !== null && _a !== void 0 ? _a : '~', '.flusk', 'data.db') }), (port ? { FLUSK_ENDPOINT: "http://127.0.0.1:".concat(port) } : {})), (agent ? { FLUSK_AGENT: agent, FLUSK_AGENT_LABEL: agent } : {})), (sessionId ? { FLUSK_SESSION_ID: sessionId } : {})), (redact ? { FLUSK_REDACT: '1' } : {})), (authToken ? { FLUSK_AUTH_TOKEN: authToken } : {}));
    // Validate and sanitize the user-provided script path to prevent path traversal
    var scriptPath = (0, node_path_1.resolve)((0, node_path_1.normalize)(script));
    var cwd = process.cwd();
    if (!scriptPath.startsWith(cwd) && !scriptPath.startsWith((0, node_path_1.resolve)((_b = process.env.HOME) !== null && _b !== void 0 ? _b : '~'))) {
        throw new Error("Script path \"".concat(script, "\" resolves outside the working directory and home directory. ") +
            "Resolved: \"".concat(scriptPath, "\". This may be a path traversal attempt."));
    }
    if (!(0, node_fs_1.existsSync)(scriptPath)) {
        throw new Error("Script not found: ".concat(scriptPath));
    }
    // Sanitize paths for safe interpolation into generated JS (prevent injection)
    var safeScriptPath = scriptPath.replace(/\\/g, '/').replace(/'/g, "\\'");
    var safeOtelRegister = otelRegister.replace(/\\/g, '/').replace(/'/g, "\\'");
    // Create a thin wrapper that loads OTel THEN the user script.
    // Using tsx as runtime ensures TypeScript support and proper module resolution.
    // We avoid node --import because getNodeAutoInstrumentations deadlocks in loader context.
    var wrapperPath = (0, node_path_1.resolve)((_c = process.env.HOME) !== null && _c !== void 0 ? _c : '~', '.flusk', '_analyze-wrapper.mjs');
    (0, node_fs_1.mkdirSync)((0, node_path_1.resolve)((_d = process.env.HOME) !== null && _d !== void 0 ? _d : '~', '.flusk'), { recursive: true });
    (0, node_fs_1.writeFileSync)(wrapperPath, [
        "const { sdk, ready } = await import('".concat(safeOtelRegister, "');"),
        "// Wait for async OpenAI monkey-patches to be applied before loading user script",
        "if (ready) await ready;",
        "await import('".concat(safeScriptPath, "');"),
        "// Flush OTel BatchSpanProcessor \u2014 shutdown() calls forceFlush() internally",
        "if (sdk) { await sdk.shutdown(); }",
    ].join('\n'));
    // Run from otel package dir so pnpm workspace deps (@opentelemetry/*) resolve correctly
    var otelPkgDir = (0, node_path_1.resolve)(otelRegister, '..', '..');
    return (0, node_child_process_1.spawn)('npx', ['tsx', wrapperPath], {
        stdio: 'inherit',
        env: env,
        cwd: otelPkgDir,
    });
}
function waitForCompletion(child, duration) {
    return new Promise(function (resolve) {
        var timer;
        var sigintHandler = function () { child.kill('SIGTERM'); };
        var cleanup = function (code) {
            if (timer)
                clearTimeout(timer);
            process.removeListener('SIGINT', sigintHandler);
            resolve(code);
        };
        child.on('exit', function (code) { return cleanup(code !== null && code !== void 0 ? code : 1); });
        child.on('error', function () { return cleanup(1); });
        if (duration > 0)
            timer = setTimeout(function () { child.kill('SIGTERM'); }, duration * 1000);
        process.on('SIGINT', sigintHandler);
    });
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
