"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.budgetCommand = void 0;
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk budget — show budget status with progress bars
 */
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var resources_1 = require("@flusk/resources");
var business_logic_1 = require("@flusk/business-logic");
var forge_1 = require("@flusk/forge");
var logger_1 = require("@flusk/logger");
var log = (0, logger_1.createLogger)({ name: 'budget' });
exports.budgetCommand = new commander_1.Command('budget')
    .description('Show budget status and alerts')
    .action(function () { return __awaiter(void 0, void 0, void 0, function () {
    var config, storage, now, dayStart, monthStart, dailyCost, monthlyCost, totalCalls, duplicateCalls, status, _i, _a, alert_1;
    var _b;
    return __generator(this, function (_c) {
        switch (_c.label) {
            case 0: return [4 /*yield*/, (0, forge_1.loadConfig)()];
            case 1:
                config = _c.sent();
                storage = (0, resources_1.createSqliteStorage)((_b = config.storage) === null || _b === void 0 ? void 0 : _b.path);
                now = new Date();
                dayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();
                monthStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
                dailyCost = storage.llmCalls.sumCostSince(dayStart);
                monthlyCost = storage.llmCalls.sumCostSince(monthStart);
                totalCalls = storage.llmCalls.list(100000, 0).length;
                duplicateCalls = storage.llmCalls.countDuplicates();
                status = business_logic_1.budget.checkBudget(config.budget, {
                    dailyCost: dailyCost,
                    monthlyCost: monthlyCost,
                    totalCalls: totalCalls,
                    duplicateCalls: duplicateCalls,
                });
                console.log(chalk_1.default.bold.cyan('\n📊 Budget Status\n'));
                printBar('Daily', status.daily);
                printBar('Monthly', status.monthly);
                if (status.alerts.length > 0) {
                    console.log(chalk_1.default.yellow('\n⚠️  Alerts:'));
                    for (_i = 0, _a = status.alerts; _i < _a.length; _i++) {
                        alert_1 = _a[_i];
                        console.log(chalk_1.default.yellow("  - ".concat(alert_1)));
                    }
                }
                else {
                    console.log(chalk_1.default.green('\n✅ All budgets within limits'));
                }
                console.log('');
                log.info('Budget check complete');
                return [2 /*return*/];
        }
    });
}); });
function printBar(label, period) {
    if (period.limit === Infinity) {
        console.log(chalk_1.default.dim("".concat(label.padEnd(8), " No limit configured")));
        return;
    }
    var width = 10;
    var filled = Math.round((period.percentage / 100) * width);
    var empty = width - filled;
    var bar = '█'.repeat(filled) + '░'.repeat(empty);
    var color = period.percentage >= 100 ? chalk_1.default.red
        : period.percentage >= 80 ? chalk_1.default.yellow
            : chalk_1.default.green;
    var pct = "".concat(period.percentage.toFixed(0), "%");
    console.log("".concat(label.padEnd(8), " ").concat(color(bar), " $").concat(period.used.toFixed(2), " / $").concat(period.limit.toFixed(2), " (").concat(pct, ")"));
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
