/**
 * @generated by @flusk/cli
 * CLI command: flusk conversations-show
 */
import { Command } from 'commander';
import chalk from 'chalk';
import { createSqliteStorage } from '@flusk/resources';

export const conversationsShowCommand = new Command('conversations-show')
  .description('Show conversation detail with all calls')
  .argument('<id>', 'Conversation ID')
  .action((id: string) => {
    const storage = createSqliteStorage();
    const convo = storage.conversations.findById(id);

    if (!convo) {
      console.log(chalk.red(`Conversation ${id} not found.`));
      return;
    }

    console.log(chalk.bold('Conversation: ') + convo.id);
    console.log(chalk.dim('─'.repeat(60)));
    console.log(`  Provider:       ${convo.provider}`);
    console.log(`  Model:          ${convo.model}`);
    console.log(`  Status:         ${convo.status}`);
    console.log(`  Turns:          ${convo.turnCount}`);
    console.log(`  Input tokens:   ${convo.totalInputTokens}`);
    console.log(`  Output tokens:  ${convo.totalOutputTokens}`);
    console.log(`  Total cost:     $${convo.totalCost.toFixed(4)}`);
    console.log(`  First call:     ${convo.firstCallAt}`);
    console.log(`  Last call:      ${convo.lastCallAt}`);

    if (convo.externalId) {
      console.log(`  External ID:    ${convo.externalId}`);
    }

    const calls = storage.llmCalls.listByConversationId(id);
    if (calls.length > 0) {
      console.log(chalk.bold('\nLLM Calls:'));
      for (const call of calls) {
        const tokens = call.tokens as Record<string, number>;
        console.log(`  ${call.model} — $${call.cost.toFixed(4)} — ${tokens.total ?? 0} tokens`);
      }
    }
  });
