/**
 * @generated by @flusk/cli
 */
import { test, describe } from 'node:test';
import assert from 'node:assert';
import { conversationsTopCommand } from './conversations-top.js';

describe('conversations-top command', () => {
  test('exports a Command instance', () => {
    assert.strictEqual(conversationsTopCommand.name(), 'conversations-top');
  });
});
