// --- BEGIN GENERATED ---
/**
 * CLI command: flusk explain
 * Explain LLM cost insights and optimization opportunities
 * @generated by @flusk/forge — command generator
 */
import { Command } from 'commander';
import type { ExplainOptions } from './explain.options.js';

export const explainCommand = new Command('explain')
  .description('Explain LLM cost insights and optimization opportunities')
  .option('--provider <provider>', 'LLM provider to analyze', 'openai')
  .option('--model <model>', 'Specific model to filter by')
  .option('--db <db>', 'Path to the Flusk SQLite database', './flusk.db')
  .option('--format <format>', 'Output format', 'text')
  .option('--max-insights <maxInsights>', 'Maximum number of insights to return', '10')
  .option('--min-severity <minSeverity>', 'Minimum severity threshold for insights', 'low')
  .option('--session <session>', 'Filter by session ID')
  .option('--cost-threshold <costThreshold>', 'Cost threshold for alerts')
  .option('--no-code', 'Exclude code snippets from output')
  .action(async (opts: ExplainOptions) => {
    const { handleExplain } = await import('./explain.handler.js');
    await handleExplain(opts);
  });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
