"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.exportCommand = void 0;
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk export
 * Configure and test observability platform exports
 */
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var node_path_1 = require("node:path");
var node_fs_1 = require("node:fs");
var VALID_PLATFORMS = ['grafana', 'datadog', 'newrelic'];
function getConfigPath() {
    var _a;
    return (0, node_path_1.resolve)((_a = process.env.HOME) !== null && _a !== void 0 ? _a : '~', '.flusk', 'config.json');
}
function loadExportConfig() {
    var p = getConfigPath();
    if ((0, node_fs_1.existsSync)(p)) {
        try {
            return JSON.parse((0, node_fs_1.readFileSync)(p, 'utf-8'));
        }
        catch ( /* ignore */_a) { /* ignore */ }
    }
    return {};
}
function saveExportConfig(config) {
    var p = getConfigPath();
    (0, node_fs_1.mkdirSync)((0, node_path_1.resolve)(p, '..'), { recursive: true });
    (0, node_fs_1.writeFileSync)(p, JSON.stringify(config, null, 2), 'utf-8');
}
var setupCommand = new commander_1.Command('setup')
    .description('Interactive setup for export targets')
    .argument('<platform>', 'Platform: grafana | datadog | newrelic')
    .option('--endpoint <url>', 'Custom OTLP endpoint')
    .option('--api-key <key>', 'API key')
    .action(function (platform, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var config, exports;
    var _a;
    return __generator(this, function (_b) {
        if (!VALID_PLATFORMS.includes(platform)) {
            console.error(chalk_1.default.red("Unknown platform: ".concat(platform, ". Use: ").concat(VALID_PLATFORMS.join(', '))));
            process.exit(1);
        }
        config = loadExportConfig();
        exports = (_a = config.exports) !== null && _a !== void 0 ? _a : {};
        exports[platform] = {
            endpoint: opts.endpoint || null,
            apiKey: opts.apiKey || null,
            configuredAt: new Date().toISOString(),
        };
        config.exports = exports;
        saveExportConfig(config);
        console.log(chalk_1.default.green("\u2705 ".concat(platform, " export configured and saved to ").concat(getConfigPath())));
        console.log(chalk_1.default.dim("Endpoint: ".concat(opts.endpoint || 'default')));
        console.log(chalk_1.default.dim("API Key: ".concat(opts.apiKey ? '***' + opts.apiKey.slice(-4) : 'not set')));
        return [2 /*return*/];
    });
}); });
var testCommand = new commander_1.Command('test')
    .description('Send a test span to configured export targets')
    .argument('<platform>', 'Platform to test')
    .option('--api-key <key>', 'API key')
    .option('--endpoint <url>', 'Custom endpoint')
    .action(function (platform, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var config, platformConfig, endpoint, apiKey, testPayload, headers, res, err_1;
    var _a;
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                config = loadExportConfig();
                platformConfig = (_a = config.exports) === null || _a === void 0 ? void 0 : _a[platform];
                endpoint = opts.endpoint || (platformConfig === null || platformConfig === void 0 ? void 0 : platformConfig.endpoint);
                apiKey = opts.apiKey || (platformConfig === null || platformConfig === void 0 ? void 0 : platformConfig.apiKey);
                if (!endpoint) {
                    console.error(chalk_1.default.red("No endpoint configured for ".concat(platform, ". Run: flusk export setup ").concat(platform, " --endpoint <url>")));
                    process.exit(1);
                }
                console.log(chalk_1.default.dim("Sending test span to ".concat(platform, " at ").concat(endpoint, "...")));
                testPayload = {
                    resourceSpans: [{
                            resource: { attributes: [{ key: 'service.name', value: { stringValue: 'flusk-test' } }] },
                            scopeSpans: [{
                                    scope: { name: 'flusk-export-test' },
                                    spans: [{
                                            traceId: Array.from({ length: 32 }, function () { return Math.floor(Math.random() * 16).toString(16); }).join(''),
                                            spanId: Array.from({ length: 16 }, function () { return Math.floor(Math.random() * 16).toString(16); }).join(''),
                                            name: 'flusk.export.test',
                                            kind: 1,
                                            startTimeUnixNano: String(Date.now() * 1000000),
                                            endTimeUnixNano: String((Date.now() + 100) * 1000000),
                                            attributes: [
                                                { key: 'flusk.test', value: { boolValue: true } },
                                            ],
                                        }],
                                }],
                        }],
                };
                _b.label = 1;
            case 1:
                _b.trys.push([1, 3, , 4]);
                headers = { 'Content-Type': 'application/json' };
                if (apiKey)
                    headers['Authorization'] = "Bearer ".concat(apiKey);
                return [4 /*yield*/, fetch(endpoint + '/v1/traces', {
                        method: 'POST',
                        headers: headers,
                        body: JSON.stringify(testPayload),
                    })];
            case 2:
                res = _b.sent();
                if (res.ok) {
                    console.log(chalk_1.default.green("\u2705 Test span sent to ".concat(platform, " (HTTP ").concat(res.status, ")")));
                    console.log(chalk_1.default.dim('Check your platform dashboard for the test trace.'));
                }
                else {
                    console.error(chalk_1.default.red("\u274C Failed to send test span: HTTP ".concat(res.status, " ").concat(res.statusText)));
                }
                return [3 /*break*/, 4];
            case 3:
                err_1 = _b.sent();
                console.error(chalk_1.default.red("\u274C Failed to send test span: ".concat(err_1 === null || err_1 === void 0 ? void 0 : err_1.message)));
                return [3 /*break*/, 4];
            case 4: return [2 /*return*/];
        }
    });
}); });
var listCommand = new commander_1.Command('list')
    .description('Show configured export targets')
    .action(function () {
    var _a;
    var targets = ((_a = process.env['FLUSK_EXPORT']) === null || _a === void 0 ? void 0 : _a.split(',').filter(Boolean)) || [];
    if (targets.length === 0) {
        console.log(chalk_1.default.dim('No export targets configured.'));
        console.log(chalk_1.default.dim('Run: flusk export setup <grafana|datadog|newrelic>'));
        return;
    }
    console.log(chalk_1.default.bold('Configured export targets:'));
    for (var _i = 0, targets_1 = targets; _i < targets_1.length; _i++) {
        var t = targets_1[_i];
        var key = process.env["FLUSK_".concat(t.toUpperCase(), "_API_KEY")];
        var endpoint = process.env["FLUSK_".concat(t.toUpperCase(), "_ENDPOINT")];
        var status_1 = key ? chalk_1.default.green('(key set)') : chalk_1.default.yellow('(no key)');
        console.log("  \u2022 ".concat(chalk_1.default.cyan(t), " \u2192 ").concat(endpoint || 'default', " ").concat(status_1));
    }
});
exports.exportCommand = new commander_1.Command('export')
    .description('Configure observability platform integrations')
    .addCommand(setupCommand)
    .addCommand(testCommand)
    .addCommand(listCommand);
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
