/**
 * @generated by @flusk/cli — cli-command recipe
 * CLI command: flusk g:function <yaml-path>
 */

// --- BEGIN GENERATED ---
import { Command } from 'commander';
import { resolve } from 'node:path';
import chalk from 'chalk';
import {
  generateFunction,
  loadFnSchema,
  updateNamespaceBarrel,
  updatePrimitivesBarrel,
  generatePyFunction,
  updatePyNamespaceInit,
  updatePyPrimitivesInit,
} from '@flusk/forge';

export const generateFunctionCommand = new Command('g:function')
  .description('Generate a pure function (TypeScript + Python) from a .fn.yaml file')
  .argument('<yaml-path>', 'Path to the .fn.yaml file')
  .option('--ts-only', 'Generate TypeScript only (skip Python)')
  .option('--dry-run', 'Preview files without writing')
  .action(async (yamlPath: string, options) => {
    const projectRoot = process.cwd();
    const absYamlPath = resolve(projectRoot, yamlPath);

    console.log(chalk.blue(`\n⚙️  Generating function from: ${yamlPath}\n`));

    try {
      const schema = await loadFnSchema(absYamlPath);
      const allFiles: Array<{ path: string; action: string }> = [];

      // TypeScript
      const tsResult = await generateFunction(absYamlPath, projectRoot);
      allFiles.push(...tsResult.files);

      const nsBarrel = await updateNamespaceBarrel(schema.namespace, projectRoot);
      const primBarrel = await updatePrimitivesBarrel([schema.namespace], projectRoot);
      allFiles.push(nsBarrel, primBarrel);

      // Python
      if (!options.tsOnly) {
        const pyFiles = await generatePyFunction(schema, projectRoot);
        allFiles.push(...pyFiles);
        const pyNsInit = await updatePyNamespaceInit(schema.namespace, projectRoot);
        const pyPrimInit = await updatePyPrimitivesInit([schema.namespace], projectRoot);
        allFiles.push(pyNsInit, pyPrimInit);
      }

      for (const f of allFiles) {
        const icon = f.action === 'created' ? '✅' : '📝';
        console.log(chalk.green(`  ${icon} [${f.action}] ${f.path}`));
      }
      console.log(chalk.green(`\n✨ Function "${schema.name}" generated!\n`));
    } catch (error) {
      console.error(chalk.red(`\n❌ Failed: ${error}`));
      process.exit(1);
    }
  });
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
