"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateCommand = void 0;
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
var commander_1 = require("commander");
var node_path_1 = require("node:path");
var node_fs_1 = require("node:fs");
var chalk_1 = require("chalk");
var forge_1 = require("@flusk/forge");
exports.generateCommand = new commander_1.Command('g')
    .aliases(['generate'])
    .description('Generate code from entity schemas')
    .argument('[entity-file]', 'Entity file to generate from (e.g., llm-call.entity.ts)')
    .option('--types-only', 'Generate only types package')
    .option('--all', 'Generate from all entities')
    .action(function (entityFile, options) { return __awaiter(void 0, void 0, void 0, function () {
    var entitiesDir, entityFiles, allFiles, fileName, _i, entityFiles_1, file, entityPath, entityName, typesResult, resourceResults, _a, resourceResults_1, result, logicResults, _b, logicResults_1, result, executionResults, _c, executionResults_1, result, error_1;
    return __generator(this, function (_d) {
        switch (_d.label) {
            case 0:
                entitiesDir = (0, node_path_1.resolve)(process.cwd(), 'packages/entities/src');
                if (!(0, node_fs_1.existsSync)(entitiesDir)) {
                    console.error(chalk_1.default.red('Error: packages/entities/src directory not found'));
                    console.error(chalk_1.default.yellow('Run this command from the project root'));
                    process.exit(1);
                }
                entityFiles = [];
                if (options.all) {
                    allFiles = (0, node_fs_1.readdirSync)(entitiesDir)
                        .filter(function (f) { return f.endsWith('.entity.ts') && f !== 'base.entity.ts'; });
                    entityFiles.push.apply(entityFiles, allFiles);
                }
                else if (entityFile) {
                    fileName = entityFile.endsWith('.entity.ts') ? entityFile : "".concat(entityFile, ".entity.ts");
                    if (!(0, node_fs_1.existsSync)((0, node_path_1.resolve)(entitiesDir, fileName))) {
                        console.error(chalk_1.default.red("Error: Entity file not found: ".concat(fileName)));
                        process.exit(1);
                    }
                    entityFiles.push(fileName);
                }
                else {
                    console.error(chalk_1.default.red('Error: Provide an entity file or use --all'));
                    console.error(chalk_1.default.yellow('Example: flusk g llm-call.entity.ts'));
                    process.exit(1);
                }
                console.log(chalk_1.default.blue("\n\uD83D\uDD27 Generating code from ".concat(entityFiles.length, " entity file(s)...\n")));
                _i = 0, entityFiles_1 = entityFiles;
                _d.label = 1;
            case 1:
                if (!(_i < entityFiles_1.length)) return [3 /*break*/, 9];
                file = entityFiles_1[_i];
                entityPath = (0, node_path_1.resolve)(entitiesDir, file);
                entityName = (0, node_path_1.basename)(file, '.entity.ts');
                console.log(chalk_1.default.cyan("\n\uD83D\uDCE6 Processing: ".concat(file)));
                _d.label = 2;
            case 2:
                _d.trys.push([2, 7, , 8]);
                return [4 /*yield*/, (0, forge_1.generateTypes)(entityPath, entityName)];
            case 3:
                typesResult = _d.sent();
                console.log(chalk_1.default.green("  \u2705 ".concat(typesResult.path)));
                if (options.typesOnly) {
                    return [3 /*break*/, 8];
                }
                return [4 /*yield*/, (0, forge_1.generateResources)(entityPath, entityName)];
            case 4:
                resourceResults = _d.sent();
                for (_a = 0, resourceResults_1 = resourceResults; _a < resourceResults_1.length; _a++) {
                    result = resourceResults_1[_a];
                    console.log(chalk_1.default.green("  \u2705 ".concat(result.path)));
                }
                return [4 /*yield*/, (0, forge_1.generateBusinessLogic)(entityPath, entityName)];
            case 5:
                logicResults = _d.sent();
                for (_b = 0, logicResults_1 = logicResults; _b < logicResults_1.length; _b++) {
                    result = logicResults_1[_b];
                    console.log(chalk_1.default.green("  \u2705 ".concat(result.path)));
                }
                return [4 /*yield*/, (0, forge_1.generateExecution)(entityPath, entityName)];
            case 6:
                executionResults = _d.sent();
                for (_c = 0, executionResults_1 = executionResults; _c < executionResults_1.length; _c++) {
                    result = executionResults_1[_c];
                    console.log(chalk_1.default.green("  \u2705 ".concat(result.path)));
                }
                return [3 /*break*/, 8];
            case 7:
                error_1 = _d.sent();
                console.error(chalk_1.default.red("  \u274C Failed to generate from ".concat(file, ":")), error_1);
                process.exit(1);
                return [3 /*break*/, 8];
            case 8:
                _i++;
                return [3 /*break*/, 1];
            case 9:
                console.log(chalk_1.default.green('\n✨ Code generation complete!\n'));
                return [2 /*return*/];
        }
    });
}); });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
