"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.validateProjectName = validateProjectName;
exports.generatePackageJson = generatePackageJson;
exports.initGitRepo = initGitRepo;
exports.installDependencies = installDependencies;
exports.printSuccessMessage = printSuccessMessage;
/**
 * @generated by @flusk/cli — command recipe
 * Helper functions for init command
 */
// --- BEGIN GENERATED ---
var chalk_1 = require("chalk");
var node_child_process_1 = require("node:child_process");
var node_util_1 = require("node:util");
var node_path_1 = require("node:path");
var promises_1 = require("node:fs/promises");
var execAsync = (0, node_util_1.promisify)(node_child_process_1.exec);
/**
 * Validate project name format
 */
function validateProjectName(projectName) {
    if (!projectName) {
        console.error(chalk_1.default.red('Error: Project name is required'));
        console.error(chalk_1.default.yellow('Example: flusk init my-api-project'));
        process.exit(1);
    }
    var validNameRegex = /^[a-z0-9-_]+$/i;
    if (!validNameRegex.test(projectName)) {
        console.error(chalk_1.default.red('Error: Invalid project name'));
        console.error(chalk_1.default.yellow('Project name must contain only letters, numbers, hyphens, and underscores'));
        console.error(chalk_1.default.yellow('Example: flusk init my-api-project'));
        process.exit(1);
    }
    return projectName;
}
/**
 * Generate package.json for new project
 */
function generatePackageJson(targetDir, projectName) {
    return __awaiter(this, void 0, void 0, function () {
        var packageJson;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    packageJson = {
                        name: projectName,
                        version: '0.1.0',
                        type: 'module',
                        private: true,
                        scripts: {
                            dev: 'platformatic watt',
                            build: 'pnpm -r build',
                            start: 'NODE_ENV=production platformatic watt',
                            'db:migrate': 'flusk migrate',
                            'infra:up': 'docker compose up -d',
                            'infra:down': 'docker compose down',
                            'infra:logs': 'docker compose logs -f'
                        },
                        workspaces: ['packages/*'],
                        devDependencies: {
                            '@types/node': '^22.10.5',
                            'typescript': '^5.7.0',
                            '@flusk/cli': 'workspace:*'
                        },
                        dependencies: {
                            '@platformatic/watt': '^3.37.0',
                            'fastify': '^5.0.0',
                            '@fastify/cors': '^10.0.0',
                            'pg': '^8.13.1'
                        }
                    };
                    return [4 /*yield*/, (0, promises_1.writeFile)((0, node_path_1.resolve)(targetDir, 'package.json'), JSON.stringify(packageJson, null, 2), 'utf-8')];
                case 1:
                    _a.sent();
                    console.log(chalk_1.default.green('✅ Generated package.json'));
                    return [2 /*return*/];
            }
        });
    });
}
/**
 * Initialize git repository
 */
function initGitRepo(targetDir, skip) {
    return __awaiter(this, void 0, void 0, function () {
        var _error_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    if (skip) {
                        console.log(chalk_1.default.gray('⏭️  Skipped git initialization'));
                        return [2 /*return*/];
                    }
                    _a.label = 1;
                case 1:
                    _a.trys.push([1, 4, , 5]);
                    return [4 /*yield*/, execAsync('git --version')];
                case 2:
                    _a.sent();
                    return [4 /*yield*/, execAsync('git init', { cwd: targetDir })];
                case 3:
                    _a.sent();
                    console.log(chalk_1.default.green('✅ Initialized git repository'));
                    return [3 /*break*/, 5];
                case 4:
                    _error_1 = _a.sent();
                    console.log(chalk_1.default.yellow('⚠️  Git not found, skipping git initialization'));
                    return [3 /*break*/, 5];
                case 5: return [2 /*return*/];
            }
        });
    });
}
/**
 * Install dependencies with pnpm
 */
function installDependencies(targetDir, skip) {
    return __awaiter(this, void 0, void 0, function () {
        var error_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    if (skip) {
                        console.log(chalk_1.default.gray('⏭️  Skipped dependency installation'));
                        return [2 /*return*/];
                    }
                    _a.label = 1;
                case 1:
                    _a.trys.push([1, 4, , 5]);
                    return [4 /*yield*/, execAsync('pnpm --version')];
                case 2:
                    _a.sent();
                    console.log(chalk_1.default.cyan('\n📦 Installing dependencies (this may take a minute)...'));
                    return [4 /*yield*/, execAsync('pnpm install', { cwd: targetDir })];
                case 3:
                    _a.sent();
                    console.log(chalk_1.default.green('✅ Installed dependencies'));
                    return [3 /*break*/, 5];
                case 4:
                    error_1 = _a.sent();
                    if (error_1.code === 'ENOENT') {
                        console.log(chalk_1.default.yellow('⚠️  pnpm not found, skipping dependency installation'));
                        console.log(chalk_1.default.yellow('   Install pnpm globally: npm install -g pnpm'));
                    }
                    else {
                        console.log(chalk_1.default.yellow('⚠️  Failed to install dependencies'));
                        console.log(chalk_1.default.gray("   ".concat(error_1.message)));
                    }
                    return [3 /*break*/, 5];
                case 5: return [2 /*return*/];
            }
        });
    });
}
/**
 * Print post-init success message
 */
function printSuccessMessage(projectName) {
    console.log(chalk_1.default.green('\n✨ Project initialized successfully!\n'));
    console.log(chalk_1.default.cyan('📋 Next steps:\n'));
    console.log(chalk_1.default.white("  1. ".concat(chalk_1.default.bold("cd ".concat(projectName)))));
    console.log(chalk_1.default.white("  2. ".concat(chalk_1.default.bold('cp .env.example .env'), " ").concat(chalk_1.default.gray('(and update with your values)'))));
    console.log(chalk_1.default.white("  3. ".concat(chalk_1.default.bold('pnpm infra:up'), " ").concat(chalk_1.default.gray('(start PostgreSQL and Redis)'))));
    console.log(chalk_1.default.white("  4. ".concat(chalk_1.default.bold('pnpm dev'), " ").concat(chalk_1.default.gray('(start development server)'))));
    console.log(chalk_1.default.white('\n💡 Useful commands:\n'));
    console.log(chalk_1.default.gray('  pnpm db:migrate        Run database migrations'));
    console.log(chalk_1.default.gray('  pnpm infra:logs        View infrastructure logs'));
    console.log(chalk_1.default.gray('  flusk g <entity>       Generate code from entity'));
    console.log();
}
// --- END GENERATED ---
