"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.initConfigCommand = void 0;
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk init-config — create .flusk.config.js interactively
 */
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var node_readline_1 = require("node:readline");
var promises_1 = require("node:fs/promises");
var node_path_1 = require("node:path");
var node_fs_1 = require("node:fs");
var logger_1 = require("@flusk/logger");
var log = (0, logger_1.createLogger)({ name: 'init-config' });
exports.initConfigCommand = new commander_1.Command('init-config')
    .description('Create a .flusk.config.js file interactively')
    .action(function () { return __awaiter(void 0, void 0, void 0, function () {
    var configPath, rl, ask, daily, monthly, agent, webhook, content;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0:
                configPath = (0, node_path_1.resolve)(process.cwd(), '.flusk.config.js');
                if ((0, node_fs_1.existsSync)(configPath)) {
                    console.log(chalk_1.default.yellow('⚠️  .flusk.config.js already exists'));
                    return [2 /*return*/];
                }
                rl = (0, node_readline_1.createInterface)({ input: process.stdin, output: process.stdout });
                ask = function (q) {
                    return new Promise(function (r) { return rl.question(q, function (a) { return r(a.trim()); }); });
                };
                console.log(chalk_1.default.cyan('\n🔧 Flusk Configuration Wizard\n'));
                return [4 /*yield*/, ask('Daily budget limit ($, leave empty to skip): ')];
            case 1:
                daily = _a.sent();
                return [4 /*yield*/, ask('Monthly budget limit ($, leave empty to skip): ')];
            case 2:
                monthly = _a.sent();
                return [4 /*yield*/, ask('Default agent name (leave empty to skip): ')];
            case 3:
                agent = _a.sent();
                return [4 /*yield*/, ask('Webhook URL for alerts (leave empty to skip): ')];
            case 4:
                webhook = _a.sent();
                rl.close();
                content = generateConfigFile({ daily: daily, monthly: monthly, agent: agent, webhook: webhook });
                return [4 /*yield*/, (0, promises_1.writeFile)(configPath, content, 'utf-8')];
            case 5:
                _a.sent();
                console.log(chalk_1.default.green("\n\u2705 Created ".concat(configPath)));
                log.info('Config file created');
                return [2 /*return*/];
        }
    });
}); });
function generateConfigFile(input) {
    var lines = ['/** @type {import("@flusk/cli").FluskConfig} */', 'export default {'];
    var budgetEntries = [];
    if (input.daily)
        budgetEntries.push("    daily: ".concat(parseFloat(input.daily), ","));
    if (input.monthly)
        budgetEntries.push("    monthly: ".concat(parseFloat(input.monthly), ","));
    if (budgetEntries.length > 0) {
        lines.push.apply(lines, __spreadArray(__spreadArray(['  budget: {'], budgetEntries, false), ['  },'], false));
    }
    if (input.agent)
        lines.push("  agent: '".concat(input.agent, "',"));
    if (input.webhook) {
        lines.push('  alerts: {', "    webhook: '".concat(input.webhook, "',"), '  },');
    }
    lines.push('};', '');
    return lines.join('\n');
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
