"use strict";
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk profile
 * Performance profiling via @platformatic/flame
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.profileCommand = exports.profileAnalyzeCommand = exports.profileGenerateCommand = exports.profileRunCommand = void 0;
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var node_path_1 = require("node:path");
var promises_1 = require("node:fs/promises");
var profile_list_js_1 = require("./profile-list.js");
var profile_report_js_1 = require("./profile-report.js");
var profile_compare_js_1 = require("./profile-compare.js");
exports.profileRunCommand = new commander_1.Command('run')
    .description('Start CPU profiling the Flusk server')
    .argument('[script]', 'Script to profile', './dist/index.js')
    .option('-d, --duration <seconds>', 'Duration in seconds', '30')
    .action(function (script, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var startProfiling;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0: return [4 /*yield*/, Promise.resolve().then(function () { return require('@platformatic/flame'); })];
            case 1:
                startProfiling = (_a.sent()).startProfiling;
                console.log(chalk_1.default.blue("\uD83D\uDD25 Profiling ".concat(script, " for ").concat(opts.duration, "s")));
                return [4 /*yield*/, startProfiling({
                        entrypoint: (0, node_path_1.resolve)(script),
                        duration: parseInt(opts.duration, 10),
                    })];
            case 2:
                _a.sent();
                console.log(chalk_1.default.green('✅ Profile complete'));
                return [2 /*return*/];
        }
    });
}); });
exports.profileGenerateCommand = new commander_1.Command('generate')
    .description('Generate flamegraph from pprof file')
    .argument('<pprof-file>', 'Path to .pprof file')
    .option('-o, --output <dir>', 'Output directory', './profiles')
    .action(function (pprofFile, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var flame, generateFlamegraph, generateMarkdown, outputDir, htmlPath, mdPath;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0: return [4 /*yield*/, Promise.resolve().then(function () { return require('@platformatic/flame'); })];
            case 1:
                flame = _a.sent();
                generateFlamegraph = flame.generateFlamegraph, generateMarkdown = flame.generateMarkdown;
                outputDir = (0, node_path_1.resolve)(opts.output);
                console.log(chalk_1.default.blue("\uD83D\uDCCA Generating flamegraph from ".concat(pprofFile)));
                return [4 /*yield*/, generateFlamegraph({
                        input: (0, node_path_1.resolve)(pprofFile),
                        outputDir: outputDir,
                    })];
            case 2:
                htmlPath = _a.sent();
                console.log(chalk_1.default.green("  \u2705 HTML: ".concat(htmlPath)));
                return [4 /*yield*/, generateMarkdown({
                        input: (0, node_path_1.resolve)(pprofFile),
                        outputDir: outputDir,
                    })];
            case 3:
                mdPath = _a.sent();
                console.log(chalk_1.default.green("  \u2705 MD:   ".concat(mdPath)));
                return [2 /*return*/];
        }
    });
}); });
exports.profileAnalyzeCommand = new commander_1.Command('analyze')
    .description('Print hotspot summary from markdown report')
    .argument('<md-file>', 'Path to .md report file')
    .action(function (mdFile) { return __awaiter(void 0, void 0, void 0, function () {
    var content, lines, _i, lines_1, line;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0: return [4 /*yield*/, (0, promises_1.readFile)((0, node_path_1.resolve)(mdFile), 'utf-8')];
            case 1:
                content = _a.sent();
                console.log(chalk_1.default.blue('\n🔍 Hotspot Summary\n'));
                lines = content.split('\n');
                for (_i = 0, lines_1 = lines; _i < lines_1.length; _i++) {
                    line = lines_1[_i];
                    if (line.startsWith('# ') || line.startsWith('## ')) {
                        console.log(chalk_1.default.bold.yellow(line));
                    }
                    else if (line.includes('%')) {
                        console.log(chalk_1.default.white(line));
                    }
                }
                return [2 /*return*/];
        }
    });
}); });
exports.profileCommand = new commander_1.Command('profile')
    .description('Performance profiling with @platformatic/flame');
exports.profileCommand.addCommand(exports.profileRunCommand);
exports.profileCommand.addCommand(exports.profileGenerateCommand);
exports.profileCommand.addCommand(exports.profileAnalyzeCommand);
exports.profileCommand.addCommand(profile_list_js_1.profileListCommand);
exports.profileCommand.addCommand(profile_report_js_1.profileReportCommand);
exports.profileCommand.addCommand(profile_compare_js_1.profileCompareCommand);
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
