"use strict";
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk profile compare <id1> <id2>
 * Side-by-side comparison of two profile sessions
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.profileCompareCommand = void 0;
exports.formatDiff = formatDiff;
exports.formatHotspotDiff = formatHotspotDiff;
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var undici_1 = require("undici");
function formatDiff(label, a, b, unit) {
    if (unit === void 0) { unit = ''; }
    var diff = b - a;
    var pct = a > 0 ? ((diff / a) * 100).toFixed(1) : 'N/A';
    var arrow = diff < 0
        ? chalk_1.default.green("\u25BC ".concat(Math.abs(diff)).concat(unit, " (").concat(pct, "%)"))
        : diff > 0
            ? chalk_1.default.red("\u25B2 ".concat(diff).concat(unit, " (+").concat(pct, "%)"))
            : chalk_1.default.dim('unchanged');
    return "  ".concat(label.padEnd(16), " ").concat(String(a) + unit, " \u2192 ").concat(String(b) + unit, "  ").concat(arrow);
}
function formatHotspotDiff(a, b) {
    var bMap = new Map(b.hotspots.map(function (h) { return [h.functionName, h]; }));
    var lines = a.hotspots.slice(0, 5).map(function (h) {
        var match = bMap.get(h.functionName);
        if (!match)
            return "  ".concat(h.functionName.slice(0, 30).padEnd(32), " ").concat(chalk_1.default.dim('removed'));
        var diff = match.percentage - h.percentage;
        var color = diff < 0 ? chalk_1.default.green : diff > 0 ? chalk_1.default.red : chalk_1.default.dim;
        return "  ".concat(h.functionName.slice(0, 30).padEnd(32), " ").concat(h.percentage.toFixed(1), "% \u2192 ").concat(match.percentage.toFixed(1), "% ").concat(color("(".concat(diff > 0 ? '+' : '').concat(diff.toFixed(1), "%)")));
    });
    return lines.join('\n');
}
function fetchProfile(endpoint, id, headers) {
    return __awaiter(this, void 0, void 0, function () {
        var res;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, (0, undici_1.request)("".concat(endpoint, "/v1/profiles/").concat(id), { headers: headers })];
                case 1:
                    res = _a.sent();
                    return [4 /*yield*/, res.body.json()];
                case 2: return [2 /*return*/, (_a.sent())];
            }
        });
    });
}
exports.profileCompareCommand = new commander_1.Command('compare')
    .description('Compare two profile sessions')
    .argument('<id1>', 'First profile session ID')
    .argument('<id2>', 'Second profile session ID')
    .option('-e, --endpoint <url>', 'API endpoint', 'http://localhost:3042')
    .option('-k, --api-key <key>', 'API key')
    .action(function (id1, id2, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var headers, _a, a, b;
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                headers = {};
                if (opts.apiKey)
                    headers['x-flusk-api-key'] = opts.apiKey;
                return [4 /*yield*/, Promise.all([
                        fetchProfile(opts.endpoint, id1, headers),
                        fetchProfile(opts.endpoint, id2, headers),
                    ])];
            case 1:
                _a = _b.sent(), a = _a[0], b = _a[1];
                console.log(chalk_1.default.blue("\n\u2696\uFE0F  Comparing: ".concat(chalk_1.default.bold(a.name), " vs ").concat(chalk_1.default.bold(b.name), "\n")));
                console.log(formatDiff('Duration', a.durationMs, b.durationMs, 'ms'));
                console.log(formatDiff('Samples', a.totalSamples, b.totalSamples));
                console.log(chalk_1.default.bold('\nHotspot Changes'));
                console.log(formatHotspotDiff(a, b));
                console.log('');
                return [2 /*return*/];
        }
    });
}); });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
