"use strict";
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk profile list
 * Lists recent profile sessions from the API
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.profileListCommand = void 0;
exports.formatTable = formatTable;
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var undici_1 = require("undici");
function formatTable(profiles) {
    var header = "".concat('ID'.padEnd(10), " ").concat('Name'.padEnd(24), " ").concat('Type'.padEnd(6), " ").concat('Duration'.padEnd(10), " ").concat('Samples'.padEnd(8), " Date");
    var sep = '-'.repeat(header.length);
    var rows = profiles.map(function (p) {
        var id = p.id.slice(0, 8);
        var name = p.name.slice(0, 22).padEnd(24);
        var type = p.type.padEnd(6);
        var dur = "".concat(p.durationMs, "ms").padEnd(10);
        var samples = String(p.totalSamples).padEnd(8);
        var date = new Date(p.createdAt).toLocaleDateString();
        return "".concat(id.padEnd(10), " ").concat(name, " ").concat(type, " ").concat(dur, " ").concat(samples, " ").concat(date);
    });
    return __spreadArray([header, sep], rows, true).join('\n');
}
exports.profileListCommand = new commander_1.Command('list')
    .description('List recent profile sessions')
    .option('-e, --endpoint <url>', 'API endpoint', 'http://localhost:3042')
    .option('-k, --api-key <key>', 'API key')
    .option('-l, --limit <n>', 'Max results', '20')
    .action(function (opts) { return __awaiter(void 0, void 0, void 0, function () {
    var url, headers, res, profiles;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0:
                url = "".concat(opts.endpoint, "/v1/profiles?limit=").concat(opts.limit);
                headers = {};
                if (opts.apiKey)
                    headers['x-flusk-api-key'] = opts.apiKey;
                return [4 /*yield*/, (0, undici_1.request)(url, { headers: headers })];
            case 1:
                res = _a.sent();
                return [4 /*yield*/, res.body.json()];
            case 2:
                profiles = (_a.sent());
                if (!profiles.length) {
                    console.log(chalk_1.default.yellow('No profile sessions found.'));
                    return [2 /*return*/];
                }
                console.log(chalk_1.default.blue('\n📊 Profile Sessions\n'));
                console.log(formatTable(profiles));
                console.log('');
                return [2 /*return*/];
        }
    });
}); });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
