"use strict";
/**
 * @generated by @flusk/cli — command recipe
 */
// --- BEGIN GENERATED ---
/**
 * CLI command: flusk regenerate — incremental code regeneration.
 *
 * WHY: After editing entity YAML, developers need to update
 * generated files without losing custom code. This command
 * detects stale files and regenerates only what changed.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.regenerateCommand = void 0;
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var node_path_1 = require("node:path");
var node_fs_1 = require("node:fs");
var logger_1 = require("@flusk/logger");
var forge_1 = require("@flusk/forge");
var logger = (0, logger_1.createLogger)({ name: 'cmd:regenerate' });
exports.regenerateCommand = new commander_1.Command('regenerate')
    .description('Regenerate stale generated files, preserving custom sections')
    .option('--all', 'Regenerate everything regardless of staleness')
    .option('--dry-run', 'Show what would change without writing')
    .action(function (opts) { return __awaiter(void 0, void 0, void 0, function () {
    var root, report, targets, yamlPaths, filesUpdated, customPreserved, _i, yamlPaths_1, yamlRel, yamlAbs, result, _a, _b, f, existing, merged;
    return __generator(this, function (_c) {
        root = process.cwd();
        report = (0, forge_1.detectChanges)(root, forge_1.DEFAULT_SCAN_DIRS);
        targets = opts.all ? __spreadArray(__spreadArray([], report.stale, true), report.fresh, true) : report.stale;
        console.log(chalk_1.default.blue("\n\uD83D\uDD0D Scanned ".concat(report.total, " generated files")));
        console.log("   Stale: ".concat(chalk_1.default.yellow(String(report.stale.length)), "  Fresh: ").concat(chalk_1.default.green(String(report.fresh.length)), "  Orphaned: ").concat(chalk_1.default.red(String(report.orphaned.length)), "\n"));
        if (!targets.length) {
            console.log(chalk_1.default.green('✅ Everything is up to date!\n'));
            return [2 /*return*/];
        }
        yamlPaths = __spreadArray([], new Set(targets.map(function (t) { return t.yamlPath; })), true);
        filesUpdated = 0;
        customPreserved = 0;
        for (_i = 0, yamlPaths_1 = yamlPaths; _i < yamlPaths_1.length; _i++) {
            yamlRel = yamlPaths_1[_i];
            yamlAbs = (0, node_path_1.resolve)(root, yamlRel);
            if (!(0, node_fs_1.existsSync)(yamlAbs))
                continue;
            logger.info({ yaml: yamlRel }, 'Regenerating from YAML');
            if (opts.dryRun) {
                console.log("  ".concat(chalk_1.default.cyan('would regenerate'), " from ").concat(yamlRel));
                continue;
            }
            result = (0, forge_1.runEntityPipeline)(yamlAbs, root);
            for (_a = 0, _b = result.files; _a < _b.length; _a++) {
                f = _b[_a];
                existing = (0, node_fs_1.existsSync)(f.path) ? (0, node_fs_1.readFileSync)(f.path, 'utf-8') : null;
                if (existing) {
                    merged = (0, forge_1.smartMerge)((0, node_fs_1.readFileSync)(f.path, 'utf-8'), existing);
                    (0, node_fs_1.writeFileSync)(f.path, merged.content, 'utf-8');
                    customPreserved += merged.customSectionsPreserved;
                    merged.warnings.forEach(function (w) { return console.log(chalk_1.default.yellow("  \u26A0\uFE0F  ".concat(w))); });
                }
                filesUpdated++;
                console.log("  ".concat(chalk_1.default.green('✅'), " ").concat(f.path, " (").concat(f.action, ")"));
            }
        }
        console.log(chalk_1.default.green("\n\u2728 Regenerated ".concat(filesUpdated, " files, preserved ").concat(customPreserved, " custom sections\n")));
        return [2 /*return*/];
    });
}); });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
