/**
 * @generated by @flusk/cli
 * CLI command: flusk training
 */
import { Command } from 'commander';
import { trainingStatusAction } from './training-status.js';
import { trainingPairsAction } from './training-pairs.js';
import { trainingClustersAction } from './training-clusters.js';
import { trainingExportAction } from './training-export.js';
import { trainingSavingsAction } from './training-savings.js';

// --- BEGIN CUSTOM ---
export const trainingCommand = new Command('training')
  .description('Manage training data collection for SLM fine-tuning');

trainingCommand
  .command('status')
  .description('Show collection stats')
  .option('-t, --tenant <id>', 'Filter by tenant ID')
  .action(trainingStatusAction);

trainingCommand
  .command('pairs')
  .description('List recent training pairs')
  .option('-m, --model <model>', 'Filter by source model')
  .option('-l, --limit <n>', 'Max pairs to show', '20')
  .action(trainingPairsAction);

trainingCommand
  .command('clusters')
  .description('Show detected pattern clusters')
  .option('-t, --tenant <id>', 'Filter by tenant ID')
  .action(trainingClustersAction);

trainingCommand
  .command('export')
  .description('Export dataset for fine-tuning')
  .requiredOption('-n, --name <name>', 'Dataset name')
  .option('-f, --format <fmt>', 'Format: jsonl|alpaca|sharegpt', 'jsonl')
  .option('-o, --output <path>', 'Output directory', './training-data')
  .action(trainingExportAction);

trainingCommand
  .command('savings')
  .description('Show estimated savings per cluster')
  .action(trainingSavingsAction);
// --- END CUSTOM ---
