/**
 * @generated by @flusk/cli
 */
import { test, describe } from 'node:test';
import assert from 'node:assert';
import { watchCommand } from './watch.js';

describe('watch command', () => {
  test('exports a Command instance', () => {
    assert.strictEqual(watchCommand.name(), 'watch');
  });
});
