"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.watchCommand = void 0;
/**
 * @generated by @flusk/cli
 * CLI command: flusk watch
 */
var commander_1 = require("commander");
var chalk_1 = require("chalk");
var node_child_process_1 = require("node:child_process");
var node_path_1 = require("node:path");
var node_fs_1 = require("node:fs");
var resources_1 = require("@flusk/resources");
var forge_1 = require("@flusk/forge");
var logger_1 = require("@flusk/logger");
var log = (0, logger_1.createLogger)({ name: 'watch' });
exports.watchCommand = new commander_1.Command('watch')
    .description('Live-watch LLM costs as your script runs (htop for AI spend)')
    .argument('<script>', 'Script to watch')
    .option('-a, --agent <name>', 'Label for multi-agent tracking')
    .action(function (script, opts) { return __awaiter(void 0, void 0, void 0, function () {
    var config, agentLabel, storage, session, scriptPath, cwd, child, renderWatchApp;
    var _a, _b;
    return __generator(this, function (_c) {
        switch (_c.label) {
            case 0: return [4 /*yield*/, (0, forge_1.loadConfig)()];
            case 1:
                config = _c.sent();
                agentLabel = opts.agent || config.agent || process.env.FLUSK_AGENT;
                storage = (0, resources_1.createSqliteStorage)((_a = config.storage) === null || _a === void 0 ? void 0 : _a.path);
                session = storage.analyzeSessions.create({
                    script: script,
                    durationMs: 0, totalCalls: 0,
                    totalCost: 0, modelsUsed: [], startedAt: new Date().toISOString(),
                });
                scriptPath = (0, node_path_1.resolve)((0, node_path_1.normalize)(script));
                cwd = process.cwd();
                if (!scriptPath.startsWith(cwd) && !scriptPath.startsWith((0, node_path_1.resolve)((_b = process.env.HOME) !== null && _b !== void 0 ? _b : '~'))) {
                    console.error(chalk_1.default.red("\u274C Path traversal detected: ".concat(scriptPath)));
                    process.exit(1);
                }
                if (!(0, node_fs_1.existsSync)(scriptPath)) {
                    console.error(chalk_1.default.red("\u274C Script not found: ".concat(scriptPath)));
                    process.exit(1);
                }
                child = spawnWithOtel(scriptPath, agentLabel, session.id);
                return [4 /*yield*/, Promise.resolve().then(function () { return require('../tui/screens/watch-app.js'); })];
            case 2:
                renderWatchApp = (_c.sent()).renderWatchApp;
                renderWatchApp({ sessionId: session.id, storage: storage, child: child });
                log.info({ sessionId: session.id }, 'Watch started');
                return [2 /*return*/];
        }
    });
}); });
function getOtelRegisterUrl() {
    var startDir = (function () {
        try {
            var fileURLToPath = require('node:url').fileURLToPath;
            return fileURLToPath(new URL('.', import.meta.url));
        }
        catch (_a) {
            return process.cwd();
        }
    })();
    var dir = startDir;
    for (var i = 0; i < 10; i++) {
        var candidate = (0, node_path_1.resolve)(dir, 'packages', 'otel', 'src', 'register.ts');
        if ((0, node_fs_1.existsSync)(candidate))
            return candidate;
        var parent_1 = (0, node_path_1.resolve)(dir, '..');
        if (parent_1 === dir)
            break;
        dir = parent_1;
    }
    return (0, node_path_1.resolve)(process.cwd(), 'packages', 'otel', 'src', 'register.ts');
}
function spawnWithOtel(scriptPath, agent, sessionId) {
    var _a, _b, _c;
    var otelRegister = getOtelRegisterUrl();
    var env = __assign(__assign(__assign(__assign({}, process.env), { FLUSK_MODE: 'local', FLUSK_SQLITE_PATH: (0, node_path_1.resolve)((_a = process.env.HOME) !== null && _a !== void 0 ? _a : '~', '.flusk', 'data.db') }), (agent ? { FLUSK_AGENT: agent, FLUSK_AGENT_LABEL: agent } : {})), (sessionId ? { FLUSK_SESSION_ID: sessionId } : {}));
    var safePath = scriptPath.replace(/\\/g, '/').replace(/'/g, "\\'");
    var safeOtel = otelRegister.replace(/\\/g, '/').replace(/'/g, "\\'");
    var wrapperPath = (0, node_path_1.resolve)((_b = process.env.HOME) !== null && _b !== void 0 ? _b : '~', '.flusk', '_watch-wrapper.mjs');
    (0, node_fs_1.mkdirSync)((0, node_path_1.resolve)((_c = process.env.HOME) !== null && _c !== void 0 ? _c : '~', '.flusk'), { recursive: true });
    (0, node_fs_1.writeFileSync)(wrapperPath, [
        "const { sdk, ready } = await import('".concat(safeOtel, "');"),
        "if (ready) await ready;",
        "await import('".concat(safePath, "');"),
        "if (sdk) { await sdk.shutdown(); }",
    ].join('\n'));
    var otelPkgDir = (0, node_path_1.resolve)(otelRegister, '..', '..');
    return (0, node_child_process_1.spawn)('npx', ['tsx', wrapperPath], {
        stdio: 'pipe',
        env: env,
        cwd: otelPkgDir,
    });
}
