/**
 * @generated by @flusk/cli — utility recipe
 */
// --- BEGIN GENERATED ---
/**
 * Generic OTLP exporter with platform presets
 * Supports: Grafana Tempo, Datadog, New Relic
 */
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import type { SpanExporter } from '@opentelemetry/sdk-trace-base';
import { createLogger } from '@flusk/logger';

const log = createLogger({ name: 'otlp-exporter' });

export type OtlpPlatform = 'grafana' | 'datadog' | 'newrelic' | 'custom';

export interface OtlpExporterConfig {
  platform: OtlpPlatform;
  endpoint?: string;
  apiKey?: string;
  instanceId?: string;
  headers?: Record<string, string>;
}

const PLATFORM_DEFAULTS: Record<OtlpPlatform, { endpoint: string; authHeader: string }> = {
  grafana: {
    endpoint: 'https://otlp-gateway-prod-us-east-0.grafana.net/otlp',
    authHeader: 'Authorization',
  },
  datadog: {
    endpoint: 'https://trace.agent.datadoghq.com/api/v0.2/traces',
    authHeader: 'DD-API-KEY',
  },
  newrelic: {
    endpoint: 'https://otlp.nr-data.net:4318/v1/traces',
    authHeader: 'Api-Key',
  },
  custom: {
    endpoint: 'http://localhost:4318/v1/traces',
    authHeader: 'Authorization',
  },
};

export function createOtlpExporter(config: OtlpExporterConfig): SpanExporter {
  const defaults = PLATFORM_DEFAULTS[config.platform];
  const endpoint = config.endpoint || defaults.endpoint;

  const headers: Record<string, string> = { ...config.headers };
  if (config.apiKey) {
    if (config.platform === 'grafana') {
      // Grafana Cloud OTLP uses Basic auth: base64(instanceId:token)
      // instanceId can be passed via config or extracted from endpoint
      const instanceId = config.instanceId || '';
      const credentials = instanceId ? `${instanceId}:${config.apiKey}` : config.apiKey;
      headers[defaults.authHeader] = `Basic ${Buffer.from(credentials).toString('base64')}`;
    } else {
      headers[defaults.authHeader] = config.apiKey;
    }
  }

  log.info(`OTLP exporter: ${config.platform} → ${endpoint}`);
  log.debug(`OTLP headers: ${JSON.stringify(Object.keys(headers))}`);
  const url = endpoint.endsWith('/v1/traces') ? endpoint : `${endpoint}/v1/traces`;
  return new OTLPTraceExporter({ url, headers, timeoutMillis: 10000 }) as unknown as SpanExporter;
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
