/**
 * @generated by @flusk/cli — otel-hook recipe
 * Parse an OTel ReadableSpan into the shape for SQLite LLM call storage.
 */

// --- BEGIN GENERATED ---
import type { ReadableSpan } from '@opentelemetry/sdk-trace-base';
import { SpanStatusCode } from '@opentelemetry/api';
import { createHash } from 'node:crypto';
import { llmCall } from '@flusk/business-logic';
import { createLogger } from '@flusk/logger';

const { calculateCost } = llmCall;
const log = createLogger({ name: 'parse-span' });
const GENAI_PREFIX = 'gen_ai.';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const MAX_STRING_LENGTH = 100 * 1024; // 100KB

function sanitizeString(val: string): string {
  return val.length > MAX_STRING_LENGTH ? val.slice(0, MAX_STRING_LENGTH) : val;
}

function sanitizeTokens(val: number): number {
  if (!Number.isFinite(val) || val < 0) return 0;
  return Math.floor(val);
}

function sanitizeCost(val: number): number {
  if (!Number.isFinite(val) || val < 0) return 0;
  return val;
}

function sanitizeProviderModel(val: string): string {
  return val.replace(/[^a-zA-Z0-9\-._/]/g, '');
}

function getAttr(span: ReadableSpan, key: string): string {
  const val = span.attributes[key];
  return typeof val === 'string' ? val : '';
}

function getNumAttr(span: ReadableSpan, key: string): number {
  const val = span.attributes[key];
  return typeof val === 'number' ? val : 0;
}

function isGenAiSpan(span: ReadableSpan): boolean {
  return Object.keys(span.attributes).some((k) => k.startsWith(GENAI_PREFIX));
}

function detectProvider(model: string, system: string): string {
  if (system === 'openai' || model.startsWith('gpt') || model.startsWith('o1')) return 'openai';
  if (system === 'anthropic' || model.startsWith('claude')) return 'anthropic';
  if (system === 'bedrock' || model.includes('amazon')) return 'bedrock';
  return 'other';
}

/**
 * Detect provider from HTTP URL
 */
function detectProviderFromUrl(url: string, userAgent: string): string | null {
  if (url.includes('api.openai.com')) return 'openai';
  if (url.includes('api.anthropic.com')) return 'anthropic';
    if (url.includes('generativelanguage.googleapis.com')) return 'google';
    if (url.includes('openai.azure.com')) return 'azure-openai';
    if (url.includes('api.cohere.com')) return 'cohere';
  if (url.includes('bedrock')) return 'bedrock';
  // Detect by user-agent (OpenAI SDK sets "OpenAI/JS ..." or "OpenAI/Python ...")
  if (userAgent.startsWith('OpenAI/')) return 'openai';
  if (userAgent.includes('anthropic')) return 'anthropic';
  // Detect by URL path patterns
  if (url.includes('/chat/completions')) return 'openai';
  if (url.includes('/v1/messages')) return 'anthropic';
  return null;
}

/**
 * Try to parse a GenAI-attributed span (from traceloop or native OTel GenAI instrumentation)
 */
function parseGenAiSpan(span: ReadableSpan): Record<string, unknown> | null {
  const rawModel = getAttr(span, 'gen_ai.response.model') || getAttr(span, 'gen_ai.request.model');
  const system = getAttr(span, 'gen_ai.system');
  const model = sanitizeProviderModel(rawModel);
  const provider = sanitizeProviderModel(detectProvider(rawModel, system));
  const prompt = sanitizeString(getAttr(span, 'gen_ai.prompt'));
  const input = sanitizeTokens(getNumAttr(span, 'gen_ai.usage.input_tokens'));
  const output = sanitizeTokens(getNumAttr(span, 'gen_ai.usage.output_tokens'));
  const tokens = { input, output, total: input + output };
  const promptHash = createHash('sha256').update(prompt).digest('hex');
  const result = calculateCost({ providerName: provider, modelName: model, tokenUsage: tokens });
  if (result.warning) log.warn(result.warning);
  const isError = span.status.code === SpanStatusCode.ERROR;

  return {
    provider,
    model,
    prompt,
    promptHash,
    tokens,
    cost: sanitizeCost(result.costUsd ?? 0),
    response: sanitizeString(getAttr(span, 'gen_ai.completion')),
    cached: false,
    status: isError ? 'error' : 'ok',
    errorMessage: isError ? (span.status.message ?? '') : '',
    organizationId: process.env['FLUSK_AGENT'] || 'default',
    consentGiven: true,
    consentPurpose: 'optimization',
  };
}

/**
 * Try to parse an HTTP span targeting a known LLM API endpoint.
 * Falls back when native GenAI instrumentation isn't available.
 */
function parseHttpLlmSpan(span: ReadableSpan): Record<string, unknown> | null {
  const url = getAttr(span, 'url.full');
  // statusCode available for future use
  void getNumAttr(span, 'http.response.status_code');
  if (!url) return null;

  const userAgent = getAttr(span, 'user_agent.original');
  const provider = detectProviderFromUrl(url, userAgent);
  if (!provider) return null;

  // Only parse chat completion endpoints
  if (!url.includes('/chat/completions') && !url.includes('/messages')) return null;

  // Try to extract model from request body captured in span events
  let model = 'unknown';
  let prompt = '';
  let inputTokens = 0;
  let outputTokens = 0;
  let response = '';

  // Check span events for request/response bodies
  for (const event of span.events) {
    const body = event.attributes?.['http.request.body'] || event.attributes?.['http.request.body.content'];
    if (typeof body === 'string') {
      try {
        const parsed = JSON.parse(body);
        if (parsed.model) model = parsed.model;
        if (parsed.messages) {
          const lastMsg = parsed.messages[parsed.messages.length - 1];
          if (lastMsg?.content) prompt = typeof lastMsg.content === 'string' ? lastMsg.content : JSON.stringify(lastMsg.content);
        }
      } catch { /* ignore */ }
    }
    const respBody = event.attributes?.['http.response.body'] || event.attributes?.['http.response.body.content'];
    if (typeof respBody === 'string') {
      try {
        const parsed = JSON.parse(respBody);
        if (parsed.model) model = parsed.model;
        if (parsed.usage) {
          inputTokens = parsed.usage.prompt_tokens || 0;
          outputTokens = parsed.usage.completion_tokens || 0;
        }
        if (parsed.choices?.[0]?.message?.content) {
          response = parsed.choices[0].message.content;
        }
      } catch { /* ignore */ }
    }
  }

  // If we couldn't extract a model from events, skip — we likely have a GenAI span for this call
  if (model === 'unknown') {
    return null;
  }

  const sanitizedModel = sanitizeProviderModel(model);
  const sanitizedProvider = sanitizeProviderModel(provider);
  const sanitizedPrompt = sanitizeString(prompt);
  const sanitizedResponse = sanitizeString(response);
  inputTokens = sanitizeTokens(inputTokens);
  outputTokens = sanitizeTokens(outputTokens);
  const tokens = { input: inputTokens, output: outputTokens, total: inputTokens + outputTokens };
  const promptHash = createHash('sha256').update(sanitizedPrompt).digest('hex');
  const result = calculateCost({ providerName: sanitizedProvider, modelName: sanitizedModel, tokenUsage: tokens });
  if (result.warning) log.warn(result.warning);
  const isError = span.status.code === SpanStatusCode.ERROR;

  return {
    provider: sanitizedProvider,
    model: sanitizedModel,
    prompt: sanitizedPrompt,
    promptHash,
    tokens,
    cost: sanitizeCost(result.costUsd ?? 0),
    response: sanitizedResponse,
    cached: false,
    status: isError ? 'error' : 'ok',
    errorMessage: isError ? (span.status.message ?? '') : '',
    organizationId: process.env['FLUSK_AGENT'] || 'default',
    consentGiven: true,
    consentPurpose: 'optimization',
  };
}

export function parseReadableSpan(span: ReadableSpan): Record<string, unknown> | null {
  // Prefer native GenAI spans
  if (isGenAiSpan(span)) return parseGenAiSpan(span);
  // Fall back to HTTP span parsing for known LLM endpoints
  return parseHttpLlmSpan(span);
}
// --- END CUSTOM ---
