/**
 * CLI command recipe — command and test file templates.
 */

import { toCamelCase } from '../generators/utils.js';

export function commandTemplate(
  name: string,
  description: string,
): string {
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * CLI command: flusk ${name}
 */
import { Command } from 'commander';
import chalk from 'chalk';

export const ${camel}Command = new Command('${name}')
  .description('${description}')
  .action(async () => {
    console.log(chalk.blue('Running ${name}...'));
    // TODO: implement
  });
`;
}

export function testTemplate(name: string): string {
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { test, describe } from 'node:test';
import assert from 'node:assert';
import { ${camel}Command } from './${name}.js';

describe('${name} command', () => {
  test('exports a Command instance', () => {
    assert.strictEqual(${camel}Command.name(), '${name}');
  });
});
`;
}
