/**
 * Client recipe — scaffolds an HTTP client + test.
 *
 * WHY: HTTP clients follow a pattern: class with baseUrl,
 * methods using undici/fetch, typed responses. This generates
 * the boilerplate so you only implement the API calls.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { toPascalCase, toCamelCase } from '../generators/utils.js';

const generateClient: RecipeStep = {
  name: 'generate-client',
  description: 'Generate HTTP client class',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'resources';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/clients`);
    const content = clientTemplate(name);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.client.ts`, content)],
    };
  },
};

const generateTest: RecipeStep = {
  name: 'generate-test',
  description: 'Generate client test file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'resources';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/clients`);
    const content = testTemplate(name);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.client.test.ts`, content)],
    };
  },
};

export const clientRecipe: Recipe = {
  name: 'client',
  description: 'Generate an HTTP client with test',
  steps: [generateClient, generateTest],
};

function clientTemplate(name: string): string {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * ${pascal} Client — HTTP client using undici
 */

import { request } from 'undici';
import { getLogger } from '@flusk/logger';

const log = getLogger().child({ module: '${name}-client' });

export class ${pascal}Client {
  private readonly baseUrl: string;

  constructor(baseUrl?: string) {
    this.baseUrl = baseUrl
      ?? process.env['${name.toUpperCase().replace(/-/g, '_')}_URL']
      ?? 'http://localhost:3000';
  }

  // CUSTOM:START — add client methods
  // CUSTOM:END
}

export const ${camel}Client = new ${pascal}Client();
`;
}

function testTemplate(name: string): string {
  const pascal = toPascalCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';
import { ${pascal}Client } from './${name}.client.js';

describe('${pascal}Client', () => {
  it('should create with default config', () => {
    const client = new ${pascal}Client('http://test:3000');
    expect(client).toBeDefined();
  });
});
`;
}
