/**
 * Function registry recipe — scans all .fn.yaml files and generates
 * TypeScript + Python implementations, tests, barrels, and a registry manifest.
 *
 * WHY: All pure functions are defined in YAML. Running this recipe
 * keeps generated code in sync across TypeScript and Python.
 */

import { resolve } from 'node:path';
import { writeFileSync } from 'node:fs';
import { readdir, writeFile, mkdir } from 'node:fs/promises';
import { stringify } from 'yaml';
import type { Recipe, RecipeStep } from './recipe.types.js';
import {
  loadFnSchema,
  generateFunction,
  updateNamespaceBarrel,
  updatePrimitivesBarrel,
} from '../generators/function.generator.js';
import {
  generatePyFunction,
  updatePyNamespaceInit,
  updatePyPrimitivesInit,
} from '../generators/python/function.generator.js';

const FN_SCHEMA_ROOT = 'packages/schema/functions';

/** Scan for all .fn.yaml files grouped by namespace */
async function scanFnYamls(
  projectRoot: string,
): Promise<Map<string, string[]>> {
  const root = resolve(projectRoot, FN_SCHEMA_ROOT);
  const namespaces = await readdir(root);
  const result = new Map<string, string[]>();

  for (const ns of namespaces) {
    if (ns.startsWith('_') || ns.endsWith('.yaml')) continue;
    const nsDir = resolve(root, ns);
    const files = await readdir(nsDir).catch(() => []);
    const yamlFiles = files
      .filter(f => f.endsWith('.fn.yaml'))
      .map(f => resolve(nsDir, f));
    if (yamlFiles.length) result.set(ns, yamlFiles);
  }

  return result;
}

/** Step 1: Generate TypeScript functions + tests */
const generateTsStep: RecipeStep = {
  name: 'generate-ts-functions',
  description: 'Generate TypeScript functions and tests from .fn.yaml files',
  async run(ctx) {
    const yamlMap = await scanFnYamls(ctx.projectRoot);
    const allFiles: Array<{ path: string; action: 'created' | 'updated' }> = [];
    const namespaces = [...yamlMap.keys()];

    for (const [, yamls] of yamlMap) {
      for (const yamlPath of yamls) {
        const result = await generateFunction(yamlPath, ctx.projectRoot);
        allFiles.push(...result.files);
      }
    }

    // Update namespace barrels
    for (const ns of namespaces) {
      const entry = await updateNamespaceBarrel(ns, ctx.projectRoot);
      allFiles.push(entry);
    }

    // Update master primitives barrel
    const masterEntry = await updatePrimitivesBarrel(namespaces, ctx.projectRoot);
    allFiles.push(masterEntry);

    ctx.shared['namespaces'] = namespaces;
    return { files: allFiles, shared: { namespaces } };
  },
};

/** Step 2: Generate Python functions + tests */
const generatePyStep: RecipeStep = {
  name: 'generate-py-functions',
  description: 'Generate Python functions and tests from .fn.yaml files',
  async run(ctx) {
    const yamlMap = await scanFnYamls(ctx.projectRoot);
    const allFiles: Array<{ path: string; action: 'created' | 'updated' }> = [];
    const namespaces = [...yamlMap.keys()];

    for (const [ns, yamls] of yamlMap) {
      for (const yamlPath of yamls) {
        const schema = await loadFnSchema(yamlPath);
        const files = await generatePyFunction(schema, ctx.projectRoot);
        allFiles.push(...files);
      }
      const init = await updatePyNamespaceInit(ns, ctx.projectRoot);
      allFiles.push(init);
    }

    const primInit = await updatePyPrimitivesInit(namespaces, ctx.projectRoot);
    allFiles.push(primInit);

    return { files: allFiles };
  },
};

/** Step 3: Write _registry.yaml manifest */
const generateRegistryStep: RecipeStep = {
  name: 'generate-registry',
  description: 'Generate packages/schema/functions/_registry.yaml manifest',
  async run(ctx) {
    const yamlMap = await scanFnYamls(ctx.projectRoot);
    const registry: Array<{ name: string; namespace: string; description: string; yamlPath: string }> = [];

    for (const [ns, yamls] of yamlMap) {
      for (const yamlPath of yamls) {
        const schema = await loadFnSchema(yamlPath);
        registry.push({
          name: schema.name,
          namespace: ns,
          description: schema.description,
          yamlPath: yamlPath.replace(ctx.projectRoot + '/', ''),
        });
      }
    }

    const registryYaml = stringify({
      generated: new Date().toISOString(),
      count: registry.length,
      functions: registry,
    });

    const outPath = resolve(ctx.projectRoot, FN_SCHEMA_ROOT, '_registry.yaml');
    if (!ctx.dryRun) {
      writeFileSync(outPath, `# @generated by @flusk/cli — function-registry recipe\n${registryYaml}`, 'utf-8');
    }

    return { files: [{ path: `${FN_SCHEMA_ROOT}/_registry.yaml`, action: 'created' as const }] };
  },
};

/** Step 4: Ensure flusk-py/tests/primitives/__init__.py exists */
const ensureTestsInitStep: RecipeStep = {
  name: 'ensure-tests-init',
  description: 'Ensure flusk-py/tests/primitives/__init__.py exists',
  async run(ctx) {
    const testsDir = resolve(ctx.projectRoot, 'flusk-py/tests/primitives');
    await mkdir(testsDir, { recursive: true });
    const initPath = resolve(testsDir, '__init__.py');
    const content = '# @generated by @flusk/cli\n';
    if (!ctx.dryRun) {
      await writeFile(initPath, content, 'utf-8');
    }
    return { files: [{ path: 'flusk-py/tests/primitives/__init__.py', action: 'created' as const }] };
  },
};

export const functionRegistryRecipe: Recipe = {
  name: 'function-registry',
  description: 'Generate all pure functions (TypeScript + Python) from .fn.yaml schemas',
  steps: [ensureTestsInitStep, generateTsStep, generatePyStep, generateRegistryStep],
};
