/**
 * Python generation + registry manifest steps for function registry recipe.
 */

import { resolve } from 'node:path';
import { writeFileSync } from 'node:fs';
import { writeFile, mkdir } from 'node:fs/promises';
import { stringify } from 'yaml';
import type { RecipeStep } from './recipe.types.js';
import { loadFnSchema } from '../generators/function.generator.js';
import {
  generatePyFunction,
  updatePyNamespaceInit,
  updatePyPrimitivesInit,
} from '../generators/python/function.generator.js';
import { scanFnYamls, FN_SCHEMA_ROOT } from './function-registry-scan.js';

/** Generate Python functions + tests */
export const generatePyStep: RecipeStep = {
  name: 'generate-py-functions',
  description: 'Generate Python functions and tests from .fn.yaml files',
  async run(ctx) {
    const yamlMap = await scanFnYamls(ctx.projectRoot);
    const allFiles: Array<{ path: string; action: 'created' | 'updated' }> = [];
    const namespaces = [...yamlMap.keys()];

    for (const [ns, yamls] of yamlMap) {
      for (const yamlPath of yamls) {
        const schema = await loadFnSchema(yamlPath);
        allFiles.push(...await generatePyFunction(schema, ctx.projectRoot));
      }
      allFiles.push(await updatePyNamespaceInit(ns, ctx.projectRoot));
    }
    allFiles.push(await updatePyPrimitivesInit(namespaces, ctx.projectRoot));
    return { files: allFiles };
  },
};

/** Write _registry.yaml manifest */
export const generateRegistryStep: RecipeStep = {
  name: 'generate-registry',
  description: 'Generate packages/schema/functions/_registry.yaml manifest',
  async run(ctx) {
    const yamlMap = await scanFnYamls(ctx.projectRoot);
    const registry: Array<{
      name: string; namespace: string; description: string; yamlPath: string;
    }> = [];

    for (const [ns, yamls] of yamlMap) {
      for (const yamlPath of yamls) {
        const schema = await loadFnSchema(yamlPath);
        registry.push({
          name: schema.name,
          namespace: ns,
          description: schema.description,
          yamlPath: yamlPath.replace(ctx.projectRoot + '/', ''),
        });
      }
    }

    const registryYaml = stringify({
      generated: new Date().toISOString(),
      count: registry.length,
      functions: registry,
    });
    const outPath = resolve(ctx.projectRoot, FN_SCHEMA_ROOT, '_registry.yaml');
    if (!ctx.dryRun) {
      writeFileSync(
        outPath,
        `# @generated by @flusk/cli — function-registry recipe\n${registryYaml}`,
        'utf-8',
      );
    }
    return { files: [{ path: `${FN_SCHEMA_ROOT}/_registry.yaml`, action: 'created' as const }] };
  },
};

/** Ensure flusk-py/tests/primitives/__init__.py exists */
export const ensureTestsInitStep: RecipeStep = {
  name: 'ensure-tests-init',
  description: 'Ensure flusk-py/tests/primitives/__init__.py exists',
  async run(ctx) {
    const testsDir = resolve(ctx.projectRoot, 'flusk-py/tests/primitives');
    await mkdir(testsDir, { recursive: true });
    if (!ctx.dryRun) {
      await writeFile(resolve(testsDir, '__init__.py'), '# @generated by @flusk/cli\n', 'utf-8');
    }
    return { files: [{ path: 'flusk-py/tests/primitives/__init__.py', action: 'created' as const }] };
  },
};
