/**
 * HTTP client recipe — generates a typed HTTP client + test.
 *
 * WHY: HTTP clients share boilerplate (URL validation, retries,
 * SSRF protection). This recipe produces a complete client with
 * all security patterns built in.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { generateHttpClient } from '../generators/http-client.generator.js';
import { toPascalCase } from '../generators/utils.js';

const generateClientFile: RecipeStep = {
  name: 'generate-http-client',
  description: 'Generate HTTP client with SSRF protection and retries',
  async run(ctx) {
    const clientName = ctx.options['name'] as string;
    const configKey = (ctx.options['config-key'] as string) ?? clientName;
    const result = generateHttpClient({
      clientName,
      baseUrlConfigKey: configKey,
      projectRoot: ctx.projectRoot,
    });
    const dir = resolve(
      ctx.projectRoot,
      'packages/resources/src/clients',
    );
    const filename = `${clientName}.client.ts`;
    return {
      files: [writeRecipeFile(ctx, dir, filename, result.content)],
    };
  },
};

const generateTestFile: RecipeStep = {
  name: 'generate-http-client-test',
  description: 'Generate HTTP client test file',
  async run(ctx) {
    const clientName = ctx.options['name'] as string;
    const pascal = toPascalCase(clientName);
    const dir = resolve(
      ctx.projectRoot,
      'packages/resources/src/clients',
    );
    const content = `/**
 * @generated by @flusk/cli — http-client recipe
 */
import { describe, it, expect } from 'vitest';
import { ${pascal}Client } from './${clientName}.client.js';

describe('${pascal}Client', () => {
  it('should create with default config', () => {
    const client = new ${pascal}Client('http://test:3000');
    expect(client).toBeDefined();
  });
});
`;
    return {
      files: [writeRecipeFile(ctx, dir, `${clientName}.client.test.ts`, content)],
    };
  },
};

export const httpClientRecipe: Recipe = {
  name: 'http-client',
  description: 'Generate HTTP client with SSRF protection, retries, and test',
  steps: [generateClientFile, generateTestFile],
};
