/**
 * Logger recipe — scaffolds a logger package from config.
 *
 * WHY: Logger packages follow a pattern: factory function,
 * singleton getter, types, levels. This generates the full
 * package structure.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';

const generateTypes: RecipeStep = {
  name: 'generate-types',
  description: 'Generate logger types',
  async run(ctx) {
    const name = (ctx.options['name'] as string) ?? 'logger';
    const pkg = (ctx.options['package'] as string) ?? name;
    const dir = resolve(ctx.projectRoot, `packages/${pkg}/src`);
    const content = typesTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, 'types.ts', content)] };
  },
};

const generateLevels: RecipeStep = {
  name: 'generate-levels',
  description: 'Generate log level constants',
  async run(ctx) {
    const pkg = (ctx.options['package'] as string) ?? 'logger';
    const dir = resolve(ctx.projectRoot, `packages/${pkg}/src`);
    return { files: [writeRecipeFile(ctx, dir, 'levels.ts', levelsTemplate())] };
  },
};

const generateFactory: RecipeStep = {
  name: 'generate-factory',
  description: 'Generate logger factory',
  async run(ctx) {
    const name = (ctx.options['name'] as string) ?? 'logger';
    const pkg = (ctx.options['package'] as string) ?? name;
    const dir = resolve(ctx.projectRoot, `packages/${pkg}/src`);
    const content = factoryTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, 'create-logger.ts', content)] };
  },
};

const generateSingleton: RecipeStep = {
  name: 'generate-singleton',
  description: 'Generate singleton logger',
  async run(ctx) {
    const pkg = (ctx.options['package'] as string) ?? 'logger';
    const dir = resolve(ctx.projectRoot, `packages/${pkg}/src`);
    return { files: [writeRecipeFile(ctx, dir, 'logger.ts', singletonTemplate())] };
  },
};

const generateBarrel: RecipeStep = {
  name: 'generate-barrel',
  description: 'Generate logger barrel export',
  async run(ctx) {
    const pkg = (ctx.options['package'] as string) ?? 'logger';
    const dir = resolve(ctx.projectRoot, `packages/${pkg}/src`);
    return { files: [writeRecipeFile(ctx, dir, 'index.ts', barrelTemplate())] };
  },
};

export const loggerRecipe: Recipe = {
  name: 'logger',
  description: 'Generate a structured logger package',
  steps: [generateTypes, generateLevels, generateFactory, generateSingleton, generateBarrel],
};

function typesTemplate(name: string): string {
  return `/**
 * @generated by @flusk/cli
 * Logger configuration types
 */

export interface ${capitalize(name)}LoggerOptions {
  name?: string;
  level?: string;
  pretty?: boolean;
}
`;
}

function levelsTemplate(): string {
  return `/**
 * @generated by @flusk/cli
 * Log level constants
 */

export const LOG_LEVELS = {
  fatal: 60,
  error: 50,
  warn: 40,
  info: 30,
  debug: 20,
  trace: 10,
} as const;

export type LogLevel = keyof typeof LOG_LEVELS;
`;
}

function factoryTemplate(name: string): string {
  return `/**
 * @generated by @flusk/cli
 * Logger factory — creates a configured Pino instance
 */

import pino from 'pino';
import type { ${capitalize(name)}LoggerOptions } from './types.js';

export function createLogger(
  options: ${capitalize(name)}LoggerOptions = {},
): pino.Logger {
  const level = options.level
    || process.env.${name.toUpperCase()}_LOG_LEVEL
    || 'info';

  const pretty = options.pretty
    ?? process.env.NODE_ENV !== 'production';

  return pino({
    name: options.name || '${name}',
    level,
    ...(pretty
      ? { transport: { target: 'pino-pretty', options: { colorize: true } } }
      : {}),
  });
}
`;
}

function singletonTemplate(): string {
  return `/**
 * @generated by @flusk/cli
 * Singleton logger instance
 */

import type pino from 'pino';
import { createLogger } from './create-logger.js';

let _instance: pino.Logger | null = null;

export function getLogger(): pino.Logger {
  if (!_instance) _instance = createLogger();
  return _instance;
}

export function setLogger(logger: pino.Logger): void {
  _instance = logger;
}

export function resetLogger(): void {
  _instance = null;
}
`;
}

function barrelTemplate(): string {
  return `/**
 * @generated by @flusk/cli
 */

export { createLogger } from './create-logger.js';
export { getLogger } from './logger.js';
export type { FluskLoggerOptions } from './types.js';
export type { LogLevel } from './levels.js';
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
