/**
 * Templates for the logger recipe — types, levels, barrel.
 */

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export { capitalize };

export function typesTemplate(name: string): string {
  return `/**
 * @generated by @flusk/cli
 * Logger configuration types
 */

export interface ${capitalize(name)}LoggerOptions {
  name?: string;
  level?: string;
  pretty?: boolean;
}
`;
}

export function levelsTemplate(): string {
  return `/**
 * @generated by @flusk/cli
 * Log level constants
 */

export const LOG_LEVELS = {
  fatal: 60,
  error: 50,
  warn: 40,
  info: 30,
  debug: 20,
  trace: 10,
} as const;

export type LogLevel = keyof typeof LOG_LEVELS;
`;
}

export function barrelTemplate(): string {
  return `/**
 * @generated by @flusk/cli
 */

export { createLogger } from './create-logger.js';
export { getLogger } from './logger.js';
export type { FluskLoggerOptions } from './types.js';
export type { LogLevel } from './levels.js';
`;
}
