/**
 * Standalone route recipe — scaffolds a Fastify route directory.
 *
 * WHY: Routes follow a consistent pattern (index.ts for registration,
 * handler file with schema). This wraps the route generator for
 * the recipe system.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { toPascalCase, toCamelCase } from '../generators/utils.js';

const generateIndex: RecipeStep = {
  name: 'generate-route-index',
  description: 'Generate route index (registration)',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'execution';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/routes/${name}-routes`);
    const content = indexTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, 'index.ts', content)] };
  },
};

const generateHandler: RecipeStep = {
  name: 'generate-route-handler',
  description: 'Generate route handler file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'execution';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/routes/${name}-routes`);
    const content = handlerTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, `${name}.ts`, content)] };
  },
};

const generateTest: RecipeStep = {
  name: 'generate-route-test',
  description: 'Generate route test file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'execution';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/routes/${name}-routes`);
    const content = testTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, `${name}.test.ts`, content)] };
  },
};

export const routeRecipe: Recipe = {
  name: 'route',
  description: 'Generate a standalone Fastify route with handler and test',
  steps: [generateIndex, generateHandler, generateTest],
};

function indexTemplate(name: string): string {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * ${pascal} routes — registration entrypoint
 */

import type { FastifyInstance } from 'fastify';
import { register${pascal}Handlers } from './${name}.js';

export async function ${camel}Routes(
  fastify: FastifyInstance,
): Promise<void> {
  register${pascal}Handlers(fastify);
}
`;
}

function handlerTemplate(name: string): string {
  const pascal = toPascalCase(name);
  return `/**
 * @generated by @flusk/cli
 * ${pascal} route handlers
 */

import type { FastifyInstance } from 'fastify';
import { Type } from '@sinclair/typebox';
import { getLogger } from '@flusk/logger';

const log = getLogger().child({ module: '${name}-routes' });

export function register${pascal}Handlers(
  fastify: FastifyInstance,
): void {
  fastify.get('/', {
    schema: {
      response: { 200: Type.Object({ status: Type.String() }) },
    },
  }, async (request) => {
    log.info({ url: request.url }, '${name} request');
    // CUSTOM:START — add route logic
    return { status: 'ok' };
    // CUSTOM:END
  });
}
`;
}

function testTemplate(name: string): string {
  const pascal = toPascalCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';

describe('${pascal} routes', () => {
  it('should export handler registration', async () => {
    const mod = await import('./${name}.js');
    expect(mod.register${pascal}Handlers).toBeDefined();
  });
});
`;
}
