/**
 * @generated by flusk CLI v1.0.0
 * Generated from: packages/entities/src/llm-call.entity.ts
 * DO NOT EDIT - Changes will be overwritten on regeneration
 * To regenerate: flusk g llm-call.entity.ts
 * Last generated: 2026-02-06T14:30:00Z
 */

import { Type, Static } from '@sinclair/typebox';

/**
 * TypeScript type generated from LlmCallEntity schema
 */
export type LlmCall = Static<typeof LlmCallSchema>;

/**
 * JSON Schema for LlmCall entity
 * Used for validation and OpenAPI generation
 */
export const LlmCallSchema = Type.Object(
  {
    id: Type.String({ format: 'uuid', description: 'Unique identifier' }),
    model: Type.String({ description: 'LLM model name' }),
    prompt: Type.String({ description: 'User prompt' }),
    completion: Type.String({ description: 'Model response' }),
    tokens: Type.Integer({ minimum: 0, description: 'Total tokens used' }),
    cost: Type.Number({ minimum: 0, description: 'Cost in USD' }),
    timestamp: Type.String({ format: 'date-time' }),
  },
  {
    $id: 'LlmCall',
    title: 'LLM API Call',
    description: 'Record of an LLM API call for cost tracking',
  }
);

/**
 * Create operation schema
 */
export const CreateLlmCallSchema = Type.Omit(LlmCallSchema, ['id', 'timestamp']);

/**
 * Update operation schema
 */
export const UpdateLlmCallSchema = Type.Partial(CreateLlmCallSchema);

/**
 * Query parameters schema
 */
export const QueryLlmCallSchema = Type.Object({
  model: Type.Optional(Type.String()),
  startDate: Type.Optional(Type.String({ format: 'date-time' })),
  endDate: Type.Optional(Type.String({ format: 'date-time' })),
  limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100, default: 20 })),
  offset: Type.Optional(Type.Integer({ minimum: 0, default: 0 })),
});
