// This file is auto-generated by TanStack Router
// Do not edit manually — run `pnpm dev` or `pnpm build` to regenerate

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router';
import { Route as rootRoute } from './routes/__root.js';
import { Route as IndexRoute } from './routes/index.js';
import { Route as DashboardRoute } from './routes/dashboard.js';
import { Route as WorkflowsRoute } from './routes/workflows.js';
import { Route as IntegrationsRoute } from './routes/integrations.js';

const rootTree = rootRoute.addChildren([
  IndexRoute,
  DashboardRoute,
  WorkflowsRoute,
  IntegrationsRoute,
]);

export const routeTree = rootTree;

export type Router = ReturnType<typeof createRouter<typeof routeTree>>;

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      parentRoute: typeof rootRoute;
    };
    '/workflows': {
      parentRoute: typeof rootRoute;
    };
    '/integrations': {
      parentRoute: typeof rootRoute;
    };
  }
}
