/**
 * @generated by @flusk/cli — sqlite-repo recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import type { DatabaseSync } from 'node:sqlite';
import type { InsightEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * List Insights by session ID, ordered by savings descending
 */
export function listBySessionId(
  db: DatabaseSync,
  sessionId: string,
): InsightEntity[] {
  const stmt = db.prepare(
    'SELECT * FROM insights WHERE session_id = ? ORDER BY savings_percent DESC',
  );
  const rows = stmt.all(sessionId) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}

/**
 * List Insights with pagination
 */
export function list(
  db: DatabaseSync,
  limit = 50,
  offset = 0,
): InsightEntity[] {
  const stmt = db.prepare(
    'SELECT * FROM insights ORDER BY created_at DESC LIMIT ? OFFSET ?',
  );
  const rows = stmt.all(limit, offset) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
