# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.conversation.is_abandoned import is_abandoned


def test_not_abandoned():
    assert is_abandoned(1000000, 1060000, 30) == False


def test_abandoned():
    assert is_abandoned(1000000, 5000000, 30) == True


def test_exactly_at_threshold():
    assert is_abandoned(0, 1800000, 30) == False
