# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.conversation.track_call import track_call


def test_first_call():
    assert track_call(0, 0, 0, 0, 100, 50, 0.005) == {"turnCount":1,"totalInputTokens":100,"totalOutputTokens":50,"totalCost":0.005}


def test_subsequent_call():
    assert track_call(3, 500, 200, 0.05, 150, 80, 0.01) == {"turnCount":4,"totalInputTokens":650,"totalOutputTokens":280,"totalCost":0.06}
