# syntax=docker/dockerfile:1
# Generated by @flusk/cli

# ── Stage 1: dependencies ──────────────────────────
FROM node:22-alpine AS deps
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/*/package.json ./packages/
RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --ignore-scripts

# ── Stage 2: build ─────────────────────────────────
FROM deps AS build
COPY . .
RUN pnpm build

# ── Stage 3: runtime ───────────────────────────────
FROM node:22-alpine AS runtime
RUN apk add --no-cache tini && corepack enable
ENV NODE_ENV=production PORT=3000 HOST=0.0.0.0
WORKDIR /app
COPY --from=build /app/packages ./packages
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./
COPY --from=build /app/server.ts ./
COPY scripts/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
EXPOSE 3000
ENTRYPOINT ["tini", "--"]
CMD ["pnpm", "start"]
