/**
 * @generated by @flusk/cli — sqlite-repo recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import type { DatabaseSync } from 'node:sqlite';
import type { ExplainSessionEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Insert a new ExplainSession record into SQLite
 */
export function create(
  db: DatabaseSync,
  data: Omit<ExplainSessionEntity, 'id' | 'createdAt' | 'updatedAt'>,
): ExplainSessionEntity {
  const stmt = db.prepare(`
    INSERT INTO explain_sessions (
      analyze_session_id, llm_provider, llm_model, prompt_tokens,
      completion_tokens, explain_cost, insights_count, total_savings
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    RETURNING *
  `);

  const row = stmt.get(
    data.analyzeSessionId,
    data.llmProvider,
    data.llmModel,
    data.promptTokens,
    data.completionTokens,
    data.explainCost,
    data.insightsCount,
    data.totalSavings,
  ) as Record<string, unknown>;

  return rowToEntity(row);
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
