/**
 * @generated by @flusk/cli
 * Generator for the root TUI app
 */

import { resolve } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { generateTuiAppTemplate } from '../../templates/tui/app.template.js';

export async function generateTuiApp(): Promise<string> {
  const dir = resolve(process.cwd(), 'packages/cli/src/tui');
  await mkdir(dir, { recursive: true });
  const filePath = resolve(dir, 'app.tsx');
  const content = generateTuiAppTemplate();
  await writeFile(filePath, content, 'utf-8');
  return filePath;
}
