/**
 * @generated by @flusk/cli — otel-hook recipe
 * Creates and configures the OpenTelemetry NodeSDK for Flusk.
 */

// --- BEGIN GENERATED ---
import { NodeSDK } from '@opentelemetry/sdk-node';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { BedrockInstrumentation } from '@traceloop/instrumentation-bedrock';
import { OpenAIInstrumentation } from '@traceloop/instrumentation-openai';
import { Resource } from '@opentelemetry/resources';
import { ATTR_SERVICE_NAME } from '@opentelemetry/semantic-conventions';
import { type SpanProcessor, BatchSpanProcessor } from '@opentelemetry/sdk-trace-base';
import type { FluskOtelConfig } from './config.js';
import { resolveExporter } from './utils/resolve-exporter.js';
import { patchAnthropic } from './instrumentations/anthropic.js';
import { patchGoogle } from './instrumentations/google.js';
import { SanitizeSpanProcessor } from './processors/sanitize-span-processor.js';
import { patchAzureOpenai } from './instrumentations/azure-openai.js';
import { patchCohere } from './instrumentations/cohere.js';
import { patchOpenai } from './instrumentations/openai.js';

export interface CreateSdkOptions {
  spanProcessors?: SpanProcessor[];
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export function createSdk(config: FluskOtelConfig, opts?: CreateSdkOptions): NodeSDK {
    patchAnthropic();
    patchGoogle();
    patchAzureOpenai();
    patchCohere();
    patchOpenai();
  const traceExporter = resolveExporter(config);

  const resource = new Resource({
    [ATTR_SERVICE_NAME]: config.projectName,
    'flusk.project.name': config.projectName,
  });

  const instrumentations = [
    new BedrockInstrumentation(),
    new OpenAIInstrumentation(),
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-undici': { enabled: true },
      '@opentelemetry/instrumentation-fs': { enabled: false },
      '@opentelemetry/instrumentation-dns': { enabled: false },
      '@opentelemetry/instrumentation-net': { enabled: false },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- openai instrumentation config not in auto-instrumentations type defs yet
      ...({ '@opentelemetry/instrumentation-openai': { captureContent: config.captureContent } } as any),
    }),
  ];

  // Build span processors: sanitize + exporter + any custom ones.
  // NOTE: When spanProcessors is provided, NodeSDK ignores traceExporter.
  // We must wrap the exporter in a BatchSpanProcessor ourselves.
  const spanProcessors: SpanProcessor[] = [
    new SanitizeSpanProcessor(),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- exporter types are overly strict
    new BatchSpanProcessor(traceExporter as any),
    ...(opts?.spanProcessors ?? []),
  ];

  return new NodeSDK({
    resource,
    instrumentations,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- NodeSDK expects specific SpanProcessor array type
    spanProcessors: spanProcessors as any,
  });
}
// --- END CUSTOM ---
