/**
 * @generated by @flusk/cli — otel-hook recipe
 * @flusk/otel — Zero-touch OpenTelemetry auto-instrumentation for Flusk
 */

// --- BEGIN GENERATED ---
export { loadConfig } from './config.js';
export type { FluskOtelConfig, FluskExportTarget } from './config.js';
export { createSdk } from './create-sdk.js';
export type { CreateSdkOptions } from './create-sdk.js';
export { SqliteSpanExporter, parseReadableSpan, createOtlpExporter, MultiSpanExporter } from './exporters/index.js';
export type { OtlpPlatform, OtlpExporterConfig } from './exporters/index.js';
export { resolveExporter, resolveMode } from './utils/resolve-exporter.js';
export type { FluskMode } from './utils/resolve-exporter.js';
export { isFlameAvailable, resetFlameDetectionCache } from './utils/detect-flame.js';
export { setupAutoFlame } from './utils/auto-register-flame.js';
export { flameProfilePlugin } from './plugins/flame-profile.plugin.js';
export type { ProfilerDecorator, ProfileMode, FlameProfileOptions } from './plugins/flame-profile.plugin.js';
export { createAutoProfileProcessor } from './hooks/auto-profile.hook.js';
export type { AutoProfileHookOptions } from './hooks/auto-profile.hook.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
