/**
 * @generated by @flusk/cli — utility recipe
 */
// --- BEGIN GENERATED ---
declare module '@platformatic/flame' {
  export function start(opts?: Record<string, unknown>): void;
  export function stop(): Promise<{ markdown: string; json: unknown }>;
  export function isRunning(): boolean;
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
