/**
 * @generated by @flusk/cli — otel-hook recipe
 * @flusk/otel — Auto-registration entry point
 *
 * Usage: node --require @flusk/otel ./index.js
 */

// --- BEGIN GENERATED ---
import { getLogger } from '@flusk/logger';
import { loadConfig } from './config.js';
import { createSdk } from './create-sdk.js';
import { setupAutoFlame } from './utils/auto-register-flame.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const logger = getLogger().child({ module: 'otel-register' });
const config = loadConfig();

// Start SDK synchronously (no top-level await — needed for --import compatibility)
const sdk = createSdk(config);
sdk.start();

// Async flame setup runs in background after SDK is already active
setupAutoFlame().then((spanProcessors) => {
  if (spanProcessors.length > 0) {
    logger.info(`Flame profiling enabled with ${spanProcessors.length} processor(s)`);
  }
}).catch((err: unknown) => {
  logger.warn({ err }, 'Flame auto-setup failed (non-fatal)');
});

process.on('SIGTERM', () => {
  sdk.shutdown().catch((err: unknown) => logger.error({ err }, 'shutdown failed'));
});

process.on('SIGINT', () => {
  sdk.shutdown().catch((err: unknown) => logger.error({ err }, 'shutdown failed'));
});

logger.info({ project: config.projectName }, 'instrumentation active');
// --- END CUSTOM ---
