# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/cost/aggregateCost.fn.yaml

def aggregate_cost(costs: list[float]) -> { total: float; count: float; average: float; min: float; max: float }:
    """Aggregate total cost from an array of individual call costs"""
    raise NotImplementedError("aggregate_cost — implement from YAML body")
