/**
 * Pipeline code generation — produces TypeScript pipeline and test files.
 */

import type { PipelineSchema } from './pipeline.types.js';
import { toKebab, toPascal, extractTypeImports } from './pipeline-helpers.js';
import { renderInputType, renderOutputType, renderStep, extractImports } from './pipeline-render.js';

/** Generate the full pipeline file */
export function generatePipelineCode(schema: PipelineSchema): string {
  const pascal = toPascal(schema.name);
  const inputType = renderInputType(schema.name, schema.input);
  const outputType = renderOutputType(schema.name, schema.output);
  const imports = extractImports(schema.steps);
  const typeImports = extractTypeImports(schema.input);
  const steps = schema.steps.map(renderStep).join('\n\n');

  return `/**
 * @generated by @flusk/forge — pipeline generator
 * ${schema.description}
 * Source: packages/schema/pipelines/${toKebab(schema.name)}.pipeline.yaml
 */

// --- BEGIN GENERATED (do not edit) ---
// @ts-nocheck — generated pipeline with dynamic expr: steps
import { getLogger } from '@flusk/logger';
${[...typeImports, ...imports].filter(Boolean).join('\n')}

const log = getLogger().child({ pipeline: '${schema.name}' });

${inputType}

${outputType}

export function ${schema.name}(input: ${pascal}Input): ${pascal}Output {
  log.debug({ pipeline: '${schema.name}' }, 'pipeline start');

${steps}
}
// --- END GENERATED ---
`;
}

/** Generate test file */
export function generatePipelineTest(schema: PipelineSchema): string {
  const pascal = toPascal(schema.name);
  const testCases = schema.tests || [];
  if (testCases.length === 0) {
    return `/**
 * @generated by @flusk/forge — pipeline generator (test)
 */
import { describe, it, expect } from 'vitest';
import { ${schema.name} } from '../${toKebab(schema.name)}.pipeline.js';

describe('${schema.name} pipeline', () => {
  it('should be defined', () => {
    expect(${schema.name}).toBeDefined();
  });
});
`;
  }

  const tests = testCases
    .map(
      (t) => `  it('${t.name}', () => {
    const result = ${schema.name}(${JSON.stringify(t.input)} as unknown as ${pascal}Input);
    expect(result).toEqual(${JSON.stringify(t.expected)});
  });`,
    )
    .join('\n\n');

  return `/**
 * @generated by @flusk/forge — pipeline generator (test)
 */
import { describe, it, expect } from 'vitest';
import { ${schema.name} } from '../${toKebab(schema.name)}.pipeline.js';
import type { ${pascal}Input } from '../${toKebab(schema.name)}.pipeline.js';

describe('${schema.name} pipeline', () => {
${tests}
});
`;
}
