/**
 * @generated by @flusk/cli — customize after generation
 * Root TUI App with keyboard navigation
 */

import React, { useState } from 'react';
// @ts-ignore ink types use exports field
import { render, Box, Text, useInput } from 'ink';
import { Header } from './components/header.js';
import { OverviewScreen } from './screens/overview.js';
import { BudgetScreen } from './screens/budget.js';
import { HistoryScreen } from './screens/history.js';
import { ModelsScreen } from './screens/models.js';
import { PatternsScreen } from './screens/patterns.js';
import { ProfileScreen } from './screens/profile.js';
import { SuggestionsScreen } from './screens/suggestions.js';

type Screen = 'overview' | 'budget' | 'history' | 'models' | 'patterns' | 'profile' | 'suggestions';

interface AppProps {
  endpoint: string;
  apiKey: string;
}

function App({ endpoint, apiKey }: AppProps) {
  const [screen, setScreen] = useState<Screen>('overview');

  useInput((input: string) => {
    if (input === '1') setScreen('overview');
    if (input === '2') setScreen('budget');
    if (input === '3') setScreen('history');
    if (input === '4') setScreen('models');
    if (input === '5') setScreen('patterns');
    if (input === '6') setScreen('profile');
    if (input === '7') setScreen('suggestions');
    if (input === 'q') process.exit(0);
  });

  return (
    <Box flexDirection="column">
      <Header endpoint={endpoint} />
      <Text dimColor>
        [1] Overview  [2] Budget  [3] History  [4] Models  [5] Patterns  [6] Profile  [7] Suggestions  [q] Quit
      </Text>
      <Box marginTop={1}>
        {screen === 'overview' && (
          <OverviewScreen endpoint={endpoint} apiKey={apiKey} />
        )}
        {screen === 'budget' && (
          <BudgetScreen endpoint={endpoint} apiKey={apiKey} />
        )}
        {screen === 'history' && (
          <HistoryScreen endpoint={endpoint} apiKey={apiKey} />
        )}
        {screen === 'models' && (
          <ModelsScreen endpoint={endpoint} apiKey={apiKey} />
        )}
        {screen === 'patterns' && (
          <PatternsScreen endpoint={endpoint} apiKey={apiKey} />
        )}
        {screen === 'profile' && (
          <ProfileScreen endpoint={endpoint} apiKey={apiKey} />
        )}
        {screen === 'suggestions' && (
          <SuggestionsScreen endpoint={endpoint} apiKey={apiKey} />
        )}
      </Box>
    </Box>
  );
}

export async function renderDashboard(
  opts: { endpoint: string; apiKey?: string },
) {
  render(<App endpoint={opts.endpoint} apiKey={opts.apiKey || ''} />);
}
