/**
 * @generated by @flusk/cli — barrel recipe
 */
// --- BEGIN GENERATED ---
/**
 * Barrel export for TUI module
 */

export { renderDashboard } from './app.js';
export * from './components/index.js';
export * from './hooks/index.js';
export * from './screens/index.js';
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
