/**
 * Template for generating repository files
 */

import { toPascalCase, toTableName } from '../generators/utils.js';

export function generateRepositoryTemplate(entityName: string): string {
  const pascalName = toPascalCase(entityName);
  const tableName = toTableName(entityName);

  return `/**
 * @generated by @flusk/cli from ${entityName}.entity.ts
 * DO NOT EDIT - regenerate using: flusk g ${entityName}.entity.ts
 */

import type { DatabaseSync } from 'node:sqlite';
import { ${pascalName}Entity } from '@flusk/entities';

/**
 * Convert database row to ${pascalName}Entity
 */
function rowToEntity(row: Record<string, unknown>): ${pascalName}Entity {
  return {
    id: String(row.id),
    createdAt: String(row.created_at),
    updatedAt: String(row.updated_at),
    // TODO: Add field mappings from schema
  } as ${pascalName}Entity;
}

/**
 * Create a new ${entityName} record
 */
export function create(
  db: DatabaseSync,
  data: Omit<${pascalName}Entity, 'id' | 'createdAt' | 'updatedAt'>
): ${pascalName}Entity {
  const id = crypto.randomUUID();
  const now = new Date().toISOString();
  // TODO: Add actual fields from schema
  const stmt = db.prepare(\\\`
    INSERT INTO ${tableName} (id, created_at, updated_at)
    VALUES (?, ?, ?)
  \\\`);

  stmt.run(id, now, now);
  return findById(db, id)!;
}

/**
 * Find ${entityName} by UUID
 */
export function findById(
  db: DatabaseSync,
  id: string
): ${pascalName}Entity | null {
  const stmt = db.prepare('SELECT * FROM ${tableName} WHERE id = ?');
  const row = stmt.get(id) as Record<string, unknown> | undefined;
  return row ? rowToEntity(row) : null;
}

/**
 * Update ${entityName} record
 */
export function update(
  db: DatabaseSync,
  id: string,
  _data: Partial<Omit<${pascalName}Entity, 'id' | 'createdAt' | 'updatedAt'>>
): ${pascalName}Entity | null {
  // TODO: Implement dynamic update logic
  const now = new Date().toISOString();
  const stmt = db.prepare(\\\`
    UPDATE ${tableName}
    SET updated_at = ?
    WHERE id = ?
  \\\`);

  stmt.run(now, id);
  return findById(db, id);
}
`;
}
