/**
 * @generated by @flusk/cli — tui recipe
 */
// --- BEGIN GENERATED ---
/**
 * TUI Component: Header — status bar with connection info
 */

import React from 'react';
// @ts-ignore ink types use exports field
import { Box, Text } from 'ink';

export interface HeaderProps {
  endpoint: string;
  connected?: boolean;
}

export function Header({ endpoint, connected = true }: HeaderProps) {
  return (
    <Box borderStyle="single" paddingX={1}>
      <Text bold color="#A3E635">[F]</Text><Text bold color="cyan"> Flusk Dashboard</Text>
      <Text> | </Text>
      <Text dimColor>{endpoint}</Text>
      <Text> | </Text>
      <Text color={connected ? 'green' : 'red'}>
        {connected ? '● Connected' : '○ Disconnected'}
      </Text>
    </Box>
  );
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
