/**
 * @generated by @flusk/cli — customize after generation
 * TUI Component: RateIndicator
 */

import React from 'react';
// @ts-ignore ink types use exports field
import { Box, Text } from 'ink';

export interface RateIndicatorProps {
  elapsedSec: number;
  totalCalls: number;
  callsPerMinute: number;
  costPerSecond: number;
}

export function RateIndicator({ elapsedSec, totalCalls, callsPerMinute, costPerSecond }: RateIndicatorProps) {
  const mins = Math.floor(elapsedSec / 60);
  const secs = Math.floor(elapsedSec % 60);
  return (
    <Box flexDirection="column">
      <Text bold>⏱ Rate</Text>
      <Text>  Elapsed:    <Text color="yellow">{mins}m {secs}s</Text></Text>
      <Text>  Calls:      <Text>{totalCalls}</Text></Text>
      <Text>  Calls/min:  <Text color="cyan">{callsPerMinute.toFixed(1)}</Text></Text>
      <Text>  $/sec:      <Text color="green">{costPerSecond.toFixed(6)}</Text></Text>
    </Box>
  );
}
