/**
 * @generated by @flusk/cli
 * TUI Screen: History — recent analysis sessions
 */

import React from 'react';
import { Box, Text } from 'ink';
import { useApi } from '../hooks/use-api.js';

interface SessionData {
  id: string;
  agent: string;
  startedAt: string;
  duration: number;
  totalCost: number;
  callCount: number;
}

export interface HistoryScreenProps {
  endpoint: string;
  apiKey: string;
}

export function HistoryScreen({ endpoint, apiKey }: HistoryScreenProps) {
  const sessions = useApi<SessionData[]>(endpoint, '/api/v1/sessions', apiKey);

  if (sessions.loading) return <Text>Loading history...</Text>;
  if (sessions.error) return <Text color="red">Error: {sessions.error}</Text>;
  const data = sessions.data || [];
  if (data.length === 0) return <Text dimColor>No sessions yet</Text>;

  return (
    <Box flexDirection="column">
      <Text bold color="cyan">Analysis History</Text>
      <Box marginTop={1} flexDirection="column">
        {data.slice(0, 10).map((s) => (
          <Box key={s.id}>
            <Text dimColor>{new Date(s.startedAt).toLocaleString().padEnd(22)}</Text>
            <Text color="yellow">{s.agent.padEnd(20)}</Text>
            <Text>{String(s.callCount).padStart(5)} calls </Text>
            <Text bold color="green">${s.totalCost.toFixed(2)}</Text>
          </Box>
        ))}
      </Box>
    </Box>
  );
}
