/**
 * @generated by @flusk/cli — barrel recipe
 */
// --- BEGIN GENERATED ---
/**
 * Barrel export for TUI screens
 */

export { OverviewScreen } from './overview.js';
export { PatternsScreen } from './patterns.js';
export { SuggestionsScreen } from './suggestions.js';
export { ProfileScreen } from './profile.js';
export { BudgetScreen } from './budget.js';
export { ModelsScreen } from './models.js';
export { HistoryScreen } from './history.js';
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
export { WatchScreen } from './watch-screen.js';
export type { WatchScreenProps } from './watch-screen.js';
export { renderWatchApp } from './watch-app.js';
// --- END CUSTOM ---
