/**
 * @generated by @flusk/cli — customized
 * TUI Screen: Profile — session list, detail, correlations
 */

import React, { useState, useEffect } from 'react';
// @ts-ignore ink types use exports field
import { Box, Text, useInput } from 'ink';
import { useProfiles } from '../hooks/use-profiles.js';
import type { CorrelationData } from '../hooks/use-profiles.js';

export interface ProfileScreenProps {
  endpoint: string;
  apiKey: string;
}

type View = 'list' | 'detail' | 'correlations';

export function ProfileScreen({ endpoint, apiKey }: ProfileScreenProps) {
  const { profiles, loading, error, fetchCorrelations } = useProfiles(endpoint, apiKey);
  const [selected, setSelected] = useState(0);
  const [view, setView] = useState<View>('list');
  const [corrData, setCorrData] = useState<CorrelationData | null>(null);

  useInput((input: string, key: any) => {
    if (view === 'list') {
      if (key.upArrow) setSelected((s) => Math.max(0, s - 1));
      if (key.downArrow) setSelected((s) => Math.min(profiles.length - 1, s + 1));
      if (key.return) setView('detail');
      if (input === 'c') loadCorrelations();
    } else if (input === 'q') {
      setView('list');
      setCorrData(null);
    }
  });

  const loadCorrelations = async () => {
    if (!profiles[selected]) return;
    const data = await fetchCorrelations(profiles[selected].id);
    setCorrData(data);
    setView('correlations');
  };

  if (loading) return <Text>Loading profiles...</Text>;
  if (error) return <Text color="red">Error: {error}</Text>;
  if (!profiles.length) return <Text color="yellow">No profiles found.</Text>;

  const current = profiles[selected];

  if (view === 'detail') return (
    <Box flexDirection="column">
      <Text bold color="blue">🔥 {current.name}</Text>
      <Text dimColor>Type: {current.type} | {current.durationMs}ms | {current.totalSamples} samples</Text>
      <Text bold>Hotspots</Text>
      {(current.hotspots || []).slice(0, 8).map((h, i) => (
        <Text key={i}>  {'█'.repeat(Math.round(h.percentage / 5))} {h.percentage.toFixed(1)}% {h.functionName.slice(0, 40)}</Text>
      ))}
      <Text dimColor>[c] correlations  [q] back</Text>
    </Box>
  );

  if (view === 'correlations') return (
    <Box flexDirection="column">
      <Text bold color="cyan">🔗 Correlations: {current.name}</Text>
      {corrData?.correlations.length ? corrData.correlations.map((c, i) => (
        <Text key={i}>  {c.model} — {c.durationMs}ms — ${c.cost.toFixed(4)}</Text>
      )) : <Text dimColor>  No correlated LLM calls.</Text>}
      {corrData?.suggestions?.map((s, i) => <Text key={`s${i}`} color="yellow">  💡 {s}</Text>)}
      <Text dimColor>[q] back</Text>
    </Box>
  );

  return (
    <Box flexDirection="column">
      <Text bold underline>Profile Sessions</Text>
      {profiles.slice(0, 15).map((p, i) => (
        <Text key={p.id} color={i === selected ? 'blue' : undefined} bold={i === selected}>
          {i === selected ? '▸' : ' '} {p.id.slice(0, 8)} {p.name.slice(0, 20).padEnd(22)} {p.type} {p.durationMs}ms
        </Text>
      ))}
      <Text dimColor>↑↓ select  ⏎ detail  [c] correlations  [q] quit</Text>
    </Box>
  );
}
