/**
 * @generated by @flusk/cli — customize after generation
 * TUI Screen: WatchApp — render entry point
 */

import React from 'react';
// @ts-ignore ink types use exports field
import { render } from 'ink';
import { WatchScreen } from './watch-screen.js';
import type { StorageAdapter } from '@flusk/resources';
import type { ChildProcess } from 'node:child_process';

interface WatchAppOpts {
  sessionId: string;
  storage: StorageAdapter;
  child: ChildProcess;
}

export function renderWatchApp(opts: WatchAppOpts): void {
  const { sessionId, storage, child } = opts;
  const app = render(<WatchScreen sessionId={sessionId} storage={storage} />);

  child.on('exit', () => {
    // Keep TUI alive so user can review final state; 'q' to quit
  });
}
