/**
 * @generated by @flusk/cli — provider generator
 */
import { describe, it, expect } from 'vitest';
import { patchAnthropic } from './anthropic.js';

describe('anthropic instrumentation', () => {
  it('exports patch function', () => {
    expect(typeof patchAnthropic).toBe('function');
  });

  it('does not throw when sdk is missing', () => {
    expect(() => patchAnthropic()).not.toThrow();
  });
});
