/**
 * @generated by @flusk/cli — provider generator
 * Google AI (Gemini) SDK instrumentation — gen_ai.* spans
 */
import { trace, SpanKind, SpanStatusCode, context } from '@opentelemetry/api';

const TRACER_NAME = 'flusk-google';

export function patchGoogle(): void {
  try {
    import('@google/generative-ai').then((mod) => {
      const Sdk = mod.default || mod;
      patchMethod(Sdk);
    }).catch(() => { /* sdk not installed */ });
  } catch { /* ignore */ }
}

// --- BEGIN CUSTOM --- Google SDK: model on instance, separate stream method
function patchMethod(Sdk: any): void {
  const proto = Sdk?.GenerativeModel?.prototype;
  if (!proto || proto.__flusk_patched) return;
  patchGenerate(proto);
  patchStream(proto);
  proto.__flusk_patched = true;
}

function patchGenerate(proto: any): void {
  const original = proto.generateContent;
  if (typeof original !== 'function') return;
  proto.generateContent = function patched(this: any, ...args: any[]) {
    const tracer = trace.getTracer(TRACER_NAME);
    const model = this.model || 'unknown';
    return tracer.startActiveSpan(
      `google ${model}`,
      { kind: SpanKind.CLIENT },
      context.active(),
      async (span) => {
        span.setAttribute('gen_ai.system', 'google');
        span.setAttribute('gen_ai.request.model', model);
        try {
          const result = await original.apply(this, args);
          setResponseAttrs(span, result);
          span.setStatus({ code: SpanStatusCode.OK });
          span.end();
          return result;
        } catch (err: any) {
          span.setStatus({ code: SpanStatusCode.ERROR, message: err?.message });
          span.end();
          throw err;
        }
      },
    );
  };
}

function patchStream(proto: any): void {
  const original = proto.generateContentStream;
  if (typeof original !== 'function') return;
  proto.generateContentStream = function patched(this: any, ...args: any[]) {
    const tracer = trace.getTracer(TRACER_NAME);
    const model = this.model || 'unknown';
    return tracer.startActiveSpan(
      `google ${model}`,
      { kind: SpanKind.CLIENT },
      context.active(),
      async (span) => {
        span.setAttribute('gen_ai.system', 'google');
        span.setAttribute('gen_ai.request.model', model);
        try {
          const result = await original.apply(this, args);
          return wrapStream(result, span);
        } catch (err: any) {
          span.setStatus({ code: SpanStatusCode.ERROR, message: err?.message });
          span.end();
          throw err;
        }
      },
    );
  };
}
// --- END CUSTOM ---

// --- BEGIN CUSTOM --- Google SDK: usageMetadata with promptTokenCount/candidatesTokenCount
function wrapStream(result: any, span: any): any {
  let inputTokens = 0, outputTokens = 0;
  const stream = result.stream ?? result;
  if (!stream?.[Symbol.asyncIterator]) { span.end(); return result; }
  const orig = stream[Symbol.asyncIterator].bind(stream);
  stream[Symbol.asyncIterator] = async function* () {
    for await (const chunk of orig()) {
      const u = chunk.usageMetadata;
      if (u) {
        inputTokens = u.promptTokenCount ?? 0;
        outputTokens = u.candidatesTokenCount ?? 0;
      }
      yield chunk;
    }
    span.setAttribute('gen_ai.usage.input_tokens', inputTokens);
    span.setAttribute('gen_ai.usage.output_tokens', outputTokens);
    span.setStatus({ code: SpanStatusCode.OK });
    span.end();
  };
  return result;
}

function setResponseAttrs(span: any, result: any): void {
  const resp = result?.response ?? result;
  if (resp?.modelVersion) span.setAttribute('gen_ai.response.model', resp.modelVersion);
  const u = resp?.usageMetadata;
  if (u) {
    span.setAttribute('gen_ai.usage.input_tokens', u.promptTokenCount ?? 0);
    span.setAttribute('gen_ai.usage.output_tokens', u.candidatesTokenCount ?? 0);
  }
}
// --- END CUSTOM ---
