/**
 * @generated by @flusk/cli — provider generator
 */
import { describe, it, expect } from 'vitest';
import { patchGoogle } from './google.js';

describe('google instrumentation', () => {
  it('exports patch function', () => {
    expect(typeof patchGoogle).toBe('function');
  });

  it('does not throw when sdk is missing', () => {
    expect(() => patchGoogle()).not.toThrow();
  });
});
