/**
 * @generated by @flusk/cli — client recipe
 * FluskClient — HTTP client for Flusk API
 */

// --- BEGIN GENERATED ---
export type {
  FluskClientConfig,
  ConversionSuggestion,
  OptimizationSuggestion,
  RouteOptions,
  RouteResult,
} from './client.types.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
import type {
  FluskClientConfig,
  ConversionSuggestion,
  OptimizationSuggestion,
  RouteOptions,
  RouteResult,
} from './client.types.js';

export class FluskClient {
  private readonly apiKey: string
  private readonly baseUrl: string

  constructor(config: FluskClientConfig) {
    this.apiKey = config.apiKey
    this.baseUrl = config.baseUrl || 'https://api.flusk.ai'
  }

  private authHeaders(extra?: Record<string, string>): Record<string, string> {
    return { Authorization: `Bearer ${this.apiKey}`, ...extra }
  }

  private jsonHeaders(): Record<string, string> {
    return this.authHeaders({ 'Content-Type': 'application/json' })
  }

  private async fetchOrThrow<T>(url: string, init: RequestInit, label: string): Promise<T> {
    const maxRetries = 3;
    const timeoutMs = 30_000;
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), timeoutMs);
      try {
        const response = await fetch(url, { ...init, signal: controller.signal });
        clearTimeout(timer);
        if (response.status >= 500 && attempt < maxRetries) {
          await new Promise(r => setTimeout(r, Math.min(1000 * 2 ** attempt, 8000)));
          continue;
        }
        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(`${label} failed: ${response.status} ${errorText}`);
        }
        return response.json() as Promise<T>;
      } catch (err) {
        clearTimeout(timer);
        if (attempt < maxRetries && (err instanceof Error && (err.name === 'AbortError' || err.message.includes('fetch')))) {
          await new Promise(r => setTimeout(r, Math.min(1000 * 2 ** attempt, 8000)));
          continue;
        }
        throw err;
      }
    }
    throw new Error(`${label} failed after ${maxRetries} retries`);
  }

  async getSuggestions(organizationId?: string): Promise<ConversionSuggestion[]> {
    const url = new URL(`${this.baseUrl}/api/v1/conversions/suggestions`)
    if (organizationId) url.searchParams.set('organizationId', organizationId)
    return this.fetchOrThrow(url.toString(), { method: 'GET', headers: this.authHeaders() }, 'getSuggestions')
  }

  async getOptimizations(): Promise<OptimizationSuggestion[]> {
    return this.fetchOrThrow(`${this.baseUrl}/api/v1/optimizations/generate`, {
      method: 'POST', headers: this.jsonHeaders(), body: JSON.stringify({}),
    }, 'getOptimizations')
  }

  async getOptimizationCode(id: string): Promise<{ code: string; language: string }> {
    return this.fetchOrThrow(`${this.baseUrl}/api/v1/optimizations/${id}/code`, {
      method: 'GET', headers: this.authHeaders(),
    }, 'getOptimizationCode')
  }

  async renderPrompt(
    templateId: string,
    variables: Record<string, string>,
    abTest?: { candidateVersionId: string; trafficPercent: number }
  ): Promise<{ rendered: string; versionId: string; isCandidate?: boolean }> {
    const url = abTest
      ? `${this.baseUrl}/api/v1/prompt-templates/${templateId}/ab-test`
      : `${this.baseUrl}/api/v1/prompt-templates/${templateId}/render`
    const body = abTest ? { ...abTest, variables } : { variables }
    return this.fetchOrThrow(url, {
      method: 'POST', headers: this.jsonHeaders(), body: JSON.stringify(body),
    }, 'renderPrompt')
  }

  async reportPromptMetrics(
    versionId: string,
    metrics: { quality: number; latencyMs: number; cost: number }
  ): Promise<void> {
    const response = await fetch(`${this.baseUrl}/api/v1/prompt-versions/${versionId}/metrics`, {
      method: 'PATCH', headers: this.jsonHeaders(), body: JSON.stringify(metrics),
    })
    if (!response.ok) throw new Error(`reportPromptMetrics failed: ${response.status} ${await response.text()}`)
  }

  async route(options: RouteOptions): Promise<RouteResult> {
    return this.fetchOrThrow(`${this.baseUrl}/api/v1/route`, {
      method: 'POST', headers: this.jsonHeaders(), body: JSON.stringify(options),
    }, 'Routing')
  }
}
// --- END CUSTOM ---
