/**
 * @generated by @flusk/cli — client recipe
 * FluskClient — HTTP client for Flusk API
 */

// --- BEGIN GENERATED ---
export type {
  FluskClientConfig,
  ConversionSuggestion,
  OptimizationSuggestion,
  RouteOptions,
  RouteResult,
} from './client.types.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
import type {
  FluskClientConfig,
  ConversionSuggestion,
  OptimizationSuggestion,
  RouteOptions,
  RouteResult,
} from './client.types.js';

export class FluskClient {
  private readonly apiKey: string
  private readonly baseUrl: string
  private readonly timeoutMs: number
  private readonly maxRetries: number

  constructor(config: FluskClientConfig) {
    this.apiKey = config.apiKey
    this.baseUrl = config.baseUrl || 'https://api.flusk.ai'
    this.timeoutMs = config.timeoutMs ?? 30_000
    this.maxRetries = config.maxRetries ?? 3
  }

  private authHeaders(extra?: Record<string, string>): Record<string, string> {
    return { Authorization: `Bearer ${this.apiKey}`, ...extra }
  }

  private jsonHeaders(): Record<string, string> {
    return this.authHeaders({ 'Content-Type': 'application/json' })
  }

  private async fetchOrThrow<T>(url: string, init: RequestInit, label: string): Promise<T> {
    let lastError: Error | undefined
    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {
      try {
        const controller = new AbortController()
        const timer = setTimeout(() => controller.abort(), this.timeoutMs)
        const response = await fetch(url, { ...init, signal: controller.signal })
        clearTimeout(timer)
        if (response.status >= 500 && attempt < this.maxRetries) {
          lastError = new Error(`${label} failed: ${response.status}`)
          await new Promise((r) => setTimeout(r, Math.min(1000 * 2 ** attempt, 10_000)))
          continue
        }
        if (!response.ok) {
          const errorText = await response.text()
          throw new Error(`${label} failed: ${response.status} ${errorText}`)
        }
        return response.json() as Promise<T>
      } catch (err) {
        lastError = err as Error
        if ((err as Error).name === 'AbortError') {
          lastError = new Error(`${label} timed out after ${this.timeoutMs}ms`)
        }
        if (attempt < this.maxRetries) {
          await new Promise((r) => setTimeout(r, Math.min(1000 * 2 ** attempt, 10_000)))
          continue
        }
      }
    }
    throw lastError ?? new Error(`${label} failed after ${this.maxRetries} retries`)
  }

  async getSuggestions(organizationId?: string): Promise<ConversionSuggestion[]> {
    const url = new URL(`${this.baseUrl}/api/v1/conversions/suggestions`)
    if (organizationId) url.searchParams.set('organizationId', organizationId)
    return this.fetchOrThrow(url.toString(), { method: 'GET', headers: this.authHeaders() }, 'getSuggestions')
  }

  async getOptimizations(): Promise<OptimizationSuggestion[]> {
    return this.fetchOrThrow(`${this.baseUrl}/api/v1/optimizations/generate`, {
      method: 'POST', headers: this.jsonHeaders(), body: JSON.stringify({}),
    }, 'getOptimizations')
  }

  async getOptimizationCode(id: string): Promise<{ code: string; language: string }> {
    return this.fetchOrThrow(`${this.baseUrl}/api/v1/optimizations/${id}/code`, {
      method: 'GET', headers: this.authHeaders(),
    }, 'getOptimizationCode')
  }

  async renderPrompt(
    templateId: string,
    variables: Record<string, string>,
    abTest?: { candidateVersionId: string; trafficPercent: number }
  ): Promise<{ rendered: string; versionId: string; isCandidate?: boolean }> {
    const url = abTest
      ? `${this.baseUrl}/api/v1/prompt-templates/${templateId}/ab-test`
      : `${this.baseUrl}/api/v1/prompt-templates/${templateId}/render`
    const body = abTest ? { ...abTest, variables } : { variables }
    return this.fetchOrThrow(url, {
      method: 'POST', headers: this.jsonHeaders(), body: JSON.stringify(body),
    }, 'renderPrompt')
  }

  async reportPromptMetrics(
    versionId: string,
    metrics: { quality: number; latencyMs: number; cost: number }
  ): Promise<void> {
    const response = await fetch(`${this.baseUrl}/api/v1/prompt-versions/${versionId}/metrics`, {
      method: 'PATCH', headers: this.jsonHeaders(), body: JSON.stringify(metrics),
    })
    if (!response.ok) throw new Error(`reportPromptMetrics failed: ${response.status} ${await response.text()}`)
  }

  async route(options: RouteOptions): Promise<RouteResult> {
    return this.fetchOrThrow(`${this.baseUrl}/api/v1/route`, {
      method: 'POST', headers: this.jsonHeaders(), body: JSON.stringify(options),
    }, 'Routing')
  }
}
// --- END CUSTOM ---
