# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/math/percentage.fn.yaml

def percentage(part: float, total: float) -> float:
    """Calculate what percentage part is of total"""
    raise NotImplementedError("percentage — implement from YAML body")
