# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/time/formatDuration.fn.yaml

def format_duration(ms: float) -> str:
    """Format a duration in milliseconds to a human-readable string"""
    raise NotImplementedError("format_duration — implement from YAML body")
