# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/time/timeBucket.fn.yaml

def time_bucket(timestamp: str, bucket: str | str | str) -> str:
    """Round a timestamp down to the nearest bucket (minute, hour, day)"""
    raise NotImplementedError("time_bucket — implement from YAML body")
