/**
 * @generated by @flusk/cli — business-logic recipe
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export interface ToolCallEntry {
  name: string;
  arguments: string;
  id?: string;
  type?: string;
}

export interface EmbeddingInfo {
  dimensions: number;
  model: string;
  count: number;
}

export interface ExtractToolCallsInput {
  responseBody: Record<string, unknown>;
}

export interface ExtractToolCallsOutput {
  toolCalls: ToolCallEntry[];
  embedding: EmbeddingInfo | null;
}

/**
 * Extract tool/function calls and embedding info from LLM
 * API response bodies. Supports OpenAI and Anthropic formats.
 */
export function extractToolCalls(
  input: ExtractToolCallsInput
): ExtractToolCallsOutput {
  const { responseBody } = input;
  const toolCalls: ToolCallEntry[] = [];
  let embedding: EmbeddingInfo | null = null;

  // OpenAI chat completion format
  const choices = responseBody.choices as
    | Array<Record<string, unknown>>
    | undefined;
  if (choices?.[0]) {
    const msg = choices[0].message as Record<string, unknown> | undefined;
    const calls = msg?.tool_calls as
      | Array<Record<string, unknown>>
      | undefined;
    if (calls) {
      for (const tc of calls) {
        const fn = tc.function as Record<string, string> | undefined;
        toolCalls.push({
          name: fn?.name ?? String(tc.name ?? ''),
          arguments: fn?.arguments ?? '',
          id: tc.id as string | undefined,
          type: tc.type as string | undefined,
        });
      }
    }
  }

  // Anthropic tool_use blocks
  const content = responseBody.content as
    | Array<Record<string, unknown>>
    | undefined;
  if (content) {
    for (const block of content) {
      if (block.type === 'tool_use') {
        toolCalls.push({
          name: block.name as string,
          arguments: JSON.stringify(block.input ?? {}),
          id: block.id as string | undefined,
          type: 'tool_use',
        });
      }
    }
  }

  // OpenAI embedding response
  const data = responseBody.data as
    | Array<Record<string, unknown>>
    | undefined;
  if (data?.[0]?.embedding) {
    const emb = data[0].embedding as number[];
    embedding = {
      dimensions: emb.length,
      model: (responseBody.model as string) ?? '',
      count: data.length,
    };
  }

  return { toolCalls, embedding };
}
// --- END CUSTOM ---
