/**
 * @generated by @flusk/cli — function generator
 */
// --- BEGIN CUSTOM ---
import { createHash } from 'node:crypto';

/**
 * Normalize a prompt for fuzzy deduplication:
 * strip whitespace, lowercase, remove numbers.
 */
export function normalizePrompt(text: string): string {
  return text
    .toLowerCase()
    .replace(/\d+/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Generate a fuzzy hash for prompt deduplication.
 * Normalizes the prompt before hashing.
 */
export function fuzzyHashPrompt(promptText: string, modelName: string): string {
  const normalized = normalizePrompt(promptText);
  const combined = `${modelName}:${normalized}`;
  return createHash('sha256').update(combined, 'utf8').digest('hex');
}
// --- END CUSTOM ---
