/**
 * @generated by @flusk/cli — business-logic recipe
 */

// --- BEGIN GENERATED ---
import { createHash } from 'node:crypto';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export interface NormalizePromptHashInput {
  promptText: string;
  modelName: string;
}

export interface NormalizePromptHashOutput {
  normalizedHash: string;
  exactHash: string;
}

const TIMESTAMP_PATTERNS = [
  /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[.\d]*Z?/g,
  /\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/g,
  /\d{1,2}\/\d{1,2}\/\d{2,4}/g,
  /\b\d{10,13}\b/g,
];

/**
 * Normalize prompt text for fuzzy matching.
 * Strips whitespace variations, normalizes casing,
 * and removes timestamps before hashing.
 */
export function normalizeText(text: string): string {
  let normalized = text;
  for (const pattern of TIMESTAMP_PATTERNS) {
    normalized = normalized.replace(pattern, '<TIMESTAMP>');
  }
  normalized = normalized.toLowerCase().replace(/\s+/g, ' ').trim();
  return normalized;
}

/**
 * Generate both exact and normalized SHA-256 hashes for
 * prompt deduplication with fuzzy matching support.
 *
 * @param input - Prompt text and model name
 * @returns Both exact and normalized hashes
 */
export function normalizePromptHash(
  input: NormalizePromptHashInput
): NormalizePromptHashOutput {
  const exactCombined = `${input.modelName}:${input.promptText}`;
  const exactHash = createHash('sha256')
    .update(exactCombined, 'utf8')
    .digest('hex');

  const normalizedText = normalizeText(input.promptText);
  const normalizedCombined = `${input.modelName.toLowerCase()}:${normalizedText}`;
  const normalizedHash = createHash('sha256')
    .update(normalizedCombined, 'utf8')
    .digest('hex');

  return { normalizedHash, exactHash };
}
// --- END CUSTOM ---
