/**
 * @generated by @flusk/cli from llm-call.entity.ts
 * Business logic stub - implement your domain logic here
 */

import { LLMCallEntity } from '@flusk/types';

/**
 * Example validation function for LLMCall
 * Pure function - no side effects, no I/O
 */
export function validateLLMCall(
  _entity: Partial<LLMCallEntity>
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  // TODO: Add validation logic
  // Example:
  // if (!_entity.someField) {
  //   errors.push('someField is required');
  // }

  return {
    valid: errors.length === 0,
    errors
  };
}
