/**
 * @generated by @flusk/cli — business-logic recipe
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export type ImageDetail = 'low' | 'high' | 'auto';

export interface VisionTokenInput {
  width: number;
  height: number;
  detail?: ImageDetail;
}

export interface VisionTokenOutput {
  tokens: number;
  tiles: number;
  detail: ImageDetail;
}

const TILE_SIZE = 512;
const LOW_DETAIL_TOKENS = 85;
const TOKENS_PER_TILE = 170;
const BASE_TOKENS = 85;
const MAX_DIMENSION = 2048;
const SHORT_SIDE_TARGET = 768;

/**
 * Estimate token count for image inputs using OpenAI's formula:
 * - Low detail: fixed 85 tokens
 * - High detail: tiles * 170 + 85 base
 *   (scale longest side to 2048, shortest to 768, count 512x512 tiles)
 */
export function estimateVisionTokens(
  input: VisionTokenInput
): VisionTokenOutput {
  const detail = input.detail ?? 'auto';

  if (detail === 'low') {
    return { tokens: LOW_DETAIL_TOKENS, tiles: 0, detail: 'low' };
  }

  let { width, height } = input;

  const resolvedDetail: ImageDetail =
    detail === 'auto' && width <= TILE_SIZE && height <= TILE_SIZE
      ? 'low'
      : 'high';

  if (resolvedDetail === 'low') {
    return { tokens: LOW_DETAIL_TOKENS, tiles: 0, detail: 'low' };
  }

  if (width > MAX_DIMENSION || height > MAX_DIMENSION) {
    const scale = MAX_DIMENSION / Math.max(width, height);
    width = Math.floor(width * scale);
    height = Math.floor(height * scale);
  }

  const shortest = Math.min(width, height);
  if (shortest > SHORT_SIDE_TARGET) {
    const scale = SHORT_SIDE_TARGET / shortest;
    width = Math.floor(width * scale);
    height = Math.floor(height * scale);
  }

  const tilesW = Math.ceil(width / TILE_SIZE);
  const tilesH = Math.ceil(height / TILE_SIZE);
  const tiles = tilesW * tilesH;

  return {
    tokens: tiles * TOKENS_PER_TILE + BASE_TOKENS,
    tiles,
    detail: resolvedDetail,
  };
}
// --- END CUSTOM ---
