/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { Pool } from 'pg';
import { ConversionEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';
import { findById } from './find-by-id.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
/**
 * Update conversion record
 * @param pool - PostgreSQL connection pool
 * @param id - UUID of the conversion to update
 * @param data - Partial data to update
 */
export async function update(
  pool: Pool,
  id: string,
  data: Partial<Omit<ConversionEntity, 'id' | 'createdAt' | 'updatedAt'>>
): Promise<ConversionEntity | null> {
  const updates: string[] = [];
  const values: unknown[] = [];
  let paramCount = 1;

  if (data.patternId !== undefined) {
    updates.push(`pattern_id = $${paramCount++}`);
    values.push(data.patternId);
  }
  if (data.organizationId !== undefined) {
    updates.push(`organization_id = $${paramCount++}`);
    values.push(data.organizationId);
  }
  if (data.conversionType !== undefined) {
    updates.push(`conversion_type = $${paramCount++}`);
    values.push(data.conversionType);
  }
  if (data.status !== undefined) {
    updates.push(`status = $${paramCount++}`);
    values.push(data.status);
  }
  if (data.estimatedSavings !== undefined) {
    updates.push(`estimated_savings = $${paramCount++}`);
    values.push(data.estimatedSavings);
  }
  if (data.config !== undefined) {
    updates.push(`config = $${paramCount++}`);
    values.push(JSON.stringify(data.config));
  }

  if (updates.length === 0) {
    return findById(pool, id);
  }

  values.push(id);
  const query = `
    UPDATE conversions
    SET ${updates.join(', ')}, updated_at = NOW()
    WHERE id = $${paramCount}
    RETURNING *
  `;

  const result = await pool.query(query, values);

  if (result.rows.length === 0) {
    return null;
  }

  return rowToEntity(result.rows[0]);
}
// --- END CUSTOM ---
