/**
 * @generated by @flusk/cli — provider generator
 */
import { describe, it, expect } from 'vitest';
import { ANTHROPIC_PRICING } from './anthropic.pricing.js';
import { ANTHROPIC_SYSTEM_VALUES, ANTHROPIC_MODEL_PREFIXES } from './anthropic.span-config.js';

describe('anthropic provider', () => {
  it('has pricing for all known models', () => {
    const expected = [
    'claude-sonnet-4-20250514',
    'claude-opus-4-20250514',
    'claude-haiku-3.5',
    ];
    for (const m of expected) {
      expect(ANTHROPIC_PRICING[m]).toBeDefined();
    }
  });

  it('has system values', () => {
    expect(ANTHROPIC_SYSTEM_VALUES.length).toBeGreaterThan(0);
  });

  it('has model prefixes', () => {
    expect(ANTHROPIC_MODEL_PREFIXES.length).toBeGreaterThan(0);
  });
});
