/**
 * @generated by @flusk/cli — provider generator
 * Cohere pricing (USD per 1M tokens)
 */

export const COHERE_PRICING: Record<string, { input: number; output: number }> = {
  'command-r-plus': { input: 2.5, output: 10 },
  'command-r': { input: 0.5, output: 1.5 },
  'command': { input: 1, output: 2 },
  'command-light': { input: 0.3, output: 0.6 },
  'embed-english-v3.0': { input: 0.1, output: 0 },
  'embed-multilingual-v3.0': { input: 0.1, output: 0 },
  'rerank-english-v3.0': { input: 1, output: 0 },
};
