/**
 * @generated by @flusk/cli — provider generator
 * OpenAI span detection config
 */

export const OPENAI_SYSTEM_VALUES = [
  'openai',
];

export const OPENAI_MODEL_PREFIXES = [
  'gpt-',
  'o1-',
  'o3-',
  'o4-',
];
