"use strict";
/**
 * @generated by @flusk/cli — barrel recipe
 */
// --- BEGIN GENERATED ---
/**
 * Infrastructure management commands
 * Export all infra subcommands
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.infraCommand = void 0;
var commander_1 = require("commander");
var up_command_js_1 = require("./up.command.js");
var down_command_js_1 = require("./down.command.js");
var reset_command_js_1 = require("./reset.command.js");
var logs_command_js_1 = require("./logs.command.js");
var status_command_js_1 = require("./status.command.js");
exports.infraCommand = new commander_1.Command('infra')
    .description('Manage Docker infrastructure services')
    .addCommand(up_command_js_1.upCommand)
    .addCommand(down_command_js_1.downCommand)
    .addCommand(reset_command_js_1.resetCommand)
    .addCommand(logs_command_js_1.logsCommand)
    .addCommand(status_command_js_1.statusCommand);
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
