/** @generated —
 * Template for generating Fastify middleware files
 */

import { toPascalCase, toCamelCase } from '../../generators/utils.js';

export function generateMiddlewareTemplate(middlewareName: string): string {
  const pascalName = toPascalCase(middlewareName);
  const camelName = toCamelCase(middlewareName);

  return `/**
 * @generated by @flusk/cli
 * ${pascalName} Middleware
 */

import { FastifyRequest, FastifyReply, HookHandlerDoneFunction } from 'fastify';

export interface ${pascalName}MiddlewareOptions {
  // Add middleware configuration options here
  enabled?: boolean;
}

/**
 * ${pascalName} middleware
 *
 * Usage:
 * \`\`\`typescript
 * // In your route or plugin:
 * fastify.addHook('preHandler', ${camelName}Middleware({ enabled: true }));
 * \`\`\`
 */
export function ${camelName}Middleware(options: ${pascalName}MiddlewareOptions = {}) {
  const { enabled = true } = options;

  return async function ${camelName}Hook(
    request: FastifyRequest,
    reply: FastifyReply,
    done: HookHandlerDoneFunction
  ) {
    if (!enabled) {
      done();
      return;
    }

    try {
      // TODO: Implement middleware logic
      request.log.debug('${pascalName} middleware executed');

      done();
    } catch (error) {
      done(error as Error);
    }
  };
}
`;
}

export function generateMiddlewareTestTemplate(middlewareName: string): string {
  const pascalName = toPascalCase(middlewareName);
  const camelName = toCamelCase(middlewareName);

  return `/**
 * @generated by @flusk/cli
 * Tests for ${pascalName} Middleware
 */

import { describe, it, expect, vi } from 'vitest';
import { FastifyRequest, FastifyReply } from 'fastify';
import { ${camelName}Middleware } from './${middlewareName}.middleware.js';

describe('${pascalName} Middleware', () => {
  it('should execute middleware when enabled', async () => {
    // Arrange
    const middleware = ${camelName}Middleware({ enabled: true });
    const request = {
      log: { debug: vi.fn() }
    } as unknown as FastifyRequest;
    const reply = {} as FastifyReply;
    const done = vi.fn();

    // Act
    await middleware(request, reply, done);

    // Assert
    expect(done).toHaveBeenCalledOnce();
    expect(request.log.debug).toHaveBeenCalled();
  });

  it('should skip middleware when disabled', async () => {
    // Arrange
    const middleware = ${camelName}Middleware({ enabled: false });
    const request = {
      log: { debug: vi.fn() }
    } as unknown as FastifyRequest;
    const reply = {} as FastifyReply;
    const done = vi.fn();

    // Act
    await middleware(request, reply, done);

    // Assert
    expect(done).toHaveBeenCalledOnce();
    expect(request.log.debug).not.toHaveBeenCalled();
  });

  it('should handle errors gracefully', async () => {
    // Arrange
    const middleware = ${camelName}Middleware({ enabled: true });
    const request = {
      log: {
        debug: vi.fn(() => { throw new Error('Test error'); })
      }
    } as unknown as FastifyRequest;
    const reply = {} as FastifyReply;
    const done = vi.fn();

    // Act
    await middleware(request, reply, done);

    // Assert
    expect(done).toHaveBeenCalledWith(expect.any(Error));
  });
});
`;
}
