/**
 * @generated by @flusk/cli — otel-hook recipe
 * Auto-detection of @platformatic/flame availability
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
let cached: boolean | null = null;

export async function isFlameAvailable(): Promise<boolean> {
  if (cached !== null) return cached;

  try {
    await import('@platformatic/flame');
    cached = true;
  } catch {
    cached = false;
  }

  return cached;
}

/** Reset cache — used in tests */
export function resetFlameDetectionCache(): void {
  cached = null;
}
// --- END CUSTOM ---
