/**
 * @generated by @flusk/cli — otel-hook recipe
 * Resolve the correct span exporter based on FLUSK_MODE.
 */

// --- BEGIN GENERATED ---
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import type { SpanExporter } from '@opentelemetry/sdk-trace-base';
import { SqliteSpanExporter } from '../exporters/sqlite-exporter.js';
import { createLogger } from '@flusk/logger';
import type { FluskOtelConfig } from '../config.js';

const log = createLogger('resolve-exporter');

export type FluskMode = 'local' | 'server';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
import { createOtlpExporter } from '../exporters/otlp-exporter.js';
import { MultiSpanExporter } from '../exporters/multi-exporter.js';

export function resolveMode(): FluskMode {
  const explicit = process.env['FLUSK_MODE'];
  if (explicit === 'server') return 'server';
  if (explicit === 'local') return 'local';
  return process.env['FLUSK_ENDPOINT'] ? 'server' : 'local';
}

export function resolveExporter(config: FluskOtelConfig): SpanExporter {
  const mode = resolveMode();
  let primary: SpanExporter;

  if (mode === 'local') {
    const dbPath = process.env['FLUSK_SQLITE_PATH'];
    log.info('Flusk: local mode — writing to ~/.flusk/data.db');
    primary = new SqliteSpanExporter(dbPath);
  } else {
    log.info(`Flusk: server mode — exporting to ${config.endpoint}`);
    primary = new OTLPTraceExporter({
      url: `${config.endpoint}/v1/traces`,
      headers: { 'x-flusk-api-key': config.apiKey },
    });
  }

  if (!config.exportTargets?.length) return primary;

  const platformExporters = config.exportTargets.map((t) =>
    createOtlpExporter({ platform: t.platform, endpoint: t.endpoint, apiKey: t.apiKey }),
  );
  log.info(`Multi-export: primary + ${platformExporters.length} platform target(s)`);
  return new MultiSpanExporter([primary, ...platformExporters]);
}
// --- END CUSTOM ---
