/**
 * @generated by @flusk/cli — sqlite-repo recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import type { DatabaseSync } from 'node:sqlite';
import type { AlertEventEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Insert a new Alert event record into SQLite
 */
export function create(
  db: DatabaseSync,
  data: Omit<AlertEventEntity, 'id' | 'createdAt' | 'updatedAt'>,
): AlertEventEntity {
  const stmt = db.prepare(`
    INSERT INTO alert_events (
      alert_type, severity, title, message, channel_name, delivered,
      acknowledged_at, metadata
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    RETURNING *
  `);

  const row = stmt.get(
    data.alertType,
    data.severity,
    data.title,
    data.message,
    data.channelName ?? null,
    data.delivered ? 1 : 0,
    data.acknowledgedAt ?? null,
    data.metadata != null ? JSON.stringify(data.metadata) : null,
  ) as Record<string, unknown>;

  return rowToEntity(row);
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
