/**
 * @generated by @flusk/cli — business-logic recipe
 * Format generated code snippets with proper indentation and comments
 * Pure function — no I/O
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export type CodeLanguage = 'typescript' | 'python' | 'json';

/**
 * Format a code snippet with language-specific header comment
 */
export function formatCodeSnippet(
  code: string,
  language: CodeLanguage
): string {
  const trimmed = code.trim();
  const header = buildHeader(language);
  return `${header}\n\n${trimmed}\n`;
}

function buildHeader(language: CodeLanguage): string {
  const comment = language === 'python' ? '#' : '//';
  const lines = [
    `${comment} Generated by Flusk — do not edit manually`,
    `${comment} Re-generate via: flusk optimize --regenerate`,
  ];
  return lines.join('\n');
}

/**
 * Indent every line of code by a given number of spaces
 */
export function indentCode(code: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return code
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : `${pad}${line}`))
    .join('\n');
}

/**
 * Wrap code in a JSON config object
 */
export function wrapAsJsonConfig(
  key: string,
  value: Record<string, unknown>
): string {
  const obj = { [key]: value };
  return JSON.stringify(obj, null, 2);
}
// --- END CUSTOM ---
