/**
 * @generated by @flusk/cli — test recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import { describe, it, expect } from 'vitest';
import { formatCodeSnippet, indentCode, wrapAsJsonConfig } from './format-code-snippet.function.js';

describe('formatCodeSnippet', () => {
  it('adds TypeScript header', () => {
    const result = formatCodeSnippet('const x = 1;', 'typescript');
    expect(result).toContain('// Generated by Flusk');
    expect(result).toContain('const x = 1;');
  });

  it('adds Python header with # comment', () => {
    const result = formatCodeSnippet('x = 1', 'python');
    expect(result).toContain('# Generated by Flusk');
  });

  it('trims whitespace', () => {
    const result = formatCodeSnippet('  code  \n\n', 'json');
    expect(result).toContain('code');
    expect(result).not.toMatch(/^\s/);
  });
});

describe('indentCode', () => {
  it('indents each line', () => {
    const result = indentCode('a\nb', 2);
    expect(result).toBe('  a\n  b');
  });

  it('preserves blank lines without indent', () => {
    const result = indentCode('a\n\nb', 4);
    expect(result).toBe('    a\n\n    b');
  });
});

describe('wrapAsJsonConfig', () => {
  it('wraps value in JSON object', () => {
    const result = wrapAsJsonConfig('cache', { ttl: 3600 });
    const parsed = JSON.parse(result);
    expect(parsed.cache.ttl).toBe(3600);
  });
});
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
