/**
 * Generate prompt deduplication/normalization code
 * Pure function — no I/O
 */

export interface PromptDedupInput {
  samplePrompts: string[];
  similarityThreshold: number;
  model: string;
}

/**
 * Generate TypeScript normalization + cache lookup function
 */
export function generatePromptDedup(input: PromptDedupInput): string {
  const lines = [
    '// Auto-generated by Flusk — prompt deduplication',
    `// Similarity threshold: ${input.similarityThreshold}`,
    `// Model: ${input.model}`,
    '',
    `import { createHash } from 'crypto';`,
    `import { createClient } from 'redis';`,
    '',
    'const redis = createClient({ url: process.env.REDIS_URL });',
    '',
    '/**',
    ' * Normalize a prompt to a canonical form for dedup',
    ' */',
    'export function normalizePrompt(prompt: string): string {',
    '  return prompt',
    '    .trim()',
    '    .toLowerCase()',
    '    .replace(/\\s+/g, \' \')',
    '    .replace(/[^a-z0-9 ]/g, \'\');',
    '}',
    '',
    '/**',
    ' * Hash a normalized prompt for cache key',
    ' */',
    'export function hashPrompt(prompt: string): string {',
    '  const normalized = normalizePrompt(prompt);',
    `  return createHash('sha256')`,
    '    .update(normalized)',
    `    .digest('hex')`,
    '    .slice(0, 16);',
    '}',
    '',
    '/**',
    ' * Deduplicated LLM call — returns cached result for similar prompts',
    ' */',
    'export async function dedupLLMCall(',
    '  prompt: string,',
    '  callFn: () => Promise<string>',
    '): Promise<string> {',
    '  const key = `flusk:dedup:${hashPrompt(prompt)}`;',
    '  const cached = await redis.get(key);',
    '  if (cached) return cached;',
    '  const result = await callFn();',
    '  await redis.set(key, result, { EX: 3600 });',
    '  return result;',
    '}',
  ];

  return lines.join('\n');
}
