/**
 * @generated by @flusk/forge — pipeline generator (test)
 */
import { describe, it, expect } from 'vitest';
import { agentBreakdown } from '../agent-breakdown.pipeline.js';
import type { AgentBreakdownInput } from '../agent-breakdown.pipeline.js';

describe('agentBreakdown pipeline', () => {
  it('empty calls', () => {
    const result = agentBreakdown({"calls":[]} as unknown as AgentBreakdownInput);
    expect(result).toEqual({"agentCount":0,"agents":[],"mostExpensive":"none","mostActive":"none"});
  });
});
