/**
 * @generated by @flusk/forge — pipeline generator (test)
 */
import { describe, it, expect } from 'vitest';
import { cacheAnalysis } from '../cache-analysis.pipeline.js';
import type { CacheAnalysisInput } from '../cache-analysis.pipeline.js';

describe('cacheAnalysis pipeline', () => {
  it('empty calls', () => {
    const result = cacheAnalysis({"calls":[]} as unknown as CacheAnalysisInput);
    expect(result).toEqual({"totalCalls":0,"cachedCalls":0,"hitRate":0,"costSaved":0,"byModel":{}});
  });
});
