/**
 * @generated by @flusk/forge — pipeline generator (test)
 */
import { describe, it, expect } from 'vitest';
import { sessionReport } from '../session-report.pipeline.js';

describe('sessionReport pipeline', () => {
  it('should be defined', () => {
    expect(sessionReport).toBeDefined();
  });
});
