/**
 * @generated by @flusk/forge — pipeline generator (test)
 */
import { describe, it, expect } from 'vitest';
import { tokenEfficiency } from '../token-efficiency.pipeline.js';
import type { TokenEfficiencyInput } from '../token-efficiency.pipeline.js';

describe('tokenEfficiency pipeline', () => {
  it('empty calls', () => {
    const result = tokenEfficiency({"calls":[]} as unknown as TokenEfficiencyInput);
    expect(result).toEqual({"totalTokens":0,"inputOutputRatio":0,"avgTokensPerCall":0,"tokensPerDollar":0,"oversizedPrompts":[],"byModel":{}});
  });
});
