/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/time/time-bucket.fn.yaml
 */

/**
 * Round a timestamp down to the nearest bucket (minute, hour, day)
 */
export function timeBucket(timestamp: string, bucket: "minute" | "hour" | "day"): string {
  return (() => {
  const d = new Date(timestamp);
  if (bucket === 'day') {
    d.setUTCHours(0, 0, 0, 0);
  } else if (bucket === 'hour') {
    d.setUTCMinutes(0, 0, 0);
  } else {
    d.setUTCSeconds(0, 0);
  }
  return d.toISOString();
})();
}
