/**
 * @generated by @flusk/forge — repo wrapper
 * Re-exports from multi-file repo with entity-prefixed names
 */

// --- BEGIN GENERATED (do not edit) ---
import * as Repo from '../sqlite/repositories/alert-channel/index.js';
import type { DatabaseSync } from 'node:sqlite';
import type { AlertChannelEntity } from '@flusk/entities';

type CreateInput = Omit<AlertChannelEntity, 'id' | 'createdAt' | 'updatedAt'>;
type UpdateInput = Partial<CreateInput>;

export function createAlertChannel(db: DatabaseSync, data: CreateInput): AlertChannelEntity {
  return Repo.create(db, data);
}

export function findAlertChannelById(db: DatabaseSync, id: string): AlertChannelEntity | null {
  return Repo.findById(db, id);
}

export function listAlertChannels(db: DatabaseSync, limit?: number, offset?: number): AlertChannelEntity[] {
  return Repo.list(db, limit, offset);
}

export function updateAlertChannel(db: DatabaseSync, id: string, data: UpdateInput): AlertChannelEntity | null {
  return Repo.update(db, id, data);
}

export function deleteAlertChannel(db: DatabaseSync, id: string): boolean {
  return Repo.deleteById(db, id);
}
// --- END GENERATED ---
