/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
import type { OptimizationEntity } from '@flusk/entities';
import type { DatabaseSync } from 'node:sqlite';

export type CreateOptimizationInput = Omit<OptimizationEntity, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateOptimizationInput = Partial<CreateOptimizationInput>;

function toISOString(value: unknown): string {
  if (typeof value === 'string') return value;
  if (value && typeof value === 'object' && 'toISOString' in value) {
    return (value as { toISOString(): string }).toISOString();
  }
  return String(value);
}

/** Convert a SQLite row (snake_case) to OptimizationEntity (camelCase) */
function rowToEntity(row: Record<string, unknown>): OptimizationEntity {
  return {
    id: row.id as string,
    createdAt: toISOString(row.created_at),
    updatedAt: toISOString(row.updated_at),
    organizationId: row.organization_id as string,
    optimizationType: row.optimization_type as string,
    title: row.title as string,
    description: row.description as string,
    estimatedSavingsPerMonth: row.estimated_savings_per_month as number,
    generatedCode: row.generated_code as string,
    language: row.language as string,
    status: row.status as string,
    sourcePatternId: (row.source_pattern_id as string) ?? undefined,
  };
}

function toSnake(s: string): string { return s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase(); }
function convertValueForDb(key: string, value: unknown): unknown {
  return value ?? null;
}

export function createOptimization(db: DatabaseSync, data: CreateOptimizationInput): OptimizationEntity {
  const stmt = db.prepare(`INSERT INTO optimizations (organization_id, optimization_type, title, description, estimated_savings_per_month, generated_code, language, status, source_pattern_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`);
  const row = stmt.get(data.organizationId, data.optimizationType, data.title, data.description, data.estimatedSavingsPerMonth, data.generatedCode, data.language, data.status, data.sourcePatternId ?? null) as Record<string, unknown>;
  return rowToEntity(row);
}

export function findOptimizationById(db: DatabaseSync, id: string): OptimizationEntity | null {
  const stmt = db.prepare('SELECT * FROM optimizations WHERE id = $1');
  const row = stmt.get(id) as Record<string, unknown> | undefined;
  return row ? rowToEntity(row) : null;
}

export function listOptimizations(db: DatabaseSync, limit = 50, offset = 0): OptimizationEntity[] {
  const stmt = db.prepare('SELECT * FROM optimizations ORDER BY created_at DESC LIMIT $1 OFFSET $2');
  return (stmt.all(limit, offset) as Record<string, unknown>[]).map(rowToEntity);
}

export function updateOptimization(db: DatabaseSync, id: string, data: UpdateOptimizationInput): OptimizationEntity | null {
  const keys = Object.keys(data).filter((k) => data[k as keyof typeof data] !== undefined);
  if (keys.length === 0) return findOptimizationById(db, id);
  const sets = keys.map((k) => `${toSnake(k)} = ?`).join(', ');
  const vals = keys.map((k) => convertValueForDb(k, data[k as keyof typeof data]));
  const stmt = db.prepare(`UPDATE optimizations SET ${sets} WHERE id = ? RETURNING *`);
  const row = stmt.get(...vals, id) as Record<string, unknown> | undefined;
  return row ? rowToEntity(row) : null;
}

export function deleteOptimization(db: DatabaseSync, id: string): boolean {
  const stmt = db.prepare('DELETE FROM optimizations WHERE id = $1');
  return stmt.run(id).changes > 0;
}

// --- BEGIN CUSTOM ---

// --- END CUSTOM ---
// --- END CUSTOM ---
