/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
import type { SpanEntity } from '@flusk/entities';
import type { DatabaseSync } from 'node:sqlite';

export type CreateSpanInput = Omit<SpanEntity, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateSpanInput = Partial<CreateSpanInput>;

function toISOString(value: unknown): string {
  if (typeof value === 'string') return value;
  if (value && typeof value === 'object' && 'toISOString' in value) {
    return (value as { toISOString(): string }).toISOString();
  }
  return String(value);
}

/** Convert a SQLite row (snake_case) to SpanEntity (camelCase) */
function rowToEntity(row: Record<string, unknown>): SpanEntity {
  return {
    id: row.id as string,
    createdAt: toISOString(row.created_at),
    updatedAt: toISOString(row.updated_at),
    traceId: row.trace_id as string,
    parentSpanId: (row.parent_span_id as string) ?? undefined,
    type: row.span_type as 'llm' | 'tool' | 'retrieval' | 'chain',
    name: row.name as string,
    input: (row.input as string) ?? undefined,
    output: (row.output as string) ?? undefined,
    cost: row.cost as number,
    tokens: row.tokens as number,
    latencyMs: row.latency_ms as number,
    status: row.status as 'running' | 'completed' | 'failed',
    startedAt: toISOString(row.started_at),
    completedAt: row.completed_at != null ? toISOString(row.completed_at) : undefined,
  };
}

function toSnake(s: string): string { return s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase(); }
function convertValueForDb(_key: string, value: unknown): unknown {
  return value ?? null;
}

export function createSpan(db: DatabaseSync, data: CreateSpanInput): SpanEntity {
  const stmt = db.prepare(`INSERT INTO spans (trace_id, parent_span_id, span_type, name, input, output, cost, tokens, latency_ms, status, started_at, completed_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING *`);
  const row = stmt.get(data.traceId, data.parentSpanId ?? null, data.type, data.name, data.input ?? null, data.output ?? null, data.cost, data.tokens, data.latencyMs, data.status, data.startedAt, data.completedAt ?? null) as Record<string, unknown>;
  return rowToEntity(row);
}

export function findSpanById(db: DatabaseSync, id: string): SpanEntity | null {
  const stmt = db.prepare('SELECT * FROM spans WHERE id = $1');
  const row = stmt.get(id) as Record<string, unknown> | undefined;
  return row ? rowToEntity(row) : null;
}

export function listSpans(db: DatabaseSync, limit = 50, offset = 0): SpanEntity[] {
  const stmt = db.prepare('SELECT * FROM spans ORDER BY created_at DESC LIMIT $1 OFFSET $2');
  return (stmt.all(limit, offset) as Record<string, unknown>[]).map(rowToEntity);
}

export function updateSpan(db: DatabaseSync, id: string, data: UpdateSpanInput): SpanEntity | null {
  const keys = Object.keys(data).filter((k) => data[k as keyof typeof data] !== undefined);
  if (keys.length === 0) return findSpanById(db, id);
  const sets = keys.map((k) => `${toSnake(k)} = ?`).join(', ');
  const vals = keys.map((k) => convertValueForDb(k, data[k as keyof typeof data])) as (string | number | null)[];
  const stmt = db.prepare(`UPDATE spans SET ${sets} WHERE id = ? RETURNING *`);
  const row = stmt.get(...vals, id) as Record<string, unknown> | undefined;
  return row ? rowToEntity(row) : null;
}

export function deleteSpan(db: DatabaseSync, id: string): boolean {
  const stmt = db.prepare('DELETE FROM spans WHERE id = $1');
  return stmt.run(id).changes > 0;
}

// --- BEGIN CUSTOM ---

// --- END CUSTOM ---
// --- END CUSTOM ---
