/**
 * Command generator — creates CLI command files from a command YAML schema.
 */
import { resolve } from 'node:path';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { parse as parseYaml } from 'yaml';
import { toPascalCase, toCamelCase } from '../utils.js';

export interface CommandOption {
  name: string;
  type: 'string' | 'integer' | 'number' | 'boolean';
  default?: string | number | boolean;
  enum?: string[];
  required?: boolean;
  description?: string;
}

export interface CommandSchema {
  name: string;
  description: string;
  options: CommandOption[];
}

export interface GenResult {
  files: { path: string; action: 'created' }[];
}

async function loadSchema(yamlPath: string): Promise<CommandSchema> {
  return parseYaml(await readFile(yamlPath, 'utf-8')) as CommandSchema;
}

function optionTsType(opt: CommandOption): string {
  if (opt.enum) return opt.enum.map(v => `'${v}'`).join(' | ');
  switch (opt.type) {
    case 'integer': case 'number': return 'number';
    case 'boolean': return 'boolean';
    default: return 'string';
  }
}

function camelName(name: string): string {
  return toCamelCase(name);
}

export function generateCommandOptionsContent(schema: CommandSchema): string {
  const lines = schema.options.map(opt => {
    const optional = opt.required === false || opt.default === undefined && opt.required !== true ? '?' : '';
    // If there's a default, the option is always present at runtime
    const mark = opt.default !== undefined ? '' : optional;
    return `  ${camelName(opt.name)}${mark}: ${optionTsType(opt)};`;
  });

  return `// --- BEGIN GENERATED ---
/**
 * Options for the "${schema.name}" command
 * @generated by @flusk/forge — command generator
 */
export interface ${toPascalCase(schema.name)}Options {
${lines.join('\n')}
}
// --- END GENERATED ---
`;
}

export function generateCommandContent(schema: CommandSchema): string {
  const pascal = toPascalCase(schema.name);
  const optionLines = schema.options.map(opt => {
    const flag = opt.type === 'boolean'
      ? `--${opt.name}`
      : `--${opt.name} <${opt.name}>`;
    const parts = [`    .option('${flag}', '${opt.description || opt.name}'`];
    if (opt.default !== undefined) parts.push(`, ${JSON.stringify(opt.default)}`);
    parts.push(')');
    return parts.join('');
  });

  return `// --- BEGIN GENERATED ---
/**
 * CLI command: flusk ${schema.name}
 * ${schema.description}
 * @generated by @flusk/forge — command generator
 */
import { Command } from 'commander';
import type { ${pascal}Options } from './${schema.name}.options.js';

export const ${toCamelCase(schema.name)}Command = new Command('${schema.name}')
  .description('${schema.description}')
${optionLines.join('\n')}
  .action(async (opts: ${pascal}Options) => {
    // TODO: implement command logic
    console.log('${schema.name} command executed', opts);
  });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
`;
}

export function generateCommandTestContent(schema: CommandSchema): string {
  const _pascal = toPascalCase(schema.name);
  return `// --- BEGIN GENERATED ---
/**
 * @generated by @flusk/forge — command generator
 */
import { describe, it, expect } from 'vitest';
import { ${toCamelCase(schema.name)}Command } from '../${schema.name}.js';

describe('${schema.name} command', () => {
  it('should be defined', () => {
    expect(${toCamelCase(schema.name)}Command).toBeDefined();
    expect(${toCamelCase(schema.name)}Command.name()).toBe('${schema.name}');
  });

  it('should have correct description', () => {
    expect(${toCamelCase(schema.name)}Command.description()).toBe('${schema.description}');
  });
});
// --- END GENERATED ---
`;
}

export function generateCommandPythonContent(schema: CommandSchema): string {
  const optionDecorators = schema.options.map(opt => {
    const _pyName = opt.name.replace(/-/g, '_');
    if (opt.type === 'boolean') {
      return `@click.option('--${opt.name}', is_flag=True, default=${opt.default ? 'True' : 'False'}, help='${opt.description || opt.name}')`;
    }
    const pyType = opt.type === 'integer' ? 'int' : opt.type === 'number' ? 'float' : 'str';
    const parts = [`@click.option('--${opt.name}'`];
    parts.push(`, type=${pyType}`);
    if (opt.default !== undefined) parts.push(`, default=${JSON.stringify(opt.default)}`);
    if (opt.enum) parts.push(`, type=click.Choice([${opt.enum.map(v => `'${v}'`).join(', ')}])`);
    if (!opt.required && opt.default === undefined) parts.push(`, default=None`);
    parts.push(`, help='${opt.description || opt.name}'`);
    parts.push(')');
    return parts.join('');
  });

  const paramNames = schema.options.map(opt => opt.name.replace(/-/g, '_'));

  return `# --- BEGIN GENERATED ---
# ${schema.name} command
# @generated by @flusk/forge — command generator

import click


${optionDecorators.join('\n')}
@click.command('${schema.name}')
def ${schema.name.replace(/-/g, '_')}(${paramNames.join(', ')}):
    """${schema.description}"""
    # TODO: implement command logic
    click.echo(f'${schema.name} command executed')

# --- END GENERATED ---
`;
}

async function writeGenFile(root: string, relPath: string, content: string, result: GenResult): Promise<void> {
  const abs = resolve(root, relPath);
  await mkdir(resolve(abs, '..'), { recursive: true });
  await writeFile(abs, content, 'utf-8');
  result.files.push({ path: relPath, action: 'created' });
}

export async function generateCommand(yamlPath: string): Promise<GenResult> {
  const root = process.cwd();
  const schema = await loadSchema(yamlPath);
  const result: GenResult = { files: [] };

  await writeGenFile(root, `packages/cli/src/commands/${schema.name}.ts`, generateCommandContent(schema), result);
  await writeGenFile(root, `packages/cli/src/commands/${schema.name}.options.ts`, generateCommandOptionsContent(schema), result);
  await writeGenFile(root, `packages/cli/src/commands/__tests__/${schema.name}.test.ts`, generateCommandTestContent(schema), result);
  await writeGenFile(root, `flusk-py/src/flusk/commands/${schema.name}.py`, generateCommandPythonContent(schema), result);

  return result;
}
