/**
 * Render TypeScript command files (options, command, test).
 */

import type { CommandOption, CommandSchema } from './command.types.js';
import { toPascalCase, toCamelCase } from '../utils.js';

function optionTsType(opt: CommandOption): string {
  if (opt.enum) return opt.enum.map(v => `'${v}'`).join(' | ');
  switch (opt.type) {
    case 'integer': case 'number': return 'number';
    case 'boolean': return 'boolean';
    default: return 'string';
  }
}

export function generateCommandOptionsContent(schema: CommandSchema): string {
  const lines = schema.options.map(opt => {
    const optional = opt.required === false || opt.default === undefined && opt.required !== true ? '?' : '';
    const mark = opt.default !== undefined ? '' : optional;
    return `  ${toCamelCase(opt.name)}${mark}: ${optionTsType(opt)};`;
  });

  return `// --- BEGIN GENERATED ---
/**
 * Options for the "${schema.name}" command
 * @generated by @flusk/forge — command generator
 */
export interface ${toPascalCase(schema.name)}Options {
${lines.join('\n')}
}
// --- END GENERATED ---
`;
}

export function generateCommandContent(schema: CommandSchema): string {
  const pascal = toPascalCase(schema.name);
  const optionLines = schema.options.map(opt => {
    const flag = opt.type === 'boolean'
      ? `--${opt.name}`
      : `--${opt.name} <${opt.name}>`;
    const parts = [`    .option('${flag}', '${opt.description || opt.name}'`];
    if (opt.default !== undefined) parts.push(`, ${JSON.stringify(opt.default)}`);
    parts.push(')');
    return parts.join('');
  });

  return `// --- BEGIN GENERATED ---
/**
 * CLI command: flusk ${schema.name}
 * ${schema.description}
 * @generated by @flusk/forge — command generator
 */
import { Command } from 'commander';
import type { ${pascal}Options } from './${schema.name}.options.js';

export const ${toCamelCase(schema.name)}Command = new Command('${schema.name}')
  .description('${schema.description}')
${optionLines.join('\n')}
  .action(async (opts: ${pascal}Options) => {
    // TODO: implement command logic
    console.log('${schema.name} command executed', opts);
  });
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
`;
}

export function generateCommandTestContent(schema: CommandSchema): string {
  const _pascal = toPascalCase(schema.name);
  return `// --- BEGIN GENERATED ---
/**
 * @generated by @flusk/forge — command generator
 */
import { describe, it, expect } from 'vitest';
import { ${toCamelCase(schema.name)}Command } from '../${schema.name}.js';

describe('${schema.name} command', () => {
  it('should be defined', () => {
    expect(${toCamelCase(schema.name)}Command).toBeDefined();
    expect(${toCamelCase(schema.name)}Command.name()).toBe('${schema.name}');
  });

  it('should have correct description', () => {
    expect(${toCamelCase(schema.name)}Command.description()).toBe('${schema.description}');
  });
});
// --- END GENERATED ---
`;
}
