/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { filterBy } from '../filter-by.function.js';

describe('filterBy', () => {
  it('filter by model', () => {
    expect(filterBy([{"model":"gpt-4"},{"model":"gpt-3"},{"model":"gpt-4"}], "model", "gpt-4")).toEqual([{"model":"gpt-4"},{"model":"gpt-4"}]);
  });

  it('no matches', () => {
    expect(filterBy([{"model":"gpt-3"}], "model", "gpt-4")).toEqual([]);
  });
});
