/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { findBy } from '../find-by.function.js';

describe('findBy', () => {
  it('found item', () => {
    expect(findBy([{"id":1,"name":"a"},{"id":2,"name":"b"}], "id", 2)).toEqual({"id":2,"name":"b"});
  });

  it('not found', () => {
    expect(findBy([{"id":1}], "id", 99)).toEqual(null);
  });
});
