/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { groupBy } from '../group-by.function.js';

describe('groupBy', () => {
  it('group by model', () => {
    expect(groupBy([{"model":"gpt-4","cost":1},{"model":"gpt-3","cost":2},{"model":"gpt-4","cost":3}], "model")).toEqual({"gpt-4":[{"model":"gpt-4","cost":1},{"model":"gpt-4","cost":3}],"gpt-3":[{"model":"gpt-3","cost":2}]});
  });
});
