/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { uniqueBy } from '../unique-by.function.js';

describe('uniqueBy', () => {
  it('removes duplicates', () => {
    expect(uniqueBy([{"id":1,"v":"a"},{"id":2,"v":"b"},{"id":1,"v":"c"}], "id")).toEqual([{"id":1,"v":"a"},{"id":2,"v":"b"}]);
  });

  it('no duplicates', () => {
    expect(uniqueBy([{"id":1},{"id":2}], "id")).toEqual([{"id":1},{"id":2}]);
  });
});
