/**
 * @generated by @flusk/cli — utility recipe
 */
// --- BEGIN GENERATED ---
import type { DatabaseSync } from 'node:sqlite';
import { readdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SQL_DIR = join(__dirname, 'sql');

/**
 * Run all pending SQLite migrations in order.
 * Tracks applied migrations in a `_migrations` table.
 */
export function runMigrations(db: DatabaseSync): void {
  db.exec(`
    CREATE TABLE IF NOT EXISTS _migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `);

  const applied = getAppliedMigrations(db);
  const files = getSqlFiles();

  for (const file of files) {
    if (!applied.has(file)) {
      const sql = readFileSync(join(SQL_DIR, file), 'utf-8');
      db.exec(sql);
      db.prepare('INSERT INTO _migrations (name) VALUES (?)').run(file);
    }
  }
}

function getAppliedMigrations(db: DatabaseSync): Set<string> {
  const stmt = db.prepare('SELECT name FROM _migrations');
  const rows = stmt.all() as Array<{ name: string }>;
  return new Set(rows.map((r) => r.name));
}

function getSqlFiles(): string[] {
  try {
    return readdirSync(SQL_DIR)
      .filter((f) => f.endsWith('.sql'))
      .sort();
  } catch {
    return [];
  }
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
export interface MigrationRecord {
  id: number;
  name: string;
  applied_at: string;
}

/**
 * Get the current schema version (number of applied migrations).
 */
export function getSchemaVersion(db: DatabaseSync): number {
  try {
    const stmt = db.prepare('SELECT COUNT(*) as count FROM _migrations');
    const row = stmt.get() as { count: number } | undefined;
    return row?.count ?? 0;
  } catch {
    return 0;
  }
}

/**
 * List all applied migrations with timestamps.
 */
export function listAppliedMigrations(db: DatabaseSync): MigrationRecord[] {
  try {
    const stmt = db.prepare('SELECT id, name, applied_at FROM _migrations ORDER BY id');
    return stmt.all() as MigrationRecord[];
  } catch {
    return [];
  }
}
// --- END CUSTOM ---
