/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { Type } from '@sinclair/typebox';
import { OptimizationRepository } from '@flusk/resources';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
/** GET /optimizations/:id/code — get generated code */
export function registerGetCodeRoute(fastify: FastifyInstance): void {
  fastify.get(
    '/:id/code',
    {
      schema: {
        params: Type.Object({ id: Type.String({ format: 'uuid' }) }),
        response: {
          200: Type.Object({
            code: Type.String(),
            language: Type.String(),
          }),
          404: Type.Object({ error: Type.String() }),
        },
        tags: ['Optimization'],
      }
    },
    async (
      request: FastifyRequest<{ Params: { id: string } }>,
      reply: FastifyReply
    ) => {
      const entity = OptimizationRepository.findOptimizationById(fastify.db, request.params.id);
      if (!entity) return reply.code(404).send({ error: 'Not found' });
      return reply.code(200).send({
        code: entity.generatedCode,
        language: entity.language,
      });
    }
  );
}
// --- END CUSTOM ---
