# --- BEGIN GENERATED ---
# explain command
# @generated by @flusk/forge — command generator

import click


@click.option('--provider', type=click.Choice(['openai', 'anthropic', 'google', 'local']), default='openai', help='LLM provider to analyze')
@click.option('--model', type=str, default=None, help='Specific model to filter by')
@click.option('--db', type=str, default='./flusk.db', help='Path to the Flusk SQLite database')
@click.option('--format', type=click.Choice(['text', 'json', 'markdown']), default='text', help='Output format')
@click.option('--max-insights', type=int, default=10, help='Maximum number of insights to return')
@click.option('--min-severity', type=click.Choice(['critical', 'high', 'medium', 'low']), default='low', help='Minimum severity threshold')
@click.option('--session', type=str, default=None, help='Filter by session ID')
@click.option('--cost-threshold', type=float, default=None, help='Cost threshold for alerts')
@click.option('--no-code', is_flag=True, default=False, help='Exclude code snippets from output')
@click.command('explain')
def explain(provider, model, db, format, max_insights, min_severity, session, cost_threshold, no_code):
    """Explain LLM cost insights and optimization opportunities"""
    # TODO: implement command logic
    click.echo('explain command executed')

# --- END GENERATED ---
