/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/collection/filter-by.fn.yaml
 */

/**
 * Filter an array of objects where a key matches a value
 */
export function filterBy<T>(items: T[], key: string, value: unknown): T[] {
  return items.filter((item) => (item as Record<string, unknown>)[key] === value);
}
