/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/collection/group-by.fn.yaml
 */

/**
 * Group array items by a key's value into a Map
 */
export function groupBy<T>(items: T[], key: string): Record<string, T[]> {
  return items.reduce((acc, item) => {
    const k = String((item as Record<string, unknown>)[key]);
    acc[k] = acc[k] ?? [];
    acc[k].push(item);
    return acc;
  }, {} as Record<string, T[]>);
}
