/**
 * Database initialization script generator.
 */

import { resolve } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import type { GeneratorResult } from './infra-file-generators.js';

/**
 * Generate database initialization script
 */
export async function generateInitDbScript(targetDir: string): Promise<GeneratorResult> {
  const scriptsDir = resolve(targetDir, 'scripts');
  const outputPath = resolve(scriptsDir, 'init-db.sql');

  if (!existsSync(scriptsDir)) {
    await mkdir(scriptsDir, { recursive: true });
  }

  const content = `-- @generated by @flusk/cli
-- PostgreSQL initialization script

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Set timezone
SET timezone = 'UTC';

-- Create updated_at function (reusable for all tables)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Log initialization
DO $$
BEGIN
  RAISE NOTICE 'Flusk database initialized successfully';
END $$;
`;

  await writeFile(outputPath, content, 'utf-8');

  return {
    path: 'scripts/init-db.sql',
    content
  };
}
