/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { durationMs } from '../duration-ms.function.js';

describe('durationMs', () => {
  it('basic duration', () => {
    expect(durationMs("2024-01-01T00:00:00.000Z", "2024-01-01T00:00:01.000Z")).toEqual(1000);
  });

  it('same time', () => {
    expect(durationMs("2024-01-01T00:00:00.000Z", "2024-01-01T00:00:00.000Z")).toEqual(0);
  });

  it('negative clamped to 0', () => {
    expect(durationMs("2024-01-01T00:00:01.000Z", "2024-01-01T00:00:00.000Z")).toEqual(0);
  });
});
