/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { timeBucket } from '../time-bucket.function.js';

describe('timeBucket', () => {
  it('minute bucket', () => {
    expect(timeBucket("2024-01-01T12:34:56.789Z", "minute")).toEqual("2024-01-01T12:34:00.000Z");
  });

  it('hour bucket', () => {
    expect(timeBucket("2024-01-01T12:34:56.789Z", "hour")).toEqual("2024-01-01T12:00:00.000Z");
  });

  it('day bucket', () => {
    expect(timeBucket("2024-01-01T12:34:56.789Z", "day")).toEqual("2024-01-01T00:00:00.000Z");
  });
});
