/**
 * Template for @generated file headers
 * Used by the CLI generator to mark generated files
 */

export interface GeneratedHeaderOptions {
  version: string;
  sourceFile: string;
  timestamp?: string;
  noHeader?: boolean;
}

export function createGeneratedHeader(options: GeneratedHeaderOptions): string {
  if (options.noHeader) {
    return '';
  }

  const timestamp = options.timestamp || new Date().toISOString();

  return `/**
 * @generated by flusk CLI v${options.version}
 * Generated from: ${options.sourceFile}
 * DO NOT EDIT - Changes will be overwritten on regeneration
 * To regenerate: flusk g ${options.sourceFile.split('/').pop()}
 * Last generated: ${timestamp}
 */

`;
}

export function extractGeneratedMetadata(content: string): {
  isGenerated: boolean;
  version?: string;
  sourceFile?: string;
  timestamp?: string;
} {
  const generatedMatch = content.match(/@generated by flusk CLI v([\d.]+)/);
  const sourceMatch = content.match(/Generated from: (.+)/);
  const timestampMatch = content.match(/Last generated: (.+)/);

  return {
    isGenerated: !!generatedMatch,
    version: generatedMatch?.[1],
    sourceFile: sourceMatch?.[1]?.trim(),
    timestamp: timestampMatch?.[1]?.trim(),
  };
}
