/** @generated —
 * Template for generating hook files
 */

import { toPascalCase } from '../generators/utils.js';

export function generateHooksTemplate(entityName: string): string {
  const pascalName = toPascalCase(entityName);

  return `/**
 * @generated by @flusk/cli from ${entityName}.entity.ts
 * DO NOT EDIT - regenerate using: flusk g ${entityName}.entity.ts
 */

import type { FastifyRequest, FastifyReply } from 'fastify';

/**
 * Example preHandler hook for ${pascalName}
 * Add business logic hooks here
 */
export async function validate${pascalName}Hook(
  _request: FastifyRequest,
  _reply: FastifyReply
): Promise<void> {
  // TODO: Add validation logic
  // Example:
  // const body = request.body as any;
  // if (!body.requiredField) {
  //   return reply.code(400).send({ error: 'requiredField is required' });
  // }
}

/**
 * Example onSend hook for ${pascalName}
 * Add post-processing logic here
 */
export async function transform${pascalName}Hook(
  _request: FastifyRequest,
  _reply: FastifyReply,
  payload: unknown
): Promise<unknown> {
  // TODO: Add transformation logic
  return payload;
}
`;
}
