/**
 * Template for generating plugin files
 */

import { toPascalCase } from '../generators/utils.js';

export function generatePluginTemplate(entityName: string): string {
  const pascalName = toPascalCase(entityName);

  return `/**
 * @generated by @flusk/cli from ${entityName}.entity.ts
 * DO NOT EDIT - regenerate using: flusk g ${entityName}.entity.ts
 */

import type { FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';
import { ${entityName.replace(/-/g, '')}Routes } from '../routes/${entityName}.routes.js';

/**
 * ${pascalName} plugin - encapsulates all ${entityName} functionality
 */
async function ${entityName.replace(/-/g, '')}Plugin(
  fastify: FastifyInstance
): Promise<void> {
  // Register routes under /${entityName}s prefix
  await fastify.register(${entityName.replace(/-/g, '')}Routes, { prefix: '/${entityName}s' });

  fastify.log.info('${pascalName} plugin registered');
}

// eslint-disable-next-line no-restricted-syntax -- fastify-plugin requires default export
export default fp(${entityName.replace(/-/g, '')}Plugin, {
  name: '${entityName}-plugin'
});
`;
}
