# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.training.format_as_alpaca import format_as_alpaca


def test_formats_with_context():
    assert format_as_alpaca("Summarize this", "Here is a summary.", "You are a summarizer.") == "{\"instruction\":\"Summarize this\",\"input\":\"You are a summarizer.\",\"output\":\"Here is a summary.\"}"


def test_formats_without_context():
    assert format_as_alpaca("Hello", "Hi", "") == "{\"instruction\":\"Hello\",\"input\":\"\",\"output\":\"Hi\"}"
