/** @generated by @flusk/forge — entity generator */
// --- BEGIN GENERATED (do not edit) ---
import { Type, Static } from '@sinclair/typebox';
import { BaseEntitySchema } from './base.entity.js';

/**
 * AlertEventEntity schema
 */
export const AlertEventEntitySchema = Type.Composite([
  BaseEntitySchema,
  Type.Object({
    alertType: Type.Union([Type.Literal('budget_exceeded'), Type.Literal('budget_warning'), Type.Literal('drift_detected'), Type.Literal('cost_anomaly'), Type.Literal('agent_stalled'), Type.Literal('error_rate_spike'), Type.Literal('token_rate_limit')]),
    severity: Type.Union([Type.Literal('critical'), Type.Literal('warning'), Type.Literal('info')]),
    title: Type.String({ description: 'Short alert title' }),
    message: Type.String({ description: 'Detailed alert message' }),
    channelName: Type.Optional(Type.String({ description: 'Which alert channel delivered this' })),
    delivered: Type.Boolean({ description: 'Whether the alert was successfully delivered', default: false }),
    acknowledgedAt: Type.Optional(Type.String({ description: 'ISO datetime when acknowledged' })),
    metadata: Type.Optional(Type.Unknown({ description: 'Additional context' }))
  })
]);

export type AlertEventEntity = Static<typeof AlertEventEntitySchema>;
// --- END GENERATED ---
