/** @generated by @flusk/forge — entity generator */
// --- BEGIN GENERATED (do not edit) ---
import { Type, Static } from '@sinclair/typebox';
import { BaseEntitySchema } from './base.entity.js';

/**
 * AlertChannelEntity schema
 */
export const AlertChannelEntitySchema = Type.Composite([
  BaseEntitySchema,
  Type.Object({
    name: Type.String({ description: 'Human-readable channel name' }),
    channelType: Type.Union([Type.Literal('pagerduty'), Type.Literal('slack'), Type.Literal('discord'), Type.Literal('webhook'), Type.Literal('email')]),
    config: Type.Unknown({ description: 'Provider-specific configuration (routing_key, webhook_url, etc.)' }),
    enabled: Type.Boolean({ description: 'Whether this channel is active', default: true }),
    severityFilter: Type.Union([Type.Literal('critical'), Type.Literal('warning'), Type.Literal('info')])
  })
]);

export type AlertChannelEntity = Static<typeof AlertChannelEntitySchema>;
// --- END GENERATED ---
