/**
 * @generated by @flusk/cli — utility recipe
 */
// --- BEGIN GENERATED ---
import { Type, Static } from '@sinclair/typebox';

/**
 * BaseEntity schema - foundation for all entities in Flusk
 * Provides common fields: id, createdAt, updatedAt
 */
export const BaseEntitySchema = Type.Object({
  id: Type.String({
    format: 'uuid',
    description: 'Unique identifier for the entity'
  }),
  createdAt: Type.String({
    format: 'date-time',
    description: 'Timestamp when the entity was created'
  }),
  updatedAt: Type.String({
    format: 'date-time',
    description: 'Timestamp when the entity was last updated'
  })
});

export type BaseEntity = Static<typeof BaseEntitySchema>;
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
