/**
 * @generated by @flusk/cli — entity recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import { Type, Static } from '@sinclair/typebox';
import { BaseEntitySchema } from './base.entity.js';

/**
 * ConversionEntity schema
 * @generated from Conversion YAML definition
 */
export const ConversionEntitySchema = Type.Composite([
  BaseEntitySchema,
  Type.Object({
    patternId: Type.String({ format: 'uuid', description: 'Reference to the pattern this conversion applies to' }),
    organizationId: Type.String({ format: 'uuid', description: 'Organization that owns this conversion' }),
    conversionType: Type.Union([Type.Literal('cache'), Type.Literal('downgrade'), Type.Literal('remove')]),
    status: Type.Union([Type.Literal('suggested'), Type.Literal('accepted'), Type.Literal('rejected')]),
    estimatedSavings: Type.Number({ description: 'Projected monthly savings in USD if accepted', minimum: 0 }),
    config: Type.Unknown({ description: 'Type-specific configuration (cache TTL, model swap details, or removal reason)' })
  })
]);

export type ConversionEntity = Static<typeof ConversionEntitySchema>;
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
