/** @generated by @flusk/forge — entity generator */
// --- BEGIN GENERATED (do not edit) ---
import { Type, Static } from '@sinclair/typebox';
import { BaseEntitySchema } from './base.entity.js';

/**
 * ConversationEntity schema
 */
export const ConversationEntitySchema = Type.Composite([
  BaseEntitySchema,
  Type.Object({
    externalId: Type.Optional(Type.String({ description: 'User-provided conversation ID' })),
    model: Type.String({ description: 'Primary model used in conversation', minLength: 1 }),
    provider: Type.String({ description: 'Primary LLM provider', minLength: 1 }),
    turnCount: Type.Integer({ description: 'Number of LLM calls in conversation', minimum: 0, default: 0 }),
    totalInputTokens: Type.Integer({ description: 'Sum of input tokens across all calls', minimum: 0, default: 0 }),
    totalOutputTokens: Type.Integer({ description: 'Sum of output tokens across all calls', minimum: 0, default: 0 }),
    totalCost: Type.Number({ description: 'Total cost in USD across all calls', minimum: 0, default: 0 }),
    firstCallAt: Type.String({ format: 'date-time', description: 'Timestamp of the first LLM call' }),
    lastCallAt: Type.String({ format: 'date-time', description: 'Timestamp of the most recent LLM call' }),
    metadata: Type.Optional(Type.Unknown({ description: 'Arbitrary metadata for the conversation' })),
    status: Type.Union([Type.Literal('active'), Type.Literal('completed'), Type.Literal('abandoned')])
  })
]);

export type ConversationEntity = Static<typeof ConversationEntitySchema>;
// --- END GENERATED ---
