/**
 * @generated by @flusk/cli — entity recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import { Type, Static } from '@sinclair/typebox';
import { BaseEntitySchema } from './base.entity.js';

/**
 * PromptVersionEntity schema
 * @generated from PromptVersion YAML definition
 */
export const PromptVersionEntitySchema = Type.Composite([
  BaseEntitySchema,
  Type.Object({
    templateId: Type.String({ format: 'uuid', description: 'Parent template ID' }),
    version: Type.Number({ description: 'Auto-increment version number per template' }),
    content: Type.String({ description: 'Prompt text with {{variable}} placeholders' }),
    metrics: Type.Unknown({ description: 'Performance metrics (avgQuality, avgLatencyMs, avgCost, sampleCount)', default: '{"avgQuality":0,"avgLatencyMs":0,"avgCost":0,"sampleCount":0}' }),
    status: Type.Union([Type.Literal('draft'), Type.Literal('active'), Type.Literal('archived'), Type.Literal('rolled-back')])
  })
]);

export type PromptVersionEntity = Static<typeof PromptVersionEntitySchema>;
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
