/** @generated by @flusk/forge — entity generator */
// --- BEGIN GENERATED (do not edit) ---
import { Type, Static } from '@sinclair/typebox';
import { BaseEntitySchema } from './base.entity.js';

/**
 * TrainingPairEntity schema
 */
export const TrainingPairEntitySchema = Type.Composite([
  BaseEntitySchema,
  Type.Object({
    tenantId: Type.Optional(Type.String({ description: 'Tenant ID for multi-tenant isolation' })),
    sourceModel: Type.String({ description: 'Source model identifier (e.g. claude-sonnet-4-20250514, gpt-4o)' }),
    sourceProvider: Type.Union([Type.Literal('anthropic'), Type.Literal('openai'), Type.Literal('google')]),
    prompt: Type.String({ description: 'Full user prompt or messages JSON' }),
    completion: Type.String({ description: 'Model response text' }),
    systemPrompt: Type.Optional(Type.String({ description: 'System prompt if present' })),
    inputTokens: Type.Integer({ description: 'Number of input tokens', minimum: 0, default: 0 }),
    outputTokens: Type.Integer({ description: 'Number of output tokens', minimum: 0, default: 0 }),
    quality: Type.Union([Type.Literal('unrated'), Type.Literal('good'), Type.Literal('flagged'), Type.Literal('rejected')]),
    cluster: Type.Optional(Type.String({ description: 'Assigned pattern cluster label' })),
    metadata: Type.Optional(Type.Unknown({ description: 'Additional metadata (temperature, tools used, etc.)' }))
  })
]);

export type TrainingPairEntity = Static<typeof TrainingPairEntitySchema>;
// --- END GENERATED ---
