/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/training/format-as-alpaca.fn.yaml
 */

/**
 * Format a training pair as Alpaca format for fine-tuning
 */
export function formatAsAlpaca(prompt: string, completion: string, systemPrompt: string): string {
  return (() => {
  return JSON.stringify({
    instruction: prompt,
    input: systemPrompt || '',
    output: completion,
  });
})();
}
