/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/training/jaccard-similarity.fn.yaml
 */

/**
 * Calculate Jaccard similarity between two string arrays
 */
export function jaccardSimilarity(setA: string[], setB: string[]): number {
  return (() => {
  const a = new Set(setA);
  const b = new Set(setB);
  if (a.size === 0 && b.size === 0) return 1;
  if (a.size === 0 || b.size === 0) return 0;
  const intersection = [...a].filter(x => b.has(x)).length;
  const union = new Set([...a, ...b]).size;
  return intersection / union;
})();
}
