/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/training/should-collect.fn.yaml
 */

/**
 * Determine if an LLM call should be collected as training data
 */
export function shouldCollect(_provider: string, model: string, prompt: string, completion: string, status: string, teacherModels: string[]): boolean {
  return (() => {
  if (status !== 'ok') return false;
  if (prompt.length < 10) return false;
  if (completion.length < 10) return false;
  const isTeacher = teacherModels.some(
    (tm: string) => model.includes(tm) || tm.includes(model)
  );
  return isTeacher;
})();
}
