-- @generated by @flusk/cli from conversion.entity.ts
-- DO NOT EDIT - regenerate using: flusk g conversion.entity.ts

-- Create conversions table
CREATE TABLE IF NOT EXISTS conversions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
  -- TODO: Add columns from entity schema
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_conversions_created_at ON conversions(created_at);
CREATE INDEX IF NOT EXISTS idx_conversions_updated_at ON conversions(updated_at);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_conversions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER conversions_updated_at
  BEFORE UPDATE ON conversions
  FOR EACH ROW
  EXECUTE FUNCTION update_conversions_updated_at();
