/**
 * @generated by @flusk/cli — sqlite-repo recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import type { PromptVersionEntity } from '@flusk/entities';

/**
 * Convert SQLite row to PromptVersionEntity
 */
export function rowToEntity(row: Record<string, unknown>): PromptVersionEntity {
  // TODO: implement snake_case → camelCase mapping
  return row as unknown as PromptVersionEntity;
}

// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
