/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { average } from '../average.function.js';

describe('average', () => {
  it('basic average', () => {
    expect(average([1,2,3])).toEqual(2);
  });

  it('empty array', () => {
    expect(average([])).toEqual(0);
  });

  it('single value', () => {
    expect(average([10])).toEqual(10);
  });
});
