/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { sum } from '../sum.function.js';

describe('sum', () => {
  it('basic sum', () => {
    expect(sum([1,2,3])).toEqual(6);
  });

  it('empty array', () => {
    expect(sum([])).toEqual(0);
  });

  it('single value', () => {
    expect(sum([42])).toEqual(42);
  });
});
