# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.math.percentage import percentage


def test_basic_percentage():
    assert percentage(25, 100) == 25


def test_zero_total():
    assert percentage(5, 0) == 0


def test_full_percentage():
    assert percentage(50, 50) == 100
