# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.math.sum import sum


def test_basic_sum():
    assert sum([1,2,3]) == 6


def test_empty_array():
    assert sum([]) == 0


def test_single_value():
    assert sum([42]) == 42
