/**
 * Template for generating Fastify plugin test files
 */

import { toPascalCase, toCamelCase } from '../../generators/utils.js';

export function generatePluginTestTemplate(pluginName: string): string {
  const pascalName = toPascalCase(pluginName);
  const camelName = toCamelCase(pluginName);

  return `/**
 * @generated by @flusk/cli
 * Tests for ${pascalName} Plugin
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import Fastify, { FastifyInstance } from 'fastify';
import { ${camelName}Plugin } from './${pluginName}.plugin.js';

describe('${pascalName} Plugin', () => {
  let fastify: FastifyInstance;

  beforeEach(async () => {
    fastify = Fastify({ logger: false });
  });

  afterEach(async () => {
    await fastify.close();
  });

  it('should register plugin successfully', async () => {
    // Act
    await fastify.register(${camelName}Plugin);

    // Assert
    expect(fastify.${camelName}).toBeDefined();
    expect(fastify.${camelName}.getName()).toBe('${pluginName}');
  });

  it('should add health check route', async () => {
    // Arrange
    await fastify.register(${camelName}Plugin, { prefix: '/test' });

    // Act
    const response = await fastify.inject({
      method: 'GET',
      url: '/test/health'
    });

    // Assert
    expect(response.statusCode).toBe(200);
    expect(JSON.parse(response.body)).toEqual({
      status: 'ok',
      plugin: '${pluginName}'
    });
  });

  it('should support custom prefix', async () => {
    // Arrange
    await fastify.register(${camelName}Plugin, { prefix: '/custom' });

    // Act
    const response = await fastify.inject({
      method: 'GET',
      url: '/custom/health'
    });

    // Assert
    expect(response.statusCode).toBe(200);
  });
});
`;
}
