/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { Type } from '@sinclair/typebox';
import { PromptVersionEntitySchema } from '@flusk/entities';
import { PromptVersionRepository } from '@flusk/resources';
import { promptVersion } from '@flusk/business-logic';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export async function promptVersionCrudRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.post('/', {
    schema: {
      body: Type.Object({
        templateId: Type.String({ format: 'uuid' }),
        content: Type.String(),
        status: Type.Optional(Type.String()),
      }),
      response: { 201: PromptVersionEntitySchema },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const data = request.body as any;
    const validation = promptVersion.validatePromptVersion(data);
    if (!validation.valid) return reply.code(400).send({ error: validation.errors.join(', ') });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- body validated by schema
    const created = PromptVersionRepository.createPromptVersion(fastify.db, data as any);
    return reply.code(201).send(created);
  });

  fastify.get('/template/:templateId', {
    schema: { params: Type.Object({ templateId: Type.String({ format: 'uuid' }) }) },
  }, async (_request: FastifyRequest<{ Params: { templateId: string } }>, reply: FastifyReply) => {
    const versions = PromptVersionRepository.listPromptVersions(fastify.db);
    return reply.send(versions);
  });

  fastify.get('/:id', {
    schema: { params: Type.Object({ id: Type.String({ format: 'uuid' }) }) },
  }, async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const entity = PromptVersionRepository.findPromptVersionById(fastify.db, request.params.id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    return reply.send(entity);
  });
}
// --- END CUSTOM ---
