/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { promptVersionCrudRoutes } from './crud.routes.js';
import { promptVersionActionRoutes } from './action.routes.js';

export async function promptversionRoutes(fastify: FastifyInstance): Promise<void> {
  await fastify.register(promptVersionCrudRoutes);
  await fastify.register(promptVersionActionRoutes);
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
