/**
 * @generated by @flusk/cli — middleware recipe
 * Config plugin — validates environment variables using @fastify/env + TypeBox.
 * Must be registered first so app.config is available to all other plugins.
 */

// --- BEGIN GENERATED ---
import fp from 'fastify-plugin';
import fastifyEnv from '@fastify/env';
import { Type } from '@sinclair/typebox';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const schema = Type.Object({
  DATABASE_URL: Type.String(),
  REDIS_URL: Type.String({ default: 'redis://localhost:6379' }),
  PORT: Type.Number({ default: 3000 }),
  HOST: Type.String({ default: '0.0.0.0' }),
  LOG_LEVEL: Type.String({ default: 'info' }),
  FLUSK_API_KEY: Type.String({ default: '' }),
  HMAC_SECRET: Type.Optional(Type.String()),
  FLUSK_HMAC_SECRET: Type.Optional(Type.String()),
  ENCRYPTION_KEY: Type.Optional(Type.String()),
  OPENAI_API_KEY: Type.Optional(Type.String()),
  FLUSK_RATE_LIMIT_MAX: Type.Number({ default: 100 }),
  FLUSK_LOG_LEVEL: Type.Optional(Type.String()),
  VECTOR_SIMILARITY_THRESHOLD: Type.Number({ default: 0.95 }),
  NODE_ENV: Type.String({ default: 'development' }),
});

export const plugin = fp(async (app) => {
  await app.register(fastifyEnv, {
    schema: Type.Strict(schema),
    dotenv: true,
  });

  const hmac = process.env.HMAC_SECRET || process.env.FLUSK_HMAC_SECRET;
  if (!hmac) {
    app.log.error('HMAC_SECRET or FLUSK_HMAC_SECRET is not set. Auth middleware will fail.');
    throw new Error(
      'HMAC_SECRET or FLUSK_HMAC_SECRET must be set in server mode. ' +
      'Auth requires this for token validation. ' +
      'Generate one with: openssl rand -hex 32',
    );
  }
  if (hmac.length < 32) {
    app.log.warn('HMAC_SECRET is shorter than 32 characters — consider using a stronger secret');
  }

  if (!process.env.ENCRYPTION_KEY) {
    app.log.warn('ENCRYPTION_KEY is not set — data-at-rest encryption disabled');
  }
}, { name: 'flusk-config' });
// --- END CUSTOM ---
