/**
 * @generated by @flusk/cli from span.entity.ts
 * DO NOT EDIT - regenerate using: flusk g span.entity.ts
 */

import type { FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';
import { spanRoutes } from '../routes/span.routes.js';

/**
 * Span plugin - encapsulates all span functionality
 */
async function spanPlugin(
  fastify: FastifyInstance
): Promise<void> {
  // Register routes under /spans prefix
  await fastify.register(spanRoutes, { prefix: '/spans' });

  fastify.log.info('Span plugin registered');
}

// eslint-disable-next-line no-restricted-syntax -- fastify-plugin requires default export
export default fp(spanPlugin, {
  name: 'span-plugin'
});
