/**
 * @generated by @flusk/cli — then customized
 * Swagger Plugin — auto-generated API docs
 */

import fp from 'fastify-plugin';
import type { FastifyInstance } from 'fastify';

async function swaggerPluginImpl(fastify: FastifyInstance) {
  await fastify.register(import('@fastify/swagger'), {
    openapi: {
      info: {
        title: 'Flusk API',
        version: '0.1.0',
        description: 'LLM Cost Optimization Platform',
      },
      servers: [{ url: '/' }],
    },
  });

  await fastify.register(import('@fastify/swagger-ui'), {
    routePrefix: '/docs',
  });
}

export const plugin = fp(swaggerPluginImpl, {
  fastify: '5.x',
  name: 'flusk-swagger',
});
