/**
 * Business logic recipe — scaffolds a pure function + test.
 *
 * WHY: Business logic functions follow a pattern: typed input/output,
 * pure function, co-located test. This recipe generates both files
 * and adds the export to the domain barrel.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { toPascalCase, toCamelCase } from '../generators/utils.js';

const generateFunction: RecipeStep = {
  name: 'generate-function',
  description: 'Generate pure business logic function',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const domain = ctx.options['domain'] as string;
    const dir = resolve(ctx.projectRoot,
      `packages/business-logic/src/${domain}`);
    const content = functionTemplate(name, _domain);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.function.ts`, content)],
    };
  },
};

const generateTest: RecipeStep = {
  name: 'generate-test',
  description: 'Generate function test file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const domain = ctx.options['domain'] as string;
    const dir = resolve(ctx.projectRoot,
      `packages/business-logic/src/${domain}`);
    const content = testTemplate(name);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.test.ts`, content)],
    };
  },
};

export const businessLogicRecipe: Recipe = {
  name: 'business-logic',
  description: 'Generate a pure business logic function with test',
  steps: [generateFunction, generateTest],
};

function functionTemplate(name: string, _domain: string): string {
  const _pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * ${pascal} — pure business logic function
 */

export interface ${pascal}Input {
  // TODO: define input shape
}

export interface ${pascal}Output {
  // TODO: define output shape
}

/**
 * ${pascal}
 *
 * Pure function — no side effects, no I/O.
 */
export function ${camel}(input: ${pascal}Input): ${pascal}Output {
  // CUSTOM:START — implement logic
  throw new Error('Not implemented');
  // CUSTOM:END
}
`;
}

function testTemplate(name: string): string {
  const _pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';
import { ${camel} } from './${name}.function.js';

describe('${camel}', () => {
  it('should be defined', () => {
    expect(${camel}).toBeDefined();
    expect(typeof ${camel}).toBe('function');
  });

  // CUSTOM:START — add test cases
  // CUSTOM:END
});
`;
}
