/** @generated —
 * CLI command recipe — scaffolds a new commander command + test.
 *
 * WHY: Adding a CLI command requires boilerplate (Command setup,
 * action handler, test file). This recipe generates it all and
 * reminds the user to register in flusk.ts.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { toCamelCase } from '../generators/utils.js';

/** Generate the command file */
const generateCommand: RecipeStep = {
  name: 'generate-command',
  description: 'Generate commander command file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const desc = (ctx.options['description'] as string) ?? `The ${name} command`;
    const dir = resolve(ctx.projectRoot, 'packages/cli/src/commands');
    const content = commandTemplate(name, desc);
    return { files: [writeRecipeFile(ctx, dir, `${name}.ts`, content)] };
  },
};

/** Generate the test file */
const generateTest: RecipeStep = {
  name: 'generate-test',
  description: 'Generate command test file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const dir = resolve(ctx.projectRoot, 'packages/cli/src/commands');
    const content = testTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, `${name}.test.ts`, content)] };
  },
};

export const cliCommandRecipe: Recipe = {
  name: 'cli-command',
  description: 'Generate a CLI command with test file',
  steps: [generateCommand, generateTest],
};

function commandTemplate(name: string, description: string): string {
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * CLI command: flusk ${name}
 */
import { Command } from 'commander';
import chalk from 'chalk';

export const ${camel}Command = new Command('${name}')
  .description('${description}')
  .action(async () => {
    console.log(chalk.blue('Running ${name}...'));
    // TODO: implement
  });
`;
}

function testTemplate(name: string): string {
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { test, describe } from 'node:test';
import assert from 'node:assert';
import { ${camel}Command } from './${name}.js';

describe('${name} command', () => {
  test('exports a Command instance', () => {
    assert.strictEqual(${camel}Command.name(), '${name}');
  });
});
`;
}
