/**
 * Middleware recipe — scaffolds Fastify preHandler middleware + test.
 *
 * WHY: Middleware follows a consistent pattern (preHandler hook,
 * options interface, test with mock request/reply). This recipe
 * generates both files from a single command.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { toPascalCase, toCamelCase } from '../generators/utils.js';

const generateMiddleware: RecipeStep = {
  name: 'generate-middleware',
  description: 'Generate Fastify preHandler middleware',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'execution';
    const dir = resolve(ctx.projectRoot, `packages/${pkg}/src/middleware`);
    const content = middlewareTemplate(name);
    return { files: [writeRecipeFile(ctx, dir, `${name}.middleware.ts`, content)] };
  },
};

const generateTest: RecipeStep = {
  name: 'generate-test',
  description: 'Generate middleware test file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'execution';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/middleware/__tests__`);
    const content = testTemplate(name);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.middleware.test.ts`, content)],
    };
  },
};

export const middlewareRecipe: Recipe = {
  name: 'middleware',
  description: 'Generate a Fastify preHandler middleware with test',
  steps: [generateMiddleware, generateTest],
};

function middlewareTemplate(name: string): string {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * ${pascal} Middleware — Fastify preHandler hook
 */

import type { FastifyReply, FastifyRequest } from 'fastify';
import { getLogger } from '@flusk/logger';

const log = getLogger().child({ module: '${name}-middleware' });

export interface ${pascal}MiddlewareOptions {
  enabled?: boolean;
}

/** ${pascal} preHandler hook */
export async function ${camel}Middleware(
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {
  log.debug({ url: request.url }, '${name} middleware');
  // CUSTOM:START — add middleware logic
  // CUSTOM:END
}
`;
}

function testTemplate(name: string): string {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';

describe('${pascal} middleware', () => {
  it('should export middleware function', async () => {
    const mod = await import('../${name}.middleware.js');
    expect(mod.${camel}Middleware).toBeDefined();
    expect(typeof mod.${camel}Middleware).toBe('function');
  });
});
`;
}
