/**
 * SDK provider interceptor recipe — scaffolds a provider interceptor.
 *
 * WHY: SDK provider interceptors (OpenAI, Anthropic, Bedrock) follow
 * a pattern: wrap client methods, intercept calls, emit spans.
 * This generates the interceptor + test.
 */

import { resolve } from 'node:path';
import type { Recipe, RecipeStep } from './recipe.types.js';
import { writeRecipeFile } from './recipe.helpers.js';
import { toPascalCase, toCamelCase } from '../generators/utils.js';

const generateInterceptor: RecipeStep = {
  name: 'generate-interceptor',
  description: 'Generate provider interceptor',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'sdk';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/providers`);
    const content = interceptorTemplate(name);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.interceptor.ts`, content)],
    };
  },
};

const generateTest: RecipeStep = {
  name: 'generate-test',
  description: 'Generate interceptor test file',
  async run(ctx) {
    const name = ctx.options['name'] as string;
    const pkg = (ctx.options['package'] as string) ?? 'sdk';
    const dir = resolve(ctx.projectRoot,
      `packages/${pkg}/src/providers/__tests__`);
    const content = testTemplate(name);
    return {
      files: [writeRecipeFile(ctx, dir, `${name}.interceptor.test.ts`, content)],
    };
  },
};

export const sdkProviderRecipe: Recipe = {
  name: 'sdk-provider',
  description: 'Generate an SDK provider interceptor with test',
  steps: [generateInterceptor, generateTest],
};

function interceptorTemplate(name: string): string {
  const pascal = toPascalCase(name);
  const _camel = toCamelCase(name);
  return `/**
 * @generated by @flusk/cli
 * ${pascal} provider interceptor — wraps SDK client calls
 */

import { trace, SpanStatusCode } from '@opentelemetry/api';

const tracer = trace.getTracer('flusk-sdk-${name}');

export interface ${pascal}InterceptorOptions {
  /** Whether to capture request/response bodies */
  captureContent?: boolean;
}

/**
 * Wrap a ${pascal} client to emit OTel spans for each API call.
 */
export function intercept${pascal}<T extends object>(
  client: T,
  options: ${pascal}InterceptorOptions = {},
): T {
  // CUSTOM:START — implement provider-specific interception
  return client;
  // CUSTOM:END
}
`;
}

function testTemplate(name: string): string {
  const pascal = toPascalCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';
import { intercept${pascal} } from '../${name}.interceptor.js';

describe('${pascal} interceptor', () => {
  it('should return the client unchanged by default', () => {
    const client = { chat: () => {} };
    const wrapped = intercept${pascal}(client);
    expect(wrapped).toBeDefined();
  });
});
`;
}
