/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { promptTemplateCrudRoutes } from './crud.routes.js';
import { promptTemplateActionRoutes } from './action.routes.js';

export async function prompttemplateRoutes(fastify: FastifyInstance): Promise<void> {
  await fastify.register(promptTemplateCrudRoutes);
  await fastify.register(promptTemplateActionRoutes);
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
