/**
 * @generated by @flusk/cli — tui recipe
 */
// --- BEGIN GENERATED ---
/**
 * TUI Hook: useApi — undici-based API client with polling
 */

import { useState, useEffect } from 'react';
import { request } from 'undici';

export interface UseApiResult<T> {
  data: T | null;
  loading: boolean;
  error: string | null;
}

export function useApi<T>(
  endpoint: string,
  path: string,
  apiKey: string,
  intervalMs = 5000,
): UseApiResult<T> {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    const fetchData = async () => {
      try {
        const res = await request(`${endpoint}${path}`, {
          headers: { 'x-flusk-api-key': apiKey },
        });
        const body = (await res.body.json()) as T;
        if (active) { setData(body); setError(null); }
      } catch (err) {
        if (active) setError(String(err));
      } finally {
        if (active) setLoading(false);
      }
    };
    fetchData();
    const id = setInterval(fetchData, intervalMs);
    return () => { active = false; clearInterval(id); };
  }, [endpoint, path, apiKey, intervalMs]);

  return { data, loading, error };
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
