/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import { createDecipheriv } from 'crypto';
import { getLogger } from '@flusk/logger';
import { ALGORITHM, deriveKey } from './crypto-utils.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const logger = getLogger().child({ module: 'decrypt' });

/**
 * Decrypt data encrypted with AES-256-GCM
 * @param ciphertext - Encrypted data in format: salt:iv:authTag:ciphertext
 */
export function decrypt(ciphertext: string, encryptionKey?: string): string {
  const key = encryptionKey || process.env.ENCRYPTION_KEY;
  if (!key) throw new Error('ENCRYPTION_KEY environment variable is required');
  if (!ciphertext) return '';

  const parts = ciphertext.split(':');
  if (parts.length !== 4) throw new Error('Invalid encrypted data format');

  const [saltB64, ivB64, authTagB64, encryptedData] = parts as [string, string, string, string];
  const salt = Buffer.from(saltB64, 'base64');
  const iv = Buffer.from(ivB64, 'base64');
  const authTag = Buffer.from(authTagB64, 'base64');
  const derivedKey = deriveKey(key, salt);

  const decipher = createDecipheriv(ALGORITHM, derivedKey, iv);
  decipher.setAuthTag(authTag);

  let plaintext: string = decipher.update(encryptedData, 'base64', 'utf8');
  plaintext += decipher.final('utf8');
  return plaintext;
}

/** Decrypt multiple fields in an object */
export function decryptFields<T extends Record<string, unknown>>(
  data: T,
  fields: (keyof T)[],
  encryptionKey?: string,
): T {
  const result = { ...data };
  for (const field of fields) {
    const value = data[field];
    if (typeof value === 'string' && value) {
      try {
        result[field] = decrypt(value, encryptionKey) as T[keyof T];
      } catch (err) {
        logger.warn({ field: String(field), err }, 'failed to decrypt field');
      }
    }
  }
  return result;
}
// --- END CUSTOM ---
