/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import { createCipheriv, randomBytes } from 'crypto';
import { ALGORITHM, IV_LENGTH, SALT_LENGTH, deriveKey } from './crypto-utils.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
/**
 * Encrypt sensitive data with AES-256-GCM
 * @returns Encrypted data in format: salt:iv:authTag:ciphertext (base64)
 */
export function encrypt(plaintext: string, encryptionKey?: string): string {
  const key = encryptionKey || process.env.ENCRYPTION_KEY;
  if (!key) throw new Error('ENCRYPTION_KEY environment variable is required');
  if (!plaintext) return '';

  const salt = randomBytes(SALT_LENGTH);
  const iv = randomBytes(IV_LENGTH);
  const derivedKey = deriveKey(key, salt);
  const cipher = createCipheriv(ALGORITHM, derivedKey, iv);

  let ciphertext = cipher.update(plaintext, 'utf8', 'base64');
  ciphertext += cipher.final('base64');
  const authTag = cipher.getAuthTag();

  return [
    salt.toString('base64'),
    iv.toString('base64'),
    authTag.toString('base64'),
    ciphertext,
  ].join(':');
}

/** Encrypt multiple fields in an object */
export function encryptFields<T extends Record<string, unknown>>(
  data: T,
  fields: (keyof T)[],
  encryptionKey?: string,
): T {
  const result = { ...data };
  for (const field of fields) {
    const value = data[field];
    if (typeof value === 'string' && value) {
      result[field] = encrypt(value, encryptionKey) as T[keyof T];
    }
  }
  return result;
}
// --- END CUSTOM ---
