/**
 * @generated by @flusk/cli from alert-channel.entity.ts
 * DO NOT EDIT - regenerate using: flusk g alert-channel.entity.ts
 */

import { Type, Static } from '@sinclair/typebox';
import { AlertChannelEntitySchema, BaseEntitySchema } from '@flusk/entities';

/**
 * TypeScript type for AlertChannelEntity
 * Generated from AlertChannelEntitySchema in entities package
 */
export type AlertChannelEntity = Static<typeof AlertChannelEntitySchema>;

/**
 * TypeScript type for BaseEntity
 */
export type BaseEntity = Static<typeof BaseEntitySchema>;

/**
 * JSON Schema for AlertChannelEntity
 * Use for validation and API documentation
 */
export const AlertChannelEntityJSONSchema = AlertChannelEntitySchema;

/**
 * Insert variant - excludes auto-generated fields (id, createdAt, updatedAt)
 */
export const AlertChannelInsertSchema = Type.Omit(AlertChannelEntitySchema, [
  'id',
  'createdAt',
  'updatedAt'
]);

export type AlertChannelInsert = Static<typeof AlertChannelInsertSchema>;

/**
 * Update variant - all fields optional except id
 */
export const AlertChannelUpdateSchema = Type.Composite([
  Type.Object({ id: Type.String({ format: 'uuid' }) }),
  Type.Partial(Type.Omit(AlertChannelEntitySchema, ['id', 'createdAt', 'updatedAt']))
]);

export type AlertChannelUpdate = Static<typeof AlertChannelUpdateSchema>;

/**
 * Query variant - all fields optional for flexible filtering
 */
export const AlertChannelQuerySchema = Type.Partial(AlertChannelEntitySchema);

export type AlertChannelQuery = Static<typeof AlertChannelQuerySchema>;
