/** @generated by @flusk/forge — types generator */
// --- BEGIN GENERATED (do not edit) ---

import { Type, Static } from '@sinclair/typebox';
import { AlertChannelEntitySchema } from '@flusk/entities';

export type AlertChannelEntity = Static<typeof AlertChannelEntitySchema>;

export const AlertChannelEntityJSONSchema = AlertChannelEntitySchema;

export const AlertChannelInsertSchema = Type.Omit(AlertChannelEntitySchema, [
  'id', 'createdAt', 'updatedAt',
]);

export type AlertChannelInsert = Static<typeof AlertChannelInsertSchema>;

export const AlertChannelUpdateSchema = Type.Composite([
  Type.Object({ id: Type.String({ format: 'uuid' }) }),
  Type.Partial(Type.Omit(AlertChannelEntitySchema, ['id', 'createdAt', 'updatedAt'])),
]);

export type AlertChannelUpdate = Static<typeof AlertChannelUpdateSchema>;

export const AlertChannelQuerySchema = Type.Partial(AlertChannelEntitySchema);

export type AlertChannelQuery = Static<typeof AlertChannelQuerySchema>;
// --- END GENERATED ---
