/**
 * @generated by @flusk/cli from conversion.entity.ts
 * DO NOT EDIT - regenerate using: flusk g conversion.entity.ts
 */

import { Type, Static } from '@sinclair/typebox';
import {
  ConversionEntitySchema,
  type ConversionType,
  type ConversionStatus,
  type ConversionConfig
} from '@flusk/entities';
import { BaseEntitySchema } from '@flusk/entities';

/**
 * TypeScript type for ConversionEntity
 * Generated from ConversionEntitySchema in entities package
 */
export type ConversionEntity = Static<typeof ConversionEntitySchema>;

/**
 * TypeScript type for BaseEntity
 */
export type BaseEntity = Static<typeof BaseEntitySchema>;

/**
 * JSON Schema for ConversionEntity
 * Use for validation and API documentation
 */
export const ConversionEntityJSONSchema = ConversionEntitySchema;

/**
 * Insert variant - excludes auto-generated fields (id, createdAt, updatedAt)
 */
export const ConversionInsertSchema = Type.Omit(ConversionEntitySchema, [
  'id',
  'createdAt',
  'updatedAt'
]);

export type ConversionInsert = Static<typeof ConversionInsertSchema>;

/**
 * Update variant - all fields optional except id
 */
export const ConversionUpdateSchema = Type.Composite([
  Type.Object({ id: Type.String({ format: 'uuid' }) }),
  Type.Partial(Type.Omit(ConversionEntitySchema, ['id', 'createdAt', 'updatedAt']))
]);

export type ConversionUpdate = Static<typeof ConversionUpdateSchema>;

/**
 * Query variant - all fields optional for flexible filtering
 */
export const ConversionQuerySchema = Type.Partial(ConversionEntitySchema);

export type ConversionQuery = Static<typeof ConversionQuerySchema>;

/**
 * Re-export enum types from entities
 */
export { type ConversionType, type ConversionStatus, type ConversionConfig };
