/**
 * @generated by @flusk/cli from pattern.entity.ts
 * DO NOT EDIT - regenerate using: flusk g pattern.entity.ts
 */

import { Type, Static } from '@sinclair/typebox';
import { PatternEntitySchema } from '@flusk/entities';
import { BaseEntitySchema } from '@flusk/entities';

/**
 * TypeScript type for PatternEntity
 * Generated from PatternEntitySchema in entities package
 */
export type PatternEntity = Static<typeof PatternEntitySchema>;

/**
 * TypeScript type for BaseEntity
 */
export type BaseEntity = Static<typeof BaseEntitySchema>;

/**
 * JSON Schema for PatternEntity
 * Use for validation and API documentation
 */
export const PatternEntityJSONSchema = PatternEntitySchema;

/**
 * Insert variant - excludes auto-generated fields (id, createdAt, updatedAt)
 */
export const PatternInsertSchema = Type.Omit(PatternEntitySchema, [
  'id',
  'createdAt',
  'updatedAt'
]);

export type PatternInsert = Static<typeof PatternInsertSchema>;

/**
 * Update variant - all fields optional except id
 */
export const PatternUpdateSchema = Type.Composite([
  Type.Object({ id: Type.String({ format: 'uuid' }) }),
  Type.Partial(Type.Omit(PatternEntitySchema, ['id', 'createdAt', 'updatedAt']))
]);

export type PatternUpdate = Static<typeof PatternUpdateSchema>;

/**
 * Query variant - all fields optional for flexible filtering
 */
export const PatternQuerySchema = Type.Partial(PatternEntitySchema);

export type PatternQuery = Static<typeof PatternQuerySchema>;
