/**
 * @generated by @flusk/cli from trace.entity.ts
 * DO NOT EDIT - regenerate using: flusk g trace.entity.ts
 */

import { Type, Static } from '@sinclair/typebox';
import { TraceEntitySchema, BaseEntitySchema } from '@flusk/entities';

/**
 * TypeScript type for TraceEntity
 * Generated from TraceEntitySchema in entities package
 */
export type TraceEntity = Static<typeof TraceEntitySchema>;

/**
 * TypeScript type for BaseEntity
 */
export type BaseEntity = Static<typeof BaseEntitySchema>;

/**
 * JSON Schema for TraceEntity
 * Use for validation and API documentation
 */
export const TraceEntityJSONSchema = TraceEntitySchema;

/**
 * Insert variant - excludes auto-generated fields (id, createdAt, updatedAt)
 */
export const TraceInsertSchema = Type.Omit(TraceEntitySchema, [
  'id',
  'createdAt',
  'updatedAt'
]);

export type TraceInsert = Static<typeof TraceInsertSchema>;

/**
 * Update variant - all fields optional except id
 */
export const TraceUpdateSchema = Type.Composite([
  Type.Object({ id: Type.String({ format: 'uuid' }) }),
  Type.Partial(Type.Omit(TraceEntitySchema, ['id', 'createdAt', 'updatedAt']))
]);

export type TraceUpdate = Static<typeof TraceUpdateSchema>;

/**
 * Query variant - all fields optional for flexible filtering
 */
export const TraceQuerySchema = Type.Partial(TraceEntitySchema);

export type TraceQuery = Static<typeof TraceQuerySchema>;
