# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.collection.sort_by import sort_by


def test_sort_ascending():
    assert sort_by([{"v":3},{"v":1},{"v":2}], "v", "asc") == [{"v":1},{"v":2},{"v":3}]


def test_sort_descending():
    assert sort_by([{"v":1},{"v":3},{"v":2}], "v", "desc") == [{"v":3},{"v":2},{"v":1}]
