# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.collection.filter_by import filter_by


def test_filter_by_model():
    assert filter_by([{"model":"gpt-4"},{"model":"gpt-3"},{"model":"gpt-4"}], "model", "gpt-4") == [{"model":"gpt-4"},{"model":"gpt-4"}]


def test_no_matches():
    assert filter_by([{"model":"gpt-3"}], "model", "gpt-4") == []
