/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { similarityScore } from '../similarity-score.function.js';

describe('similarityScore', () => {
  it('identical strings', () => {
    expect(similarityScore("hello world", "hello world")).toEqual(1);
  });

  it('no overlap', () => {
    expect(similarityScore("hello", "world")).toEqual(0);
  });

  it('partial overlap', () => {
    expect(similarityScore("hello world", "hello there")).toEqual(0.3333333333333333);
  });
});
