/**
 * @generated by @flusk/cli from conversion.entity.ts
 * DO NOT EDIT - regenerate using: flusk g conversion.entity.ts
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { Type } from '@sinclair/typebox';
import { ConversionEntitySchema } from '@flusk/entities';
import * as ConversionRepository from '@flusk/resources/repositories/conversion';

/**
 * Request schema for creating Conversion
 */
const CreateConversionSchema = Type.Omit(ConversionEntitySchema, [
  'id',
  'createdAt',
  'updatedAt'
]);

/**
 * Response schema for Conversion
 */
const ConversionResponseSchema = ConversionEntitySchema;

/**
 * Register Conversion routes
 */
export async function conversionRoutes(
  fastify: FastifyInstance
): Promise<void> {
  /**
   * POST /conversions
   * Create new conversion record
   */
  fastify.post(
    '/',
    {
      schema: {
        body: CreateConversionSchema,
        response: {
          201: ConversionResponseSchema
        },
        tags: ['Conversion'],
        description: 'Create a new conversion record'
      }
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const data = request.body as any;
      const created = await ConversionRepository.create(data);
      return reply.code(201).send(created);
    }
  );

  /**
   * GET /conversions/:id
   * Retrieve conversion by UUID
   */
  fastify.get(
    '/:id',
    {
      schema: {
        params: Type.Object({
          id: Type.String({ format: 'uuid' })
        }),
        response: {
          200: ConversionResponseSchema,
          404: Type.Object({ error: Type.String() })
        },
        tags: ['Conversion'],
        description: 'Get conversion by ID'
      }
    },
    async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
      const { id } = request.params;
      const entity = await ConversionRepository.findById(id);

      if (!entity) {
        return reply.code(404).send({ error: 'Conversion not found' });
      }

      return reply.code(200).send(entity);
    }
  );
}
