/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { Type, type TSchema } from '@sinclair/typebox';
import { LLMCallEntitySchema } from '@flusk/entities';
import { LLMCallRepository } from '@flusk/resources';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const CreateLLMCallSchema = Type.Omit(LLMCallEntitySchema as any, ['id', 'createdAt', 'updatedAt']);
const LLMCallResponseSchema = LLMCallEntitySchema;
const IdParamsSchema = Type.Object({ id: Type.String({ format: 'uuid' }) });
const NotFoundSchema = Type.Object({ error: Type.String() });
const ListQuerySchema = Type.Object({
  limit: Type.Optional(Type.Integer({ minimum: 1 })),
  offset: Type.Optional(Type.Integer({ minimum: 0 })),
});

export async function llmCallRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  const pool = fastify.pg.pool;

  fastify.post('/', {
    schema: {
      body: CreateLLMCallSchema,
      response: { 201: LLMCallResponseSchema as unknown as TSchema },
      tags: ['LLMCall'],
    },
  }, async (request, reply) => {
    const created = await LLMCallRepository.create(pool, request.body as any);
    return reply.code(201).send(created);
  });

  fastify.get('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 200: LLMCallResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['LLMCall'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const entity = await LLMCallRepository.findById(pool, id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(entity);
  });

  fastify.get('/', {
    schema: {
      querystring: ListQuerySchema,
      response: { 200: Type.Array(LLMCallResponseSchema as unknown as TSchema) },
      tags: ['LLMCall'],
    },
  }, async (_request, reply) => {
    // LLMCallRepository has no list; use findByPromptHash as stub
    return reply.code(200).send([]);
  });

  fastify.put('/:id', {
    schema: {
      params: IdParamsSchema,
      body: Type.Partial(CreateLLMCallSchema),
      response: { 200: LLMCallResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['LLMCall'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const updated = await LLMCallRepository.update(pool, id, request.body as any);
    if (!updated) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(updated);
  });

  fastify.delete('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 204: Type.Null(), 404: NotFoundSchema },
      tags: ['LLMCall'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const deleted = await LLMCallRepository.hardDelete(pool, id);
    if (!deleted) return reply.code(404).send({ error: 'Not found' });
    return reply.code(204).send();
  });
}

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
// --- END CUSTOM ---
