/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { Type, type TSchema } from '@sinclair/typebox';
import { OptimizationEntitySchema } from '@flusk/entities';
import { OptimizationRepository } from '@flusk/resources';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- TypeBox Type.Omit requires TObject cast
const CreateOptimizationSchema = Type.Omit(OptimizationEntitySchema as any, ['id', 'createdAt', 'updatedAt']);
const OptimizationResponseSchema = OptimizationEntitySchema;
const IdParamsSchema = Type.Object({ id: Type.String({ format: 'uuid' }) });
const NotFoundSchema = Type.Object({ error: Type.String() });
const ListQuerySchema = Type.Object({
  limit: Type.Optional(Type.Integer({ minimum: 1 })),
  offset: Type.Optional(Type.Integer({ minimum: 0 })),
});

export async function optimizationRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  fastify.post('/', {
    schema: {
      body: CreateOptimizationSchema,
      response: { 201: OptimizationResponseSchema as unknown as TSchema },
      tags: ['Optimization'],
    },
  }, async (request, reply) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- request body validated by schema
    const created = OptimizationRepository.createOptimization(fastify.db, request.body as any);
    return reply.code(201).send(created);
  });

  fastify.get('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 200: OptimizationResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['Optimization'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const entity = OptimizationRepository.findOptimizationById(fastify.db, id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(entity);
  });

  fastify.get('/', {
    schema: {
      querystring: ListQuerySchema,
      response: { 200: Type.Array(OptimizationResponseSchema as unknown as TSchema) },
      tags: ['Optimization'],
    },
  }, async (request, reply) => {
    const { limit, offset } = request.query as { limit?: number; offset?: number };
    const items = OptimizationRepository.listOptimizations(fastify.db, limit, offset);
    return reply.code(200).send(items);
  });

  fastify.put('/:id', {
    schema: {
      params: IdParamsSchema,
      body: Type.Partial(CreateOptimizationSchema),
      response: { 200: OptimizationResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['Optimization'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- request body validated by schema
    const updated = OptimizationRepository.updateOptimization(fastify.db, id, request.body as any);
    if (!updated) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(updated);
  });

  fastify.delete('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 204: Type.Null(), 404: NotFoundSchema },
      tags: ['Optimization'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const deleted = OptimizationRepository.deleteOptimization(fastify.db, id);
    if (!deleted) return reply.code(404).send({ error: 'Not found' });
    return reply.code(204).send();
  });
}

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
// --- END CUSTOM ---
