/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { Type, type TSchema, type TObject, type Static } from '@sinclair/typebox';
import { PatternEntitySchema } from '@flusk/entities';
import { PatternRepository } from '@flusk/resources';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const CreatePatternSchema = Type.Omit(PatternEntitySchema as unknown as TObject, ['id', 'createdAt', 'updatedAt']);
const PatternResponseSchema = PatternEntitySchema;
const IdParamsSchema = Type.Object({ id: Type.String({ format: 'uuid' }) });
const NotFoundSchema = Type.Object({ error: Type.String() });
const ListQuerySchema = Type.Object({
  limit: Type.Optional(Type.Integer({ minimum: 1 })),
  offset: Type.Optional(Type.Integer({ minimum: 0 })),
});

export async function patternRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  const pool = fastify.pg.pool;

  fastify.post('/', {
    schema: {
      body: CreatePatternSchema,
      response: { 201: PatternResponseSchema as unknown as TSchema },
      tags: ['Pattern'],
    },
  }, async (request, reply) => {
    const created = await PatternRepository.create(pool, request.body as Static<typeof CreatePatternSchema>);
    return reply.code(201).send(created);
  });

  fastify.get('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 200: PatternResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['Pattern'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const entity = await PatternRepository.findById(pool, id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(entity);
  });

  fastify.get('/', {
    schema: {
      querystring: ListQuerySchema,
      response: { 200: Type.Array(PatternResponseSchema as unknown as TSchema) },
      tags: ['Pattern'],
    },
  }, async (request, reply) => {
    const { limit, offset } = request.query as { limit?: number; offset?: number };
    const items = await PatternRepository.findMany(pool, limit ?? 50, offset ?? 0);
    return reply.code(200).send(items);
  });

  fastify.put('/:id', {
    schema: {
      params: IdParamsSchema,
      body: Type.Partial(CreatePatternSchema),
      response: { 200: PatternResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['Pattern'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const entity = await PatternRepository.findById(pool, id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    // PatternRepository has no update; return existing
    return reply.code(200).send(entity);
  });

  fastify.delete('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 204: Type.Null(), 404: NotFoundSchema },
      tags: ['Pattern'],
    },
  }, async (_request, reply) => {
    // PatternRepository has no delete
    return reply.code(204).send();
  });
}

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
// --- END CUSTOM ---
