/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { Type, type TSchema } from '@sinclair/typebox';
import { PromptVersionEntitySchema } from '@flusk/entities';
import { PromptVersionRepository } from '@flusk/resources';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const CreatePromptVersionSchema = Type.Omit(PromptVersionEntitySchema as any, ['id', 'createdAt', 'updatedAt']);
const PromptVersionResponseSchema = PromptVersionEntitySchema;
const IdParamsSchema = Type.Object({ id: Type.String({ format: 'uuid' }) });
const NotFoundSchema = Type.Object({ error: Type.String() });
const ListQuerySchema = Type.Object({
  limit: Type.Optional(Type.Integer({ minimum: 1 })),
  offset: Type.Optional(Type.Integer({ minimum: 0 })),
});

export async function promptVersionRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  fastify.post('/', {
    schema: {
      body: CreatePromptVersionSchema,
      response: { 201: PromptVersionResponseSchema as unknown as TSchema },
      tags: ['PromptVersion'],
    },
  }, async (request, reply) => {
    const created = PromptVersionRepository.createPromptVersion(fastify.db, request.body as any);
    return reply.code(201).send(created);
  });

  fastify.get('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 200: PromptVersionResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['PromptVersion'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const entity = PromptVersionRepository.findPromptVersionById(fastify.db, id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(entity);
  });

  fastify.get('/', {
    schema: {
      querystring: ListQuerySchema,
      response: { 200: Type.Array(PromptVersionResponseSchema as unknown as TSchema) },
      tags: ['PromptVersion'],
    },
  }, async (request, reply) => {
    const { limit, offset } = request.query as { limit?: number; offset?: number };
    const items = PromptVersionRepository.listPromptVersions(fastify.db, limit, offset);
    return reply.code(200).send(items);
  });

  fastify.put('/:id', {
    schema: {
      params: IdParamsSchema,
      body: Type.Partial(CreatePromptVersionSchema),
      response: { 200: PromptVersionResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['PromptVersion'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const updated = PromptVersionRepository.updatePromptVersion(fastify.db, id, request.body as any);
    if (!updated) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(updated);
  });

  fastify.delete('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 204: Type.Null(), 404: NotFoundSchema },
      tags: ['PromptVersion'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const deleted = PromptVersionRepository.deletePromptVersion(fastify.db, id);
    if (!deleted) return reply.code(404).send({ error: 'Not found' });
    return reply.code(204).send();
  });
}

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
// --- END CUSTOM ---
