/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyInstance } from 'fastify';
import { Type, type TSchema, type TObject, type Static } from '@sinclair/typebox';
import { RoutingRuleEntitySchema } from '@flusk/entities';
import { RoutingRuleRepository } from '@flusk/resources';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const CreateRoutingRuleSchema = Type.Omit(RoutingRuleEntitySchema as unknown as TObject, ['id', 'createdAt', 'updatedAt']);
const RoutingRuleResponseSchema = RoutingRuleEntitySchema;
const IdParamsSchema = Type.Object({ id: Type.String({ format: 'uuid' }) });
const NotFoundSchema = Type.Object({ error: Type.String() });
const ListQuerySchema = Type.Object({
  limit: Type.Optional(Type.Integer({ minimum: 1 })),
  offset: Type.Optional(Type.Integer({ minimum: 0 })),
});

export async function routingRuleRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  const pool = fastify.pg.pool;

  fastify.post('/', {
    schema: {
      body: CreateRoutingRuleSchema,
      response: { 201: RoutingRuleResponseSchema as unknown as TSchema },
      tags: ['RoutingRule'],
    },
  }, async (request, reply) => {
    const created = await RoutingRuleRepository.create(pool, request.body as Static<typeof CreateRoutingRuleSchema>);
    return reply.code(201).send(created);
  });

  fastify.get('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 200: RoutingRuleResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['RoutingRule'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const entity = await RoutingRuleRepository.findById(pool, id);
    if (!entity) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(entity);
  });

  fastify.get('/', {
    schema: {
      querystring: ListQuerySchema,
      response: { 200: Type.Array(RoutingRuleResponseSchema as unknown as TSchema) },
      tags: ['RoutingRule'],
    },
  }, async (_request, reply) => {
    const items = await RoutingRuleRepository.findByOrganization(pool, '');
    return reply.code(200).send(items);
  });

  fastify.put('/:id', {
    schema: {
      params: IdParamsSchema,
      body: Type.Partial(CreateRoutingRuleSchema),
      response: { 200: RoutingRuleResponseSchema as unknown as TSchema, 404: NotFoundSchema },
      tags: ['RoutingRule'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const updated = await RoutingRuleRepository.update(pool, id, request.body as Static<typeof CreateRoutingRuleSchema>);
    if (!updated) return reply.code(404).send({ error: 'Not found' });
    return reply.code(200).send(updated);
  });

  fastify.delete('/:id', {
    schema: {
      params: IdParamsSchema,
      response: { 204: Type.Null(), 404: NotFoundSchema },
      tags: ['RoutingRule'],
    },
  }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const deleted = await RoutingRuleRepository.deleteById(pool, id);
    if (!deleted) return reply.code(404).send({ error: 'Not found' });
    return reply.code(204).send();
  });
}

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
// --- END CUSTOM ---
