/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { extractTrigrams } from '../extract-trigrams.function.js';

describe('extractTrigrams', () => {
  it('extracts trigrams from sentence', () => {
    expect(extractTrigrams("the quick brown fox jumps")).toEqual(["the quick brown","quick brown fox","brown fox jumps"]);
  });

  it('handles short text', () => {
    expect(extractTrigrams("hello world")).toEqual(["hello world"]);
  });

  it('handles empty text', () => {
    expect(extractTrigrams("")).toEqual([]);
  });
});
