/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { formatAsSharegpt } from '../format-as-sharegpt.function.js';

describe('formatAsSharegpt', () => {
  it('formats with system', () => {
    expect(formatAsSharegpt("What is ML?", "ML is machine learning.", "Be concise.")).toEqual("{\"conversations\":[{\"from\":\"system\",\"value\":\"Be concise.\"},{\"from\":\"human\",\"value\":\"What is ML?\"},{\"from\":\"gpt\",\"value\":\"ML is machine learning.\"}]}");
  });

  it('formats without system', () => {
    expect(formatAsSharegpt("Hi", "Hello", "")).toEqual("{\"conversations\":[{\"from\":\"human\",\"value\":\"Hi\"},{\"from\":\"gpt\",\"value\":\"Hello\"}]}");
  });
});
