/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { jaccardSimilarity } from '../jaccard-similarity.function.js';

describe('jaccardSimilarity', () => {
  it('identical sets', () => {
    expect(jaccardSimilarity(["a","b","c"], ["a","b","c"])).toEqual(1);
  });

  it('no overlap', () => {
    expect(jaccardSimilarity(["a","b"], ["c","d"])).toEqual(0);
  });

  it('partial overlap', () => {
    expect(jaccardSimilarity(["a","b","c"], ["b","c","d"])).toEqual(0.5);
  });
});
