/**
 * @generated by @flusk/cli — test recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import { describe, it, expect, vi } from 'vitest';

vi.mock('./parse-llm-span.js', () => ({
  isGenAiSpan: vi.fn((span) =>
    span.attributes?.some((a: { key: string }) => a.key.startsWith('gen_ai.'))
  ),
  parseLlmSpan: vi.fn((span) => ({ model: 'gpt-4', spanId: span.spanId })),
}));

vi.mock('./map-span-to-llm-call.js', () => ({
  mapSpanToLlmCall: vi.fn((parsed) => ({ ...parsed, mapped: true })),
}));

vi.mock('@flusk/resources', () => ({
  LLMCallRepository: {
    createLLMCall: vi.fn((_db: unknown, data: unknown) => ({ id: '1', ...data as object })),
  },
  getDb: vi.fn(() => ({})),
}));

import { ingestTracesHandler } from './ingest-traces.js';
import { LLMCallRepository } from '@flusk/resources';

function makeApp() {
  const routes: Record<string, Function> = {};
  return {
    app: {
      post: vi.fn((_path: string, handler: Function) => { routes['post'] = handler; }),
      eventBus: { emit: vi.fn() },
    },
    routes,
  };
}

const genAiSpan = {
  spanId: 's1',
  attributes: [{ key: 'gen_ai.system', value: { stringValue: 'openai' } }],
};
const httpSpan = {
  spanId: 's2',
  attributes: [{ key: 'http.method', value: { stringValue: 'GET' } }],
};

describe('ingestTracesHandler', () => {
  it('filters only GenAI spans from mixed data', async () => {
    const { app, routes } = makeApp();
    await ingestTracesHandler(app as any);
    const handler = routes['post']!;
    const body = { resourceSpans: [{ scopeSpans: [{ spans: [genAiSpan, httpSpan] }] }] };
    const reply = { status: vi.fn().mockReturnThis(), send: vi.fn() };
    await handler({ body, headers: {}, log: { error: vi.fn() } }, reply);
    expect(LLMCallRepository.createLLMCall).toHaveBeenCalledTimes(1);
  });

  it('returns 200 with partialSuccess on empty input', async () => {
    const { app, routes } = makeApp();
    await ingestTracesHandler(app as any);
    const handler = routes['post']!;
    const body = { resourceSpans: [] };
    const reply = { status: vi.fn().mockReturnThis(), send: vi.fn() };
    await handler({ body, headers: {}, log: { error: vi.fn() } }, reply);
    expect(reply.status).toHaveBeenCalledWith(200);
    expect(reply.send).toHaveBeenCalledWith({ partialSuccess: {} });
  });

  it('handles failed spans gracefully', async () => {
    const { app, routes } = makeApp();
    await ingestTracesHandler(app as any);
    vi.mocked(LLMCallRepository.createLLMCall).mockImplementationOnce(() => { throw new Error('boom'); });
    const handler = routes['post']!;
    const body = { resourceSpans: [{ scopeSpans: [{ spans: [genAiSpan] }] }] };
    const logError = vi.fn();
    const reply = { status: vi.fn().mockReturnThis(), send: vi.fn() };
    await handler({ body, headers: {}, log: { error: logError } }, reply);
    expect(logError).toHaveBeenCalled();
    expect(reply.send).toHaveBeenCalledWith(
      expect.objectContaining({ partialSuccess: { rejectedSpans: 1 } })
    );
  });
});
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
