/**
 * @generated by @flusk/cli — sqlite-repo recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import type { AlertChannelEntity } from '@flusk/entities';
import { toISOString } from '../../../shared/map-row.js';

/** Convert SQLite row to AlertChannelEntity */
export function rowToEntity(row: Record<string, unknown>): AlertChannelEntity {
  return {
    id: row.id as string,
    createdAt: toISOString(row.created_at),
    updatedAt: toISOString(row.updated_at),
    name: row.name as string,
    channelType: row.channel_type as AlertChannelEntity['channelType'],
    config: JSON.parse(row.config as string),
    enabled: Boolean(row.enabled),
    severityFilter: row.severity_filter as AlertChannelEntity['severityFilter'],
  };
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
