"use strict";
/**
 * @generated by @flusk/cli — utility recipe
 */
// --- BEGIN GENERATED ---
/**
 * ASCII banner for Flusk CLI
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.printBanner = printBanner;
var chalk_1 = require("chalk");
var logo = [
    ' ┌──┬──┐',
    ' │  │  │',
    ' │  ├──┘',
    ' │  │   ',
    ' └──┘   ',
];
var VERSION = '0.1.0';
function printBanner() {
    var green = chalk_1.default.hex('#A3E635');
    var lines = logo.map(function (l) { return green(l); });
    lines[1] += "  ".concat(chalk_1.default.bold.hex('#A3E635')('flusk'));
    lines[2] += "  ".concat(chalk_1.default.dim("v".concat(VERSION)));
    console.log(lines.join('\n'));
    console.log();
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
