/**
 * @generated by @flusk/cli — utility recipe
 */
// --- BEGIN GENERATED ---
/**
 * Docker utility functions for infrastructure management
 */

import { execa } from 'execa';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

export type { DockerCheckResult, ServiceStatus } from './docker.types.js';
export { startServices, stopServices, resetServices, getLogs, getServicesStatus } from './docker-services.js';

import type { DockerCheckResult } from './docker.types.js';

/**
 * Check if Docker is installed and running
 */
export async function checkDocker(): Promise<DockerCheckResult> {
  const result: DockerCheckResult = {
    installed: false,
    running: false,
    composeAvailable: false,
  };

  try {
    const { stdout } = await execa('docker', ['--version']);
    result.installed = true;
    result.version = stdout.trim();

    await execa('docker', ['info']);
    result.running = true;

    await execa('docker', ['compose', 'version']);
    result.composeAvailable = true;
  } catch (_error) {
    // Docker not installed or not running
  }

  return result;
}

/**
 * Check if docker-compose.yml exists in project root
 */
export function checkDockerComposeFile(projectRoot: string = process.cwd()): boolean {
  const composePath = resolve(projectRoot, 'docker-compose.yml');
  return existsSync(composePath);
}
// --- END GENERATED ---
// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
