/**
 * @generated by @flusk/cli
 * Template for the root TUI app with navigation
 */

export function generateTuiAppTemplate(): string {
  return `/**
 * @generated by @flusk/cli — customize after generation
 * Root TUI App with keyboard navigation
 */

import React, { useState } from 'react';
import { render, Box, Text, useInput } from 'ink';

type Screen = 'overview' | 'patterns' | 'suggestions';

interface AppProps {
  endpoint: string;
  apiKey: string;
}

function App({ endpoint, apiKey }: AppProps) {
  const [screen, setScreen] = useState<Screen>('overview');

  useInput((input: string) => {
    if (input === '1') setScreen('overview');
    if (input === '2') setScreen('patterns');
    if (input === '3') setScreen('suggestions');
    if (input === 'q') process.exit(0);
  });

  return (
    <Box flexDirection="column">
      <Text bold>Flusk Dashboard</Text>
      <Text dimColor>
        [1] Overview  [2] Patterns  [3] Suggestions  [q] Quit
      </Text>
      <Box marginTop={1}>
        <Text>Current: {screen} | {endpoint}</Text>
      </Box>
    </Box>
  );
}

export async function renderDashboard(
  opts: { endpoint: string; apiKey?: string },
) {
  render(<App endpoint={opts.endpoint} apiKey={opts.apiKey || ''} />);
}
`;
}
