/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/conversation/is-abandoned.fn.yaml
 */

/**
 * Check if a conversation should be marked as abandoned
 */
export function isAbandoned(lastCallAtMs: number, nowMs: number, timeoutMinutes: number): boolean {
  return (nowMs - lastCallAtMs) > (timeoutMinutes * 60 * 1000);
}
