/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { StorageAdapter } from './storage.js';
import { createSqliteStorage } from './sqlite-storage.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
/**
 * Factory: create the appropriate storage adapter.
 * Currently only SQLite is supported (CLI-first architecture).
 */
export function createStorage(): StorageAdapter {
  return createSqliteStorage();
}
// --- END CUSTOM ---
