/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { StorageAdapter } from './storage.js';
import { getDb } from './sqlite/connection.js';
import { runMigrations } from './sqlite/migrations.js';
import * as LLMCallRepo from './sqlite/repositories/llm-call/index.js';
import * as AnalyzeSessionRepo from './sqlite/repositories/analyze-session/index.js';
import * as ProfileSessionRepo from './sqlite/repositories/profile-session/index.js';
import * as PatternRepo from './sqlite/repositories/performance-pattern/index.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
import { hardenPermissions } from './sqlite/harden-permissions.js';
import * as ConversationRepo from './sqlite/repositories/conversation/index.js';
import * as TrainingPairRepo from './sqlite/repositories/training-pair/index.js';
import * as TrainingDatasetRepo from './sqlite/repositories/training-dataset/index.js';

/**
 * Create a SQLite-backed storage adapter.
 * Runs migrations on first call.
 */
export function createSqliteStorage(dbPath?: string): StorageAdapter {
  const db = getDb(dbPath);
  hardenPermissions(dbPath ?? process.env.HOME + '/.flusk/data.db');
  runMigrations(db);

  return {
    mode: 'sqlite',
    llmCalls: {
      create: (data) => LLMCallRepo.create(db, data),
      findById: (id) => LLMCallRepo.findById(db, id),
      findByPromptHash: (hash) => LLMCallRepo.findByPromptHash(db, hash),
      list: (limit, offset) => LLMCallRepo.list(db, limit, offset),
      listBySessionId: (sessionId) => LLMCallRepo.listBySessionId(db, sessionId),
      countByModel: () => LLMCallRepo.countByModel(db),
      countByModelBySessionId: (sessionId) => LLMCallRepo.countByModelBySessionId(db, sessionId),
      sumCost: () => LLMCallRepo.sumCost(db),
      sumCostBySessionId: (sessionId) => LLMCallRepo.sumCostBySessionId(db, sessionId),
      sumCostSince: (since: string) => LLMCallRepo.sumCostSince(db, since),
      countDuplicates: () => LLMCallRepo.countDuplicates(db),
      listByConversationId: (cid: string) => LLMCallRepo.listByConversationId(db, cid),
    },
    analyzeSessions: {
      create: (data) => AnalyzeSessionRepo.create(db, data),
      findById: (id) => AnalyzeSessionRepo.findById(db, id),
      list: (limit, offset) => AnalyzeSessionRepo.list(db, limit, offset),
      update: (id, data) => AnalyzeSessionRepo.update(db, id, data),
    },
    profileSessions: {
      create: (data) => ProfileSessionRepo.create(db, data),
      findById: (id) => ProfileSessionRepo.findById(db, id),
      list: (limit, offset) => ProfileSessionRepo.list(db, limit, offset),
    },
    patterns: {
      create: (data) => PatternRepo.create(db, data),
      findByProfileId: (id) => PatternRepo.findByProfileId(db, id),
      list: (limit, offset) => PatternRepo.list(db, limit, offset),
    },
    conversations: {
      create: (data) => ConversationRepo.create(db, data),
      findById: (id) => ConversationRepo.findById(db, id),
      findByExternalId: (eid) => ConversationRepo.findByExternalId(db, eid),
      list: (limit, offset) => ConversationRepo.list(db, limit, offset),
      findAbandoned: (before) => ConversationRepo.findAbandoned(db, before),
      topByCost: () => ConversationRepo.topByCost(db),
      topByTurns: () => ConversationRepo.topByTurns(db),
      topByTokens: () => ConversationRepo.topByTokens(db),
      update: (id, data) => ConversationRepo.update(db, id, data),
    },
    trainingPairs: {
      create: (data) => TrainingPairRepo.create(db, data),
      findById: (id) => TrainingPairRepo.findById(db, id),
      list: (limit, offset) => TrainingPairRepo.list(db, limit, offset),
      listByModel: (model) => TrainingPairRepo.listByModel(db, model),
      findByCluster: (cluster) => TrainingPairRepo.findByCluster(db, cluster),
      countByTenant: (tenantId) => TrainingPairRepo.countByTenant(db, tenantId),
      countByModelGrouped: () => TrainingPairRepo.countByModelGrouped(db),
      countByClusterGrouped: () => TrainingPairRepo.countByClusterGrouped(db),
      update: (id, data) => TrainingPairRepo.update(db, id, data),
    },
    trainingDatasets: {
      create: (data) => TrainingDatasetRepo.create(db, data),
      findById: (id) => TrainingDatasetRepo.findById(db, id),
      list: (limit, offset) => TrainingDatasetRepo.list(db, limit, offset),
      update: (id, data) => TrainingDatasetRepo.update(db, id, data),
    },
  };
}
// --- END CUSTOM ---
