/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { Pool } from 'pg';
import { ProfileSessionEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
/**
 * Find profile sessions within a time range
 */
export async function findByTimeRange(
  pool: Pool,
  startTime: string,
  endTime: string
): Promise<ProfileSessionEntity[]> {
  const query = `
    SELECT * FROM profile_sessions
    WHERE started_at BETWEEN $1 AND $2
    ORDER BY started_at DESC
  `;
  const result = await pool.query(query, [startTime, endTime]);
  return result.rows.map(rowToEntity);
}
// --- END CUSTOM ---
