/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { Pool } from 'pg';
import type { RoutingRuleEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export async function findByOrganization(
  pool: Pool,
  organizationId: string
): Promise<RoutingRuleEntity[]> {
  const result = await pool.query(
    'SELECT * FROM routing_rules WHERE organization_id = $1 ORDER BY created_at DESC',
    [organizationId]
  );
  return result.rows.map(rowToEntity);
}
// --- END CUSTOM ---
