/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { Pool } from 'pg';
import type { RoutingRuleEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export async function findById(
  pool: Pool,
  id: string
): Promise<RoutingRuleEntity | null> {
  const result = await pool.query(
    'SELECT * FROM routing_rules WHERE id = $1',
    [id]
  );
  return result.rows[0] ? rowToEntity(result.rows[0]) : null;
}
// --- END CUSTOM ---
