/**
 * Business logic generator — file content templates.
 */

export function exampleFunctionContent(
  entityName: string,
  pascalName: string,
): string {
  return `/**
 * @generated by @flusk/cli from ${entityName}.entity.ts
 * Business logic stub - implement your domain logic here
 */

import { ${pascalName}Entity } from '@flusk/types';

/**
 * Example validation function for ${pascalName}
 * Pure function - no side effects, no I/O
 */
export function validate${pascalName}(
  entity: Partial<${pascalName}Entity>
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  // TODO: Add validation logic
  // Example:
  // if (!entity.someField) {
  //   errors.push('someField is required');
  // }

  return {
    valid: errors.length === 0,
    errors
  };
}
`;
}

export function indexContent(
  entityName: string,
  pascalName: string,
): string {
  return `/**
 * @generated by @flusk/cli from ${entityName}.entity.ts
 */

export { validate${pascalName} } from './validate-${entityName}.function.js';
`;
}
