/**
 * Function generator — reads .fn.yaml and emits TypeScript function + tests.
 *
 * WHY: Pure functions are declared as YAML definitions so they can be
 * generated consistently in TypeScript and Python from a single source.
 */

import { resolve } from 'node:path';
import { writeFile, mkdir, readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { parse } from 'yaml';
import { toKebabCase } from './utils.js';

export interface FnInput {
  type: string;
  description: string;
}

export interface FnSchema {
  name: string;
  namespace: string;
  description: string;
  pure: boolean;
  generic?: boolean;
  typeParams?: string[];
  input: Record<string, FnInput>;
  output: { type: string; description: string };
  body: string | { steps: Array<{ name?: string; expr?: string; return?: string } | { return: string }> };
  tests: Array<{ name: string; input: Record<string, unknown>; expected: unknown }>;
}

export interface FnGenResult {
  files: Array<{ path: string; action: 'created' | 'updated' }>;
}

/** Load and parse a .fn.yaml file */
export async function loadFnSchema(yamlPath: string): Promise<FnSchema> {
  const raw = await readFile(yamlPath, 'utf-8');
  return parse(raw) as FnSchema;
}

/** Render TypeScript function body from schema */
function renderBody(schema: FnSchema): string {
  const { body } = schema;
  if (typeof body === 'string') {
    return body.trim();
  }
  // Multi-step body
  const steps = body.steps;
  const lines: string[] = [];
  for (const step of steps) {
    if ('return' in step && step.return && !('name' in step)) {
      lines.push(`  return ${(step.return as string).trim()};`);
    } else if ('name' in step && step.name) {
      lines.push(`  const ${step.name} = ${(step.expr ?? '').trim()};`);
    }
  }
  return `{\n${lines.join('\n')}\n}`;
}

/** Render param list for function signature */
function renderParams(schema: FnSchema): string {
  return Object.entries(schema.input)
    .map(([k, v]) => `${k}: ${v.type}`)
    .join(', ');
}

/** Render TypeScript function file content */
export function renderFunctionContent(schema: FnSchema): string {
  const typeParam = schema.generic && schema.typeParams?.length
    ? `<${schema.typeParams.join(', ')}>`
    : '';
  const params = renderParams(schema);
  const returnType = schema.output.type;
  const body = renderBody(schema);

  const isSimpleExpr = typeof schema.body === 'string' || (
    typeof schema.body === 'object' && !schema.body.steps.some(s => 'name' in s)
  );

  const bodyStr = isSimpleExpr && typeof schema.body === 'string'
    ? `  return ${body};`
    : body.startsWith('{') ? body.slice(1, -1).trim().split('\n').map(l => `  ${l}`).join('\n')
    : `  return ${body};`;

  return `/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/${schema.namespace}/${toKebabCase(schema.name)}.fn.yaml
 */

/**
 * ${schema.description}
 */
export function ${schema.name}${typeParam}(${params}): ${returnType} {
${bodyStr}
}
`;
}

/** Render vitest test file for a function */
export function renderTestContent(schema: FnSchema): string {
  const kebab = toKebabCase(schema.name);
  const testCases = schema.tests.map((t) => {
    const args = Object.values(t.input)
      .map((v) => JSON.stringify(v))
      .join(', ');
    const expected = JSON.stringify(t.expected);
    return `  it('${t.name}', () => {
    expect(${schema.name}(${args})).toEqual(${expected});
  });`;
  }).join('\n\n');

  return `/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { ${schema.name} } from '../${kebab}.function.js';

describe('${schema.name}', () => {
${testCases}
});
`;
}

/** Render namespace barrel index.ts */
export function renderNamespaceBarrel(names: string[]): string {
  const exports = names.map(n => `export * from './${n}.function.js';`).join('\n');
  return `/**
 * @generated by @flusk/cli — function generator
 */
${exports}
`;
}

/** Render primitives master barrel */
export function renderPrimitivesBarrel(namespaces: string[]): string {
  const exports = namespaces.map(ns => `export * from './${ns}/index.js';`).join('\n');
  return `/**
 * @generated by @flusk/cli — function generator
 */
${exports}
`;
}

/** Generate a single function from a .fn.yaml path */
export async function generateFunction(
  yamlPath: string,
  projectRoot: string,
): Promise<FnGenResult> {
  const schema = await loadFnSchema(yamlPath);
  const kebab = toKebabCase(schema.name);
  const result: FnGenResult = { files: [] };

  const nsDir = resolve(projectRoot, `packages/business-logic/src/primitives/${schema.namespace}`);
  const testDir = resolve(nsDir, '__tests__');
  await mkdir(testDir, { recursive: true });

  // Function file (kebab-case filename, camelCase export)
  const fnPath = resolve(nsDir, `${kebab}.function.ts`);
  const fnContent = renderFunctionContent(schema);
  const fnAction = existsSync(fnPath) ? 'updated' : 'created';
  await writeFile(fnPath, fnContent, 'utf-8');
  result.files.push({ path: `packages/business-logic/src/primitives/${schema.namespace}/${kebab}.function.ts`, action: fnAction });

  // Test file
  const testPath = resolve(testDir, `${kebab}.function.test.ts`);
  const testContent = renderTestContent(schema);
  const testAction = existsSync(testPath) ? 'updated' : 'created';
  await writeFile(testPath, testContent, 'utf-8');
  result.files.push({ path: `packages/business-logic/src/primitives/${schema.namespace}/__tests__/${kebab}.function.test.ts`, action: testAction });

  return result;
}

/** Regenerate namespace barrel after all functions in a namespace are generated */
export async function updateNamespaceBarrel(
  namespace: string,
  projectRoot: string,
): Promise<{ path: string; action: 'created' | 'updated' }> {
  const nsDir = resolve(projectRoot, `packages/business-logic/src/primitives/${namespace}`);
  const files = await readdir(nsDir);
  const names = files
    .filter(f => f.endsWith('.function.ts'))
    .map(f => f.replace('.function.ts', ''));
  const content = renderNamespaceBarrel(names);
  const indexPath = resolve(nsDir, 'index.ts');
  const action = existsSync(indexPath) ? 'updated' : 'created';
  await writeFile(indexPath, content, 'utf-8');
  return { path: `packages/business-logic/src/primitives/${namespace}/index.ts`, action };
}

/** Regenerate the primitives master barrel */
export async function updatePrimitivesBarrel(
  namespaces: string[],
  projectRoot: string,
): Promise<{ path: string; action: 'created' | 'updated' }> {
  const primDir = resolve(projectRoot, 'packages/business-logic/src/primitives');
  await mkdir(primDir, { recursive: true });
  const content = renderPrimitivesBarrel(namespaces);
  const indexPath = resolve(primDir, 'index.ts');
  const action = existsSync(indexPath) ? 'updated' : 'created';
  await writeFile(indexPath, content, 'utf-8');
  return { path: 'packages/business-logic/src/primitives/index.ts', action };
}
