/**
 * Unit tests for otel-hook generator
 */

import { test, describe } from 'node:test';
import assert from 'node:assert';
import { generateOtelHookContent, generateOtelHookTestContent } from './otel-hook.generator.js';

describe('OTel Hook Generator', () => {
  test('generates SpanProcessor class', () => {
    const content = generateOtelHookContent({ name: 'auto-profile' });
    assert.ok(content.includes('class AutoProfileHook'));
    assert.ok(content.includes('implements SpanProcessor'));
    assert.ok(content.includes('onStart'));
    assert.ok(content.includes('onEnd'));
    assert.ok(content.includes('shutdown'));
    assert.ok(content.includes('forceFlush'));
  });

  test('includes @generated header', () => {
    const content = generateOtelHookContent({ name: 'test' });
    assert.ok(content.includes('@generated by @flusk/cli'));
  });

  test('adds span filter when specified', () => {
    const content = generateOtelHookContent({ name: 'test', spanFilter: 'gen_ai,openai' });
    assert.ok(content.includes('SPAN_PREFIXES'));
    assert.ok(content.includes("'gen_ai'"));
    assert.ok(content.includes("'openai'"));
  });

  test('generates test file', () => {
    const content = generateOtelHookTestContent('auto-profile');
    assert.ok(content.includes('AutoProfileHook'));
  });
});
