/**
 * OTel hook content templates — hook class and filter block.
 */

import { toPascalCase } from './utils.js';

export function generateOtelHookContent(opts: {
  name: string;
  spanFilter?: string;
}): string {
  const pascal = toPascalCase(opts.name);
  const filterBlock = opts.spanFilter
    ? generateFilterBlock(opts.spanFilter)
    : '';

  return `/**
 * @generated by @flusk/cli
 */
import type {
  ReadableSpan,
  Span,
  SpanProcessor,
} from '@opentelemetry/sdk-trace-base';
import { getLogger } from '@flusk/logger';

const logger = getLogger().child({ module: '${opts.name}-hook' });
${filterBlock}
export class ${pascal}Hook implements SpanProcessor {
  onStart(span: Span): void {
    logger.debug({ spanName: (span as unknown as { name: string }).name }, 'span started');
    // TODO: handle span start
  }

  onEnd(span: ReadableSpan): void {
    logger.debug({ spanName: span.name }, 'span ended');
    // TODO: handle span end
  }

  async shutdown(): Promise<void> {
    logger.info('${opts.name} hook shutting down');
  }

  async forceFlush(): Promise<void> {
    // no-op
  }
}
`;
}

function generateFilterBlock(filter: string): string {
  const prefixes = filter.split(',').map((p) => `'${p.trim()}'`);
  return `
const SPAN_PREFIXES = [${prefixes.join(', ')}];

function matchesFilter(span: Span): boolean {
  const name = (span as unknown as { name: string }).name ?? '';
  return SPAN_PREFIXES.some((p) => name.toLowerCase().includes(p));
}
`;
}

export function generateOtelHookTestContent(name: string): string {
  const pascal = toPascalCase(name);
  return `/**
 * @generated by @flusk/cli
 */
import { describe, it, expect } from 'vitest';
import { ${pascal}Hook } from '../${name}.hook.js';

describe('${pascal}Hook', () => {
  it('should implement SpanProcessor interface', () => {
    const hook = new ${pascal}Hook();
    expect(hook.onStart).toBeDefined();
    expect(hook.onEnd).toBeDefined();
    expect(hook.shutdown).toBeDefined();
    expect(hook.forceFlush).toBeDefined();
  });
});
`;
}
