/**
 * Template: instrumentation test file
 */
import type { ProviderYaml } from './provider-yaml.types.js';
import { toPascalCase } from './utils.js';

export function renderInstrumentationTest(cfg: ProviderYaml): string {
  const pascal = toPascalCase(cfg.name);
  const fnName = `patch${pascal}`;

  return `/**
 * @generated by @flusk/cli — provider generator
 */
import { describe, it, expect } from 'vitest';
import { ${fnName} } from './${cfg.name}.js';

describe('${cfg.name} instrumentation', () => {
  it('exports patch function', () => {
    expect(typeof ${fnName}).toBe('function');
  });

  it('does not throw when sdk is missing', () => {
    expect(() => ${fnName}()).not.toThrow();
  });
});
`;
}
