/**
 * Template: OTel instrumentation file for an LLM provider
 */
import type { ProviderYaml } from './provider-yaml.types.js';
import { toPascalCase } from './utils.js';

export function renderInstrumentation(cfg: ProviderYaml): string {
  const pascal = toPascalCase(cfg.name);
  const method = cfg.methods[0];
  const tracerName = `flusk-${cfg.name}`;
  const protoPath = method.path; // e.g. Messages.prototype.create
  const parts = protoPath.split('.');
  const className = parts[0]; // e.g. Messages
  const methodName = parts[parts.length - 1]; // e.g. create

  return `/**
 * @generated by @flusk/cli — provider generator
 * ${cfg.displayName} SDK instrumentation — gen_ai.* spans
 */
import { trace, SpanKind, SpanStatusCode, context } from '@opentelemetry/api';

const TRACER_NAME = '${tracerName}';

export function patch${pascal}(): void {
  try {
    import('${cfg.sdkPackage}').then((mod) => {
      const Sdk = mod.default || mod;
      patchMethod(Sdk);
    }).catch(() => { /* sdk not installed */ });
  } catch { /* ignore */ }
}

function patchMethod(Sdk: any): void {
  const proto = Sdk?.${className}?.prototype;
  if (!proto || proto.__flusk_patched) return;
  const original = proto.${methodName};
  if (typeof original !== 'function') return;

  proto.${methodName} = function patched(this: any, body: any, opts?: any) {
    const tracer = trace.getTracer(TRACER_NAME);
    const model = body?.model || 'unknown';

    return tracer.startActiveSpan(
      \`${cfg.name} \${model}\`,
      { kind: SpanKind.CLIENT },
      context.active(),
      async (span) => {
        span.setAttribute('gen_ai.system', '${cfg.spans.system}');
        span.setAttribute('gen_ai.request.model', model);
        try {
          const result = await original.call(this, body, opts);
          if (body?.${method.streamParam} && result?.[Symbol.asyncIterator]) {
            return wrapStream(result, span);
          }
          setResponseAttrs(span, result);
          span.setStatus({ code: SpanStatusCode.OK });
          span.end();
          return result;
        } catch (err: any) {
          span.setStatus({ code: SpanStatusCode.ERROR, message: err?.message });
          span.end();
          throw err;
        }
      },
    );
  };
  proto.__flusk_patched = true;
}

function wrapStream(result: any, span: any): any {
  let inputTokens = 0, outputTokens = 0;
  const orig = result[Symbol.asyncIterator].bind(result);
  result[Symbol.asyncIterator] = async function* () {
    for await (const chunk of orig()) {
      if (chunk.usage) {
        inputTokens = chunk.usage.input_tokens ?? chunk.usage.prompt_tokens ?? 0;
        outputTokens = chunk.usage.output_tokens ?? chunk.usage.completion_tokens ?? 0;
      }
      yield chunk;
    }
    span.setAttribute('gen_ai.usage.input_tokens', inputTokens);
    span.setAttribute('gen_ai.usage.output_tokens', outputTokens);
    span.setStatus({ code: SpanStatusCode.OK });
    span.end();
  };
  return result;
}

function setResponseAttrs(span: any, result: any): void {
  if (result?.model) span.setAttribute('gen_ai.response.model', result.model);
  const u = result?.usage;
  if (u) {
    span.setAttribute('gen_ai.usage.input_tokens', u.input_tokens ?? u.prompt_tokens ?? 0);
    span.setAttribute('gen_ai.usage.output_tokens', u.output_tokens ?? u.completion_tokens ?? 0);
  }
}
`;
}
