/**
 * @generated by @flusk/cli — middleware recipe
 */

// --- BEGIN GENERATED ---
import type { FastifyError, FastifyReply, FastifyRequest } from 'fastify';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
/**
 * Error Handler Middleware
 * Maps errors to HTTP status codes and returns structured JSON errors
 *
 * Error handling strategy:
 * - Validation errors (400)
 * - Not found errors (404)
 * - Business logic errors (400/409)
 * - Internal server errors (500)
 */

interface ErrorResponse {
  error: {
    message: string;
    code: string;
    statusCode: number;
    details?: unknown;
  };
}

/**
 * Global error handler for Fastify
 * Attaches to setErrorHandler hook
 */
export async function errorHandler(
  error: FastifyError,
  request: FastifyRequest,
  reply: FastifyReply
): Promise<void> {
  // Log error for debugging
  request.log.error(
    {
      err: error,
      url: request.url,
      method: request.method,
      requestId: request.id
    },
    'Request error'
  );

  // Determine status code
  const statusCode = error.statusCode || 500;

  // Map error code for client
  const errorCode = mapErrorCode(error);

  const isProduction = process.env.NODE_ENV === 'production';

  // Build structured error response
  // In production, never leak internal details for server errors
  const safeMessage = isProduction
    ? (statusCode >= 500 ? 'Internal Server Error' : (error.validation ? 'Validation Error' : 'Request Error'))
    : (error.message || 'Internal Server Error');

  const response: ErrorResponse = {
    error: {
      message: safeMessage,
      code: errorCode,
      statusCode,
      // Include validation details only in non-production
      ...(!isProduction && error.validation && { details: error.validation }),
      // Include stack trace only in development
      ...(!isProduction && error.stack && { details: error.stack })
    }
  };

  // Send response
  await reply.status(statusCode).send(response);
}

/**
 * Map error to a client-friendly error code
 */
function mapErrorCode(error: FastifyError): string {
  // Fastify validation errors
  if (error.validation) {
    return 'VALIDATION_ERROR';
  }

  // HTTP status-based codes
  if (error.statusCode === 404) {
    return 'NOT_FOUND';
  }

  if (error.statusCode === 401) {
    return 'UNAUTHORIZED';
  }

  if (error.statusCode === 403) {
    return 'FORBIDDEN';
  }

  if (error.statusCode === 409) {
    return 'CONFLICT';
  }

  if (error.statusCode && error.statusCode >= 400 && error.statusCode < 500) {
    return 'BAD_REQUEST';
  }

  // Default to internal server error
  return 'INTERNAL_SERVER_ERROR';
}
// --- END CUSTOM ---
