# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/training/formatAsAlpaca.fn.yaml

def format_as_alpaca(prompt: str, completion: str, system_prompt: str) -> str:
    """Format a training pair as Alpaca format for fine-tuning"""
    raise NotImplementedError("format_as_alpaca — implement from YAML body")
