# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/training/formatAsSharegpt.fn.yaml

def format_as_sharegpt(prompt: str, completion: str, system_prompt: str) -> str:
    """Format a training pair as ShareGPT format for fine-tuning"""
    raise NotImplementedError("format_as_sharegpt — implement from YAML body")
