# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/training/shouldCollect.fn.yaml

def should_collect(provider: str, model: str, prompt: str, completion: str, status: str, teacher_models: list[str]) -> bool:
    """Determine if an LLM call should be collected as training data"""
    raise NotImplementedError("should_collect — implement from YAML body")
