/**
 * @generated by @flusk/cli — function generator
 */
import { describe, it, expect } from 'vitest';
import { calculateCost } from '../calculate-cost.function.js';

describe('calculateCost', () => {
  it('basic calculation', () => {
    expect(calculateCost(100, 50, 0.001, 0.002)).toEqual(0.2);
  });

  it('zero tokens', () => {
    expect(calculateCost(0, 0, 0.001, 0.002)).toEqual(0);
  });

  it('input only', () => {
    expect(calculateCost(1000, 0, 0.003, 0.015)).toEqual(3);
  });
});
