/**
 * @generated by @flusk/forge — pipeline generator
 * Compare current spend to configured budget thresholds and flag overages
 * Source: packages/schema/pipelines/budget-check.pipeline.yaml
 */

// --- BEGIN GENERATED (do not edit) ---
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck — generated pipeline with dynamic types
import { getLogger } from '@flusk/logger';


const log = getLogger().child({ pipeline: 'budgetCheck' });

export interface BudgetCheckInput {
  calls: any[];
  dailyLimit: number;
  monthlyLimit: number;
}

export interface BudgetCheckOutput {
  dailySpend: number;
  monthlySpend: number;
  dailyUtilization: number;
  monthlyUtilization: number;
  alerts: any[];
  status: string;
}

export function budgetCheck(input: BudgetCheckInput): BudgetCheckOutput {
  log.debug({ pipeline: 'budgetCheck' }, 'pipeline start');

  // Step: today-start
  const todayStart = (() => {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth(), d.getDate()).toISOString();
})();
  log.debug({ step: 'today-start' }, 'today-start complete');

  // Step: daily-calls
  const dailyCalls = input.calls.filter(c => c.createdAt && c.createdAt >= todayStart);
  log.debug({ step: 'daily-calls' }, 'daily-calls complete');

  // Step: daily-spend
  const dailySpend = dailyCalls.reduce((s, c) => s + (c.cost ?? 0), 0);
  log.debug({ step: 'daily-spend' }, 'daily-spend complete');

  // Step: monthly-spend
  const monthlySpend = input.calls.reduce((s, c) => s + (c.cost ?? 0), 0);
  log.debug({ step: 'monthly-spend' }, 'monthly-spend complete');

  // Step: daily-util
  const dailyUtilization = input.dailyLimit > 0 ? (dailySpend / input.dailyLimit) * 100 : 0;
  log.debug({ step: 'daily-util' }, 'daily-util complete');

  // Step: monthly-util
  const monthlyUtilization = input.monthlyLimit > 0 ? (monthlySpend / input.monthlyLimit) * 100 : 0;
  log.debug({ step: 'monthly-util' }, 'monthly-util complete');

  // Step: build-alerts
  const alerts = (() => {
  const alerts = [];
  if (dailyUtilization >= 100) alerts.push({ level: 'exceeded', scope: 'daily', spend: dailySpend, limit: input.dailyLimit });
  else if (dailyUtilization >= 80) alerts.push({ level: 'warning', scope: 'daily', spend: dailySpend, limit: input.dailyLimit });
  if (monthlyUtilization >= 100) alerts.push({ level: 'exceeded', scope: 'monthly', spend: monthlySpend, limit: input.monthlyLimit });
  else if (monthlyUtilization >= 80) alerts.push({ level: 'warning', scope: 'monthly', spend: monthlySpend, limit: input.monthlyLimit });
  return alerts;
})();
  log.debug({ step: 'build-alerts' }, 'build-alerts complete');

  // Step: status
  const status = alerts.some(a => a.level === 'exceeded') ? 'exceeded'
  : alerts.length > 0 ? 'warning' : 'ok';
  log.debug({ step: 'status' }, 'status complete');

  // Step: return
  return {
    dailySpend: dailySpend,
    monthlySpend: monthlySpend,
    dailyUtilization: dailyUtilization,
    monthlyUtilization: monthlyUtilization,
    alerts: alerts,
    status: status,
  };
}
// --- END GENERATED ---
