/**
 * @generated by @flusk/forge — pipeline generator
 * Group LLM calls by conversation_id and calculate per-conversation costs
 */
// --- BEGIN CUSTOM ---
import type { LLMCallEntity } from '@flusk/entities';

export interface ConversationCost {
  conversationId: string;
  callCount: number;
  totalCost: number;
  totalTokens: number;
  models: string[];
}

export interface ConversationCostReport {
  conversations: ConversationCost[];
  totalConversations: number;
  avgCostPerConversation: number;
  maxCostConversation: ConversationCost | null;
}

export function conversationCostGrouping(
  calls: LLMCallEntity[],
): ConversationCostReport {
  const groups = new Map<string, LLMCallEntity[]>();
  for (const c of calls) {
    const cid = c.conversationId ?? 'ungrouped';
    const group = groups.get(cid) ?? [];
    group.push(c);
    groups.set(cid, group);
  }

  const conversations: ConversationCost[] = [...groups.entries()]
    .filter(([id]) => id !== 'ungrouped')
    .map(([id, items]) => {
      const t = items as Array<LLMCallEntity & { tokens?: Record<string, number> }>;
      return {
        conversationId: id,
        callCount: items.length,
        totalCost: items.reduce((s, c) => s + (c.cost ?? 0), 0),
        totalTokens: t.reduce((s, c) => s + (c.tokens?.total ?? 0), 0),
        models: [...new Set(items.map(c => c.model))],
      };
    })
    .sort((a, b) => b.totalCost - a.totalCost);

  const totalCost = conversations.reduce((s, c) => s + c.totalCost, 0);

  return {
    conversations,
    totalConversations: conversations.length,
    avgCostPerConversation: conversations.length > 0 ? totalCost / conversations.length : 0,
    maxCostConversation: conversations[0] ?? null,
  };
}
// --- END CUSTOM ---
