/**
 * @generated by @flusk/forge — pipeline generator
 * Calculate cost breakdown by model for an analysis session
 * Source: packages/schema/pipelines/cost-summary.pipeline.yaml
 */

// --- BEGIN GENERATED (do not edit) ---
// @ts-nocheck — generated pipeline with dynamic expr: steps
import { getLogger } from '@flusk/logger';
import type { LLMCallEntity } from '@flusk/entities';

const log = getLogger().child({ pipeline: 'costSummary' });

export interface CostSummaryInput {
  calls: LLMCallEntity[];
}

export interface CostSummaryOutput {
  totalCost: number;
  callCount: number;
  byModel: Record<string, { count: number; cost: number }>;
  avgCostPerCall: number;
}

export function costSummary(input: CostSummaryInput): CostSummaryOutput {
  log.debug({ pipeline: 'costSummary' }, 'pipeline start');

  // Step: total-cost
  const totalCost = input.calls.reduce((s, c) => s + (c.cost ?? 0), 0);
  log.debug({ step: 'total-cost' }, 'total-cost complete');

  // Step: call-count
  const callCount = input.calls.length;
  log.debug({ step: 'call-count' }, 'call-count complete');

  // Step: by-model
  const byModel = (() => {
  const groups = {};
  for (const c of input.calls) {
    const m = c.model;
    if (!groups[m]) groups[m] = { count: 0, cost: 0 };
    groups[m].count++;
    groups[m].cost += c.cost ?? 0;
  }
  return groups;
})();
  log.debug({ step: 'by-model' }, 'by-model complete');

  // Step: avg-cost
  const avgCostPerCall = callCount > 0 ? totalCost / callCount : 0;
  log.debug({ step: 'avg-cost' }, 'avg-cost complete');

  // Step: return
  return {
    totalCost: totalCost,
    callCount: callCount,
    byModel: byModel,
    avgCostPerCall: avgCostPerCall,
  };
}
// --- END GENERATED ---
