/**
 * @generated by @flusk/forge — pipeline generator
 * Identify error rates, error-prone models, and recurring failure patterns
 * Source: packages/schema/pipelines/error-analysis.pipeline.yaml
 */

// --- BEGIN GENERATED (do not edit) ---
// @ts-nocheck — generated pipeline with dynamic expr: steps
import { getLogger } from '@flusk/logger';
import type { LLMCallEntity } from '@flusk/entities';

const log = getLogger().child({ pipeline: 'errorAnalysis' });

export interface ErrorAnalysisInput {
  calls: LLMCallEntity[];
}

export interface ErrorAnalysisOutput {
  totalErrors: number;
  errorRate: number;
  wastedCost: number;
  byModel: Record<string, ModelErrorStats>;
  topErrors: ErrorPattern[];
}

export function errorAnalysis(input: ErrorAnalysisInput): ErrorAnalysisOutput {
  log.debug({ pipeline: 'errorAnalysis' }, 'pipeline start');

  // Step: failed-calls
  const failedCalls = input.calls.filter(c => c.status === 'error');
  log.debug({ step: 'failed-calls' }, 'failed-calls complete');

  // Step: total-errors
  const totalErrors = failedCalls.length;
  log.debug({ step: 'total-errors' }, 'total-errors complete');

  // Step: error-rate
  const errorRate = input.calls.length > 0 ? (totalErrors / input.calls.length) * 100 : 0;
  log.debug({ step: 'error-rate' }, 'error-rate complete');

  // Step: wasted-cost
  const wastedCost = failedCalls.reduce((s, c) => s + (c.cost ?? 0), 0);
  log.debug({ step: 'wasted-cost' }, 'wasted-cost complete');

  // Step: by-model
  const byModel = (() => {
  const groups = {};
  for (const c of input.calls) {
    if (!groups[c.model]) groups[c.model] = [];
    groups[c.model].push(c);
  }
  return Object.fromEntries(
    Object.entries(groups).map(([model, items]) => {
      const errors = items.filter(c => c.status === 'error');
      return [model, {
        total: items.length,
        errors: errors.length,
        errorRate: items.length > 0 ? (errors.length / items.length) * 100 : 0,
        wastedCost: errors.reduce((s, c) => s + (c.cost ?? 0), 0),
      }];
    })
  );
})();
  log.debug({ step: 'by-model' }, 'by-model complete');

  // Step: top-errors
  const topErrors = (() => {
  const groups = {};
  for (const c of failedCalls) {
    const msg = c.errorMessage ?? 'unknown';
    if (!groups[msg]) groups[msg] = [];
    groups[msg].push(c);
  }
  return Object.entries(groups)
    .map(([msg, items]) => ({
      message: msg,
      count: items.length,
      models: [...new Set(items.map(c => c.model))],
    }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);
})();
  log.debug({ step: 'top-errors' }, 'top-errors complete');

  // Step: return
  return {
    totalErrors: totalErrors,
    errorRate: errorRate,
    wastedCost: wastedCost,
    byModel: byModel,
    topErrors: topErrors,
  };
}
// --- END GENERATED ---
