/**
 * @generated by @flusk/forge — pipeline generator
 * Compose cost summary, duplicates, and model comparison into a full report
 * Source: packages/schema/pipelines/session-report.pipeline.yaml
 */

// --- BEGIN GENERATED (do not edit) ---
// @ts-nocheck — generated pipeline with dynamic expr: steps
import { getLogger } from '@flusk/logger';
import type { LLMCallEntity } from '@flusk/entities';
import { costSummary as costSummary_fn } from './cost-summary.pipeline.js';
import { duplicateDetection as duplicateDetection_fn } from './duplicate-detection.pipeline.js';
import { modelComparison as modelComparison_fn } from './model-comparison.pipeline.js';

const log = getLogger().child({ pipeline: 'sessionReport' });

export interface SessionReportInput {
  calls: LLMCallEntity[];
  sessionId: string;
}

export interface SessionReportOutput {
  sessionId: string;
  costSummary: CostSummary;
  duplicates: DuplicateReport;
  modelComparison: ModelComparisonResult;
  overallScore: number;
  generatedAt: string;
}

export function sessionReport(input: SessionReportInput): SessionReportOutput {
  log.debug({ pipeline: 'sessionReport' }, 'pipeline start');

  // Step: cost
  const costSummary = costSummary_fn({ calls: input.calls });
  log.debug({ step: 'cost' }, 'cost complete');

  // Step: dupes
  const duplicates = duplicateDetection_fn({ calls: input.calls });
  log.debug({ step: 'dupes' }, 'dupes complete');

  // Step: models
  const modelComparison = modelComparison_fn({ calls: input.calls });
  log.debug({ step: 'models' }, 'models complete');

  // Step: score
  const overallScore = Math.max(0, Math.min(100,
  100
  - (duplicates.exactDuplicates * 5)
  - (modelComparison.suggestions.length * 10)
  - (costSummary.avgCostPerCall > 0.01 ? 15 : 0)
));
  log.debug({ step: 'score' }, 'score complete');

  // Step: return
  return {
    sessionId: input.sessionId,
    costSummary: costSummary,
    duplicates: duplicates,
    modelComparison: modelComparison,
    overallScore: overallScore,
    generatedAt: new Date().toISOString(),
  };
}
// --- END GENERATED ---
