/**
 * Prompt generator — creates prompt template files from a prompt YAML schema.
 */
import { toCamelCase, toPascalCase } from '../utils.js';
import { generatePromptPythonContent } from './prompt-python.generator.js';
import { loadSchema, writeGenFile } from './prompt-io.js';

export interface PromptVariable {
  name: string;
  type: string;
  description?: string;
}

export interface PromptSchema {
  name: string;
  domain: string;
  description: string;
  template: string;
  variables: PromptVariable[];
}

export interface GenResult {
  files: { path: string; action: 'created' }[];
}

export { generatePromptPythonContent } from './prompt-python.generator.js';

export function generatePromptTemplateContent(schema: PromptSchema): string {
  const pascal = toPascalCase(schema.name);
  const camel = toCamelCase(schema.name);

  return `// --- BEGIN GENERATED ---
/**
 * ${schema.description}
 * @generated by @flusk/forge — prompt generator
 */
import type { ${pascal}Variables } from './${schema.name}.types.js';

export const ${camel}Template = ${JSON.stringify(schema.template)};

/**
 * Render the ${schema.name} prompt with the given variables.
 */
export function render${pascal}(vars: ${pascal}Variables): string {
  let result = ${camel}Template;
${schema.variables.map(v => `  result = result.replace(/\\{\\{${v.name}\\}\\}/g, vars.${toCamelCase(v.name)});`).join('\n')}
  return result;
}
// --- END GENERATED ---
`;
}

export function generatePromptTypesContent(schema: PromptSchema): string {
  const pascal = toPascalCase(schema.name);
  const fields = schema.variables.map(v => {
    const tsType = v.type === 'number' ? 'number' : v.type === 'boolean' ? 'boolean' : 'string';
    const doc = v.description ? `  /** ${v.description} */\n` : '';
    return `${doc}  ${toCamelCase(v.name)}: ${tsType};`;
  });

  return `// --- BEGIN GENERATED ---
/**
 * Variable types for ${schema.name} prompt
 * @generated by @flusk/forge — prompt generator
 */
export interface ${pascal}Variables {
${fields.join('\n')}
}
// --- END GENERATED ---
`;
}

export async function generatePrompt(yamlPath: string): Promise<GenResult> {
  const root = process.cwd();
  const schema = await loadSchema(yamlPath);
  const result: GenResult = { files: [] };
  const domain = schema.domain;

  await writeGenFile(root, `packages/business-logic/src/${domain}/prompts/${schema.name}.prompt.ts`, generatePromptTemplateContent(schema), result);
  await writeGenFile(root, `packages/business-logic/src/${domain}/prompts/${schema.name}.types.ts`, generatePromptTypesContent(schema), result);
  await writeGenFile(root, `flusk-py/src/flusk/prompts/${schema.name}.py`, generatePromptPythonContent(schema), result);

  return result;
}
