/**
 * @generated by @flusk/cli from pattern.entity.ts
 * DO NOT EDIT - regenerate using: flusk g pattern.entity.ts
 */

import type { FastifyRequest, FastifyReply } from 'fastify';

/**
 * Example preHandler hook for Pattern
 * Add business logic hooks here
 */
export async function validatePatternHook(
  _request: FastifyRequest,
  _reply: FastifyReply
): Promise<void> {
  // TODO: Add validation logic
  // Example:
  // const body = request.body as any;
  // if (!body.requiredField) {
  //   return reply.code(400).send({ error: 'requiredField is required' });
  // }
}

/**
 * Example onSend hook for Pattern
 * Add post-processing logic here
 */
export async function transformPatternHook(
  _request: FastifyRequest,
  _reply: FastifyReply,
  payload: any
): Promise<any> {
  // TODO: Add transformation logic
  return payload;
}
