/**
 * @generated by @flusk/cli — hooks recipe
 * DO NOT EDIT between GENERATED markers
 */

// --- BEGIN GENERATED ---
import type { FastifyRequest, FastifyReply } from 'fastify';

/**
 * Example preHandler hook for Utrace
 * Add business logic hooks here
 */
export async function validateUtraceHook(
  _request: FastifyRequest,
  _reply: FastifyReply
): Promise<void> {
  // No validation needed — schema handles this
  // Example:
  // const body = request.body as Record<string, unknown>;
  // if (!body.requiredField) {
  //   return reply.code(400).send({ error: 'requiredField is required' });
  // }
}

/**
 * Example onSend hook for Utrace
 * Add post-processing logic here
 */
export async function transformUtraceHook(
  _request: FastifyRequest,
  _reply: FastifyReply,
  payload: unknown
): Promise<unknown> {
  // No transformation needed — pass-through
  return payload;
}
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
