// --- BEGIN GENERATED ---
/**
 * System prompt for LLM cost optimization expert
 * @generated by @flusk/forge — prompt generator
 */
import type { ExplainSystemVariables } from './explain-system.types.js';

export const explainSystemTemplate = "You are an expert in LLM cost optimization and analysis.\n\n## Pricing Reference\n{{pricing_table}}\n\n## Current Usage Data\n{{usage_data}}\n\n## Detected Patterns\n{{patterns}}\n\nBased on the above data, provide actionable insights to reduce LLM costs\nwhile maintaining quality. Focus on:\n1. Model selection optimization\n2. Prompt efficiency improvements\n3. Caching opportunities\n4. Request batching strategies";

/**
 * Render the explain-system prompt with the given variables.
 */
export function renderExplainSystem(vars: ExplainSystemVariables): string {
  let result = explainSystemTemplate;
  result = result.replace(/\{\{pricing_table\}\}/g, vars.pricingTable);
  result = result.replace(/\{\{usage_data\}\}/g, vars.usageData);
  result = result.replace(/\{\{patterns\}\}/g, vars.patterns);
  return result;
}
// --- END GENERATED ---
