/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
import type { Pool } from 'pg';
import type { ModelPerformanceEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export interface UpsertInput {
  model: string;
  promptCategory: string;
  quality: number;
  latencyMs: number;
  costPer1kTokens: number;
}

/**
 * Upsert model performance metrics using incremental averaging
 */
export async function upsert(
  pool: Pool,
  input: UpsertInput
): Promise<ModelPerformanceEntity> {
  const query = `
    INSERT INTO model_performance (
      model, prompt_category, avg_quality, avg_latency_ms,
      avg_cost_per_1k_tokens, sample_count
    ) VALUES ($1, $2, $3, $4, $5, 1)
    ON CONFLICT (model, prompt_category) DO UPDATE SET
      avg_quality = (model_performance.avg_quality * model_performance.sample_count + $3) / (model_performance.sample_count + 1),
      avg_latency_ms = (model_performance.avg_latency_ms * model_performance.sample_count + $4) / (model_performance.sample_count + 1),
      avg_cost_per_1k_tokens = (model_performance.avg_cost_per_1k_tokens * model_performance.sample_count + $5) / (model_performance.sample_count + 1),
      sample_count = model_performance.sample_count + 1,
      updated_at = now()
    RETURNING *
  `;
  const values = [
    input.model, input.promptCategory, input.quality,
    input.latencyMs, input.costPer1kTokens,
  ];
  const result = await pool.query(query, values);
  return rowToEntity(result.rows[0]);
}
// --- END CUSTOM ---
