/**
 * @generated by @flusk/cli — client recipe
 * Webhook client — fire-and-forget POST to Slack/Discord webhooks
 */

// --- BEGIN GENERATED ---
import { request } from 'undici';
import { createLogger } from '@flusk/logger';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
const log = createLogger({ name: 'webhook' });

const PRIVATE_IP_PATTERNS = [
  /^127\./,
  /^10\./,
  /^172\.(1[6-9]|2\d|3[01])\./,
  /^192\.168\./,
  /^169\.254\./,
  /^0\./,
];

function validateWebhookUrl(rawUrl: string): void {
  const parsed = new URL(rawUrl);
  const isDev = process.env['NODE_ENV'] === 'development' || process.env['NODE_ENV'] === 'test';

  // In dev/test, allow any URL (tests use mock servers, dev uses localhost)
  if (isDev) return;

  if (parsed.protocol !== 'https:') {
    throw new Error(`Webhook URL must use HTTPS (got ${parsed.protocol})`);
  }

  const host = parsed.hostname;
  const isLocalhost = host === 'localhost' || host === '127.0.0.1';
  if (host === '::1' || host.startsWith('fc') || host.startsWith('fd') || isLocalhost) {
    throw new Error(`Webhook URL blocked: private/reserved address (${host})`);
  }

  for (const pattern of PRIVATE_IP_PATTERNS) {
    if (pattern.test(host)) {
      throw new Error(`Webhook URL blocked: private IP range (${host})`);
    }
  }
}

export interface WebhookPayload {
  text: string;
}

export class WebhookClient {
  private url: string;

  constructor(url: string) {
    validateWebhookUrl(url);
    this.url = url;
  }

  async send(payload: WebhookPayload, retries = 3): Promise<void> {
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        const res = await request(this.url, {
          method: 'POST' as const,
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(payload),
        });
        if (res.statusCode >= 400) {
          const errMsg = `HTTP ${res.statusCode}`;
          log.warn({ url: this.url.slice(0, 40), attempt, status: res.statusCode }, `Webhook response error: ${errMsg}`);
          if (attempt < retries && res.statusCode >= 500) {
            await new Promise((r) => setTimeout(r, attempt * 1000));
            continue;
          }
          throw new Error(errMsg);
        }
        log.info({ url: this.url.slice(0, 40) + '...' }, 'Webhook sent');
        return;
      } catch (err) {
        log.error({ error: err, attempt, url: this.url.slice(0, 40) }, `Webhook failed (attempt ${attempt}/${retries})`);
        if (attempt < retries) {
          await new Promise((r) => setTimeout(r, attempt * 1000));
        }
      }
    }
  }

  fireAndForget(alerts: string[]): void {
    if (alerts.length === 0) return;
    const text = `🚨 Flusk Budget Alert\n${alerts.map((a) => `• ${a}`).join('\n')}`;
    void this.send({ text });
  }
}

/**
 * Convenience: standalone fire-and-forget (backwards compat)
 */
export function sendWebhook(
  url: string,
  payload: WebhookPayload,
): Promise<void> {
  return new WebhookClient(url).send(payload);
}

export function fireAndForget(
  url: string | undefined,
  alerts: string[],
): void {
  if (!url || alerts.length === 0) return;
  new WebhookClient(url).fireAndForget(alerts);
}
// --- END CUSTOM ---
