/**
 * @generated by @flusk/cli — business-logic recipe
 */

// --- BEGIN GENERATED ---
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
export interface DetectTemplateInput {
  prompt: string;
}

export interface DetectTemplateOutput {
  isTemplate: boolean;
  templatePattern: string | null;
  variables: string[];
  templateTag: string | null;
}

const PLACEHOLDER_REGEX = /\{(\w+)\}/g;
const COMMON_PREFIXES = [
  'You are a',
  'You are an',
  'Act as a',
  'As a',
  'Given the following',
  'Based on the',
  'Summarize the',
  'Translate the',
  'Answer the following',
];

/**
 * Detect prompt template patterns from runtime LLM calls.
 * Identifies variable placeholders like {role}, {context}, {input}
 * and common system prompt prefixes.
 *
 * @param input - The prompt text to analyze
 * @returns Template detection result with variables and tag
 */
export function detectTemplate(
  input: DetectTemplateInput
): DetectTemplateOutput {
  const { prompt } = input;
  const variables: string[] = [];
  let match: RegExpExecArray | null;

  const regex = new RegExp(PLACEHOLDER_REGEX.source, 'g');
  while ((match = regex.exec(prompt)) !== null) {
    if (!variables.includes(match[1]!)) {
      variables.push(match[1]!);
    }
  }

  const hasPlaceholders = variables.length > 0;
  const prefix = COMMON_PREFIXES.find((p) =>
    prompt.trimStart().startsWith(p)
  );

  const isTemplate = hasPlaceholders || prefix !== undefined;
  let templateTag: string | null = null;

  if (hasPlaceholders && prefix) {
    templateTag = `system-prompt:${variables.join(',')}`;
  } else if (hasPlaceholders) {
    templateTag = `parameterized:${variables.join(',')}`;
  } else if (prefix) {
    templateTag = 'system-prompt:static';
  }

  const templatePattern = isTemplate
    ? prompt.replace(PLACEHOLDER_REGEX, '{$1}')
    : null;

  return { isTemplate, templatePattern, variables, templateTag };
}
// --- END CUSTOM ---
