/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/math/average.fn.yaml
 */

/**
 * Calculate the arithmetic mean of an array of numbers
 */
export function average(values: number[]): number {
  const total = values.reduce((acc, v) => acc + v, 0);
    return values.length === 0 ? 0 : total / values.length;
}
