/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/math/clamp.fn.yaml
 */

/**
 * Clamp a number between a minimum and maximum value
 */
export function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}
