/**
 * Render functions for the function generator — code output.
 */

import type { FnSchema } from './function.types.js';
import { toKebabCase } from '../utils.js';

/** Render TypeScript function body from schema */
function renderBody(schema: FnSchema): string {
  const { body } = schema;
  if (typeof body === 'string') {
    return body.trim();
  }
  const steps = body.steps;
  const lines: string[] = [];
  for (const step of steps) {
    if ('return' in step && step.return && !('name' in step)) {
      lines.push(`  return ${(step.return as string).trim()};`);
    } else if ('name' in step && step.name) {
      lines.push(`  const ${step.name} = ${(step.expr ?? '').trim()};`);
    }
  }
  return `{\n${lines.join('\n')}\n}`;
}

/** Render param list for function signature */
function renderParams(schema: FnSchema): string {
  return Object.entries(schema.input)
    .map(([k, v]) => `${k}: ${v.type}`)
    .join(', ');
}

/** Render TypeScript function file content */
export function renderFunctionContent(schema: FnSchema): string {
  const typeParam = schema.generic && schema.typeParams?.length
    ? `<${schema.typeParams.join(', ')}>`
    : '';
  const params = renderParams(schema);
  const returnType = schema.output.type;
  const body = renderBody(schema);

  const isSimpleExpr = typeof schema.body === 'string' || (
    typeof schema.body === 'object' && !schema.body.steps.some(s => 'name' in s)
  );

  const bodyStr = isSimpleExpr && typeof schema.body === 'string'
    ? `  return ${body};`
    : body.startsWith('{') ? body.slice(1, -1).trim().split('\n').map(l => `  ${l}`).join('\n')
    : `  return ${body};`;

  return `/**
 * @generated by @flusk/cli — function generator
 * Source: packages/schema/functions/${schema.namespace}/${toKebabCase(schema.name)}.fn.yaml
 */

/**
 * ${schema.description}
 */
export function ${schema.name}${typeParam}(${params}): ${returnType} {
${bodyStr}
}
`;
}
