/**
 * Python function generator — .fn.yaml → Python functions + pytest tests.
 *
 * WHY: Same YAML definitions used for TypeScript are reused to generate
 * Python equivalents, keeping both packages in sync.
 */

import { resolve } from 'node:path';
import { writeFile, mkdir, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import type { FnSchema } from '../function.generator.js';
import { toSnakeCase } from '../utils.js';

const PY_PRIMITIVES = 'flusk-py/src/flusk/primitives';
const PY_TESTS = 'flusk-py/tests/primitives';

/** Map TypeScript type strings to Python type annotations */
function toPyType(tsType: string): string {
  return tsType
    .replace(/number\[\]/g, 'list[float]')
    .replace(/string\[\]/g, 'list[str]')
    .replace(/number/g, 'float')
    .replace(/string/g, 'str')
    .replace(/boolean/g, 'bool')
    .replace(/unknown/g, 'Any')
    .replace(/T\[\]/g, 'list[T]')
    .replace(/T \| undefined/g, 'Optional[T]')
    .replace(/undefined/g, 'None')
    .replace(/"[^"]+"/g, 'str')
    .replace(/Map<[^>]+>/g, 'dict');
}

/** Render Python function file */
export function renderPyFunctionContent(schema: FnSchema): string {
  const snakeName = toSnakeCase(schema.name);
  const params = Object.entries(schema.input)
    .map(([k, v]) => `${toSnakeCase(k)}: ${toPyType(v.type)}`)
    .join(', ');
  const returnType = toPyType(schema.output.type);

  const needsAny = Object.values(schema.input).some(v => v.type === 'unknown') ||
    schema.output.type.includes('unknown');
  const needsOptional = schema.output.type.includes('undefined') || schema.output.type.includes('T |');
  const imports: string[] = [];
  if (needsAny) imports.push('from typing import Any');
  if (needsOptional) imports.push('from typing import Optional');
  if (schema.generic) imports.push('from typing import TypeVar\nT = TypeVar("T")');
  const importBlock = imports.length ? imports.join('\n') + '\n\n' : '';

  return `# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/${schema.namespace}/${schema.name}.fn.yaml
${importBlock}
def ${snakeName}(${params}) -> ${returnType}:
    """${schema.description}"""
    raise NotImplementedError("${snakeName} — implement from YAML body")
`;
}

/** Render pytest test file */
export function renderPyTestContent(schema: FnSchema): string {
  const snakeName = toSnakeCase(schema.name);
  const moduleName = snakeName;

  const testCases = schema.tests.map((t) => {
    const testName = toSnakeCase(t.name.replace(/[^a-zA-Z0-9 ]/g, '').replace(/ /g, '_'));
    const args = Object.values(t.input)
      .map((v) => JSON.stringify(v).replace(/null/g, 'None').replace(/true/g, 'True').replace(/false/g, 'False'))
      .join(', ');
    const expected = JSON.stringify(t.expected)
      .replace(/null/g, 'None')
      .replace(/true/g, 'True')
      .replace(/false/g, 'False');
    return `def test_${testName}():
    assert ${snakeName}(${args}) == ${expected}`;
  }).join('\n\n\n');

  return `# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.${schema.namespace}.${moduleName} import ${snakeName}


${testCases}
`;
}

/** Render Python __init__.py for a namespace */
export function renderPyNamespaceInit(schema: FnSchema[], _namespace: string): string {
  const exports = schema.map(s => `from .${toSnakeCase(s.name)} import ${toSnakeCase(s.name)}`).join('\n');
  return `# @generated by @flusk/cli — python function generator
${exports}

__all__ = [${schema.map(s => `"${toSnakeCase(s.name)}"`).join(', ')}]
`;
}

/** Generate Python files for a single function schema */
export async function generatePyFunction(
  schema: FnSchema,
  projectRoot: string,
): Promise<Array<{ path: string; action: 'created' | 'updated' }>> {
  const snakeName = toSnakeCase(schema.name);
  const nsDir = resolve(projectRoot, `${PY_PRIMITIVES}/${schema.namespace}`);
  const testDir = resolve(projectRoot, `${PY_TESTS}/${schema.namespace}`);

  await mkdir(nsDir, { recursive: true });
  await mkdir(testDir, { recursive: true });

  const results: Array<{ path: string; action: 'created' | 'updated' }> = [];

  // Ensure __init__.py in test dir
  const testInitPath = resolve(testDir, '__init__.py');
  if (!existsSync(testInitPath)) {
    await writeFile(testInitPath, '# @generated by @flusk/cli\n', 'utf-8');
    results.push({ path: `${PY_TESTS}/${schema.namespace}/__init__.py`, action: 'created' });
  }

  // Function file
  const fnPath = resolve(nsDir, `${snakeName}.py`);
  const fnAction = existsSync(fnPath) ? 'updated' : 'created';
  await writeFile(fnPath, renderPyFunctionContent(schema), 'utf-8');
  results.push({ path: `${PY_PRIMITIVES}/${schema.namespace}/${snakeName}.py`, action: fnAction });

  // Test file
  const testPath = resolve(testDir, `test_${snakeName}.py`);
  const testAction = existsSync(testPath) ? 'updated' : 'created';
  await writeFile(testPath, renderPyTestContent(schema), 'utf-8');
  results.push({ path: `${PY_TESTS}/${schema.namespace}/test_${snakeName}.py`, action: testAction });

  return results;
}

/** Write namespace __init__.py after all functions in namespace are generated */
export async function updatePyNamespaceInit(
  namespace: string,
  projectRoot: string,
): Promise<{ path: string; action: 'created' | 'updated' }> {
  const nsDir = resolve(projectRoot, `${PY_PRIMITIVES}/${namespace}`);
  const files = await readdir(nsDir);
  const names = files
    .filter(f => f.endsWith('.py') && f !== '__init__.py')
    .map(f => f.replace('.py', ''));
  const exports = names.map(n => `from .${n} import ${n}`).join('\n');
  const content = `# @generated by @flusk/cli — python function generator\n${exports}\n\n__all__ = [${names.map(n => `"${n}"`).join(', ')}]\n`;
  const initPath = resolve(nsDir, '__init__.py');
  const action = existsSync(initPath) ? 'updated' : 'created';
  await writeFile(initPath, content, 'utf-8');
  return { path: `${PY_PRIMITIVES}/${namespace}/__init__.py`, action };
}

/** Write top-level primitives __init__.py */
export async function updatePyPrimitivesInit(
  namespaces: string[],
  projectRoot: string,
): Promise<{ path: string; action: 'created' | 'updated' }> {
  const primDir = resolve(projectRoot, PY_PRIMITIVES);
  await mkdir(primDir, { recursive: true });
  const exports = namespaces.map(ns => `from . import ${ns}`).join('\n');
  const content = `# @generated by @flusk/cli — python function generator\n${exports}\n\n__all__ = [${namespaces.map(ns => `"${ns}"`).join(', ')}]\n`;
  const initPath = resolve(primDir, '__init__.py');
  const action = existsSync(initPath) ? 'updated' : 'created';
  await writeFile(initPath, content, 'utf-8');
  return { path: `${PY_PRIMITIVES}/__init__.py`, action };
}
