/**
 * Python code renderers — function files, test files, __init__.py.
 */

import type { FnSchema } from '../function.generator.js';
import { toSnakeCase } from '../utils.js';
import { toPyType } from './py-type-mapper.js';

/** Render Python function file */
export function renderPyFunctionContent(schema: FnSchema): string {
  const snakeName = toSnakeCase(schema.name);
  const params = Object.entries(schema.input)
    .map(([k, v]) => `${toSnakeCase(k)}: ${toPyType(v.type)}`)
    .join(', ');
  const returnType = toPyType(schema.output.type);

  const needsAny = Object.values(schema.input).some(v => v.type === 'unknown') ||
    schema.output.type.includes('unknown');
  const needsOptional = schema.output.type.includes('undefined') ||
    schema.output.type.includes('T |');
  const imports: string[] = [];
  if (needsAny) imports.push('from typing import Any');
  if (needsOptional) imports.push('from typing import Optional');
  if (schema.generic) imports.push('from typing import TypeVar\nT = TypeVar("T")');
  const importBlock = imports.length ? imports.join('\n') + '\n\n' : '';

  return `# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/${schema.namespace}/${schema.name}.fn.yaml
${importBlock}
def ${snakeName}(${params}) -> ${returnType}:
    """${schema.description}"""
    raise NotImplementedError("${snakeName} — implement from YAML body")
`;
}

/** Render pytest test file */
export function renderPyTestContent(schema: FnSchema): string {
  const snakeName = toSnakeCase(schema.name);
  const moduleName = snakeName;

  const testCases = schema.tests.map((t) => {
    const testName = toSnakeCase(
      t.name.replace(/[^a-zA-Z0-9 ]/g, '').replace(/ /g, '_'),
    );
    const args = Object.values(t.input)
      .map((v) => JSON.stringify(v)
        .replace(/null/g, 'None')
        .replace(/true/g, 'True')
        .replace(/false/g, 'False'))
      .join(', ');
    const expected = JSON.stringify(t.expected)
      .replace(/null/g, 'None')
      .replace(/true/g, 'True')
      .replace(/false/g, 'False');
    return `def test_${testName}():
    assert ${snakeName}(${args}) == ${expected}`;
  }).join('\n\n\n');

  return `# @generated by @flusk/cli — python function generator
import pytest
from flusk.primitives.${schema.namespace}.${moduleName} import ${snakeName}


${testCases}
`;
}

/** Render Python __init__.py for a namespace */
export function renderPyNamespaceInit(
  schema: FnSchema[],
  _namespace: string,
): string {
  const exports = schema
    .map(s => `from .${toSnakeCase(s.name)} import ${toSnakeCase(s.name)}`)
    .join('\n');
  return `# @generated by @flusk/cli — python function generator
${exports}

__all__ = [${schema.map(s => `"${toSnakeCase(s.name)}"`).join(', ')}]
`;
}
