/**
 * Template for .gitignore generation
 * Comprehensive ignore patterns for Node.js/TypeScript Flusk projects
 */

/**
 * Generate .gitignore template for Flusk projects
 */
export function generateGitignoreTemplate(): string {
  return `# Flusk Project .gitignore
# Generated by @flusk/cli

# ============================================
# Dependencies
# ============================================
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*
.pnpm-store/
.yarn/
.yarnrc.yml

# ============================================
# Build Output
# ============================================
dist/
build/
out/
*.tsbuildinfo
.rpt2_cache/
.nx/cache

# ============================================
# Environment & Secrets
# ============================================
.env
.env.local
.env.*.local
.env.production
.env.development
.env.test
*.pem
*.key
*.crt
.secrets/

# Keep .env.example for documentation
!.env.example

# ============================================
# TypeScript
# ============================================
*.tsbuildinfo
tsconfig.tsbuildinfo

# ============================================
# Testing
# ============================================
coverage/
.nyc_output/
*.lcov
.vitest/
.jest/

# ============================================
# Database & Cache
# ============================================
*.sqlite
*.sqlite3
*.db
.postgres/
.redis/
redis-dump.rdb
dump.rdb

# ============================================
# Docker
# ============================================
docker-compose.override.yml
.dockerignore
docker/postgres/data/
docker/redis/data/

# Keep docker init scripts
!docker/postgres/init/

# ============================================
# Logs
# ============================================
logs/
*.log
npm-debug.log*
yarn-debug.log*
pnpm-debug.log*
lerna-debug.log*

# ============================================
# IDEs & Editors
# ============================================
# VS Code
.vscode/
!.vscode/extensions.json
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
*.code-workspace

# JetBrains IDEs
.idea/
*.iml
*.ipr
*.iws

# Sublime Text
*.sublime-project
*.sublime-workspace

# Vim
*.swp
*.swo
*~

# Emacs
*~
\#*\#
.\#*

# ============================================
# OS Files
# ============================================
# macOS
.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes

# Windows
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/

# Linux
*~
.directory
.Trash-*/

# ============================================
# Temporary Files
# ============================================
tmp/
temp/
*.tmp
*.temp
.cache/
.parcel-cache/

# ============================================
# Platformatic Watt
# ============================================
.platformatic/
.watt/

# ============================================
# Flusk Specific
# ============================================
# Generated migrations (keep source migrations)
packages/resources/src/migrations/*.generated.ts

# Generated types (regenerated from entities)
packages/types/src/*.generated.ts

# Local development overrides
watt.local.json
docker-compose.local.yml

# ============================================
# Misc
# ============================================
.turbo/
.vercel/
.next/
.nuxt/
.output/
.vite/
`;
}
