# @generated by @flusk/cli — python function generator
# Source: packages/schema/functions/collection/sortBy.fn.yaml
from typing import TypeVar
T = TypeVar("T")


def sort_by(items: list[T], key: str, direction: str | str) -> list[T]:
    """Sort an array of objects by a key, ascending or descending"""
    raise NotImplementedError("sort_by — implement from YAML body")
