/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';

export interface ModelCount {
  model: string;
  count: number;
}

/**
 * Count training pairs grouped by source model
 */
export function countByModelGrouped(db: DatabaseSync): ModelCount[] {
  const stmt = db.prepare(
    'SELECT source_model as model, COUNT(*) as count FROM training_pairs GROUP BY source_model ORDER BY count DESC',
  );
  return stmt.all() as unknown as ModelCount[];
}
// --- END GENERATED ---
