/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { TrainingPairEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Insert a new Training pair record into SQLite
 */
export function create(
  db: DatabaseSync,
  data: Omit<TrainingPairEntity, 'id' | 'createdAt' | 'updatedAt'>,
): TrainingPairEntity {
  const stmt = db.prepare(`
    INSERT INTO training_pairs (
      tenant_id, source_model, source_provider, prompt, completion,
      system_prompt, input_tokens, output_tokens, quality, cluster,
      metadata
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    RETURNING *
  `);

  const row = stmt.get(
    data.tenantId ?? null,
    data.sourceModel,
    data.sourceProvider,
    data.prompt,
    data.completion,
    data.systemPrompt ?? null,
    data.inputTokens,
    data.outputTokens,
    data.quality,
    data.cluster ?? null,
    data.metadata != null ? JSON.stringify(data.metadata) : null,
  ) as Record<string, unknown>;

  return rowToEntity(row);
}
// --- END GENERATED ---
