/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { TrainingPairEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * Find training pairs in a specific cluster
 */
export function findByCluster(
  db: DatabaseSync, cluster: string,
): TrainingPairEntity[] {
  const stmt = db.prepare(
    'SELECT * FROM training_pairs WHERE cluster = ? ORDER BY created_at DESC',
  );
  const rows = stmt.all(cluster) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}
// --- END GENERATED ---
