/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { DatabaseSync } from 'node:sqlite';
import type { TrainingPairEntity } from '@flusk/entities';
import { rowToEntity } from './row-to-entity.js';

/**
 * List training pairs by source model with pagination
 */
export function listByModel(
  db: DatabaseSync, sourceModel: string,
): TrainingPairEntity[] {
  const stmt = db.prepare(
    'SELECT * FROM training_pairs WHERE source_model = ? ORDER BY created_at DESC',
  );
  const rows = stmt.all(sourceModel) as Record<string, unknown>[];
  return rows.map(rowToEntity);
}
// --- END GENERATED ---
