/** @generated by @flusk/forge — multi-file repo */
// --- BEGIN GENERATED (do not edit) ---
import type { TrainingPairEntity } from '@flusk/entities';
import { toISOString } from '../../../shared/map-row.js';

/** Convert SQLite row to TrainingPairEntity */
export function rowToEntity(row: Record<string, unknown>): TrainingPairEntity {
  return {
    id: row.id as string,
    createdAt: toISOString(row.created_at),
    updatedAt: toISOString(row.updated_at),
    tenantId: (row.tenant_id as string) ?? undefined,
    sourceModel: row.source_model as string,
    sourceProvider: row.source_provider as 'anthropic' | 'openai' | 'google',
    prompt: row.prompt as string,
    completion: row.completion as string,
    systemPrompt: (row.system_prompt as string) ?? undefined,
    inputTokens: row.input_tokens as number,
    outputTokens: row.output_tokens as number,
    quality: row.quality as 'unrated' | 'good' | 'flagged' | 'rejected',
    cluster: (row.cluster as string) ?? undefined,
    metadata: row.metadata != null ? JSON.parse(row.metadata as string) : undefined,
  };
}
// --- END GENERATED ---
