/**
 * @generated by @flusk/cli — client recipe
 */

// --- BEGIN GENERATED ---
export { create } from './create.js';
export { findByRule } from './find-by-rule.js';
export { getSavingsSummary } from './get-savings-summary.js';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
