/**
 * @generated by @flusk/cli — business-logic recipe
 * Budget types — canonical definitions live in @flusk/types
 */

// --- BEGIN GENERATED ---
export type {
  BudgetLimits,
  UsageData,
  BudgetPeriod,
  BudgetStatus,
  PerCallAlert,
  DuplicateAlert,
} from '@flusk/types';
// --- END GENERATED ---

// --- BEGIN CUSTOM ---
// --- END CUSTOM ---
